### ISSUE TITLE
Build error on multiple libraries. ninja: error: FindFirstFileExA

### ISSUE THREAD

**Issue by ma-blip** [m-ab-s/media-autobuild_suite#1646] opened 2020-05-11 15:06 UTC
All of a sudden getting Ninja errors on multiple libraries. Getting the same errors on multiple libraries that dit not have any problem a couple of days ago. Updated to the last version.

Likely error (tail of the failed operation logfile):
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
ninja -j1 install
ninja: error: FindFirstFileExA(c/:/media-autobuild_suite-master/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.1.0/include-fixed):

The path looks a bit weird to me?

Tried on two diffrent computers.

/M

**Comment by 1480c1** [comment] 2020-05-11 15:06
duplicate of #1644

**Closed by 1480c1** 2020-05-11 15:06 UTC
