### ISSUE TITLE
MinGW64 GCC compiler isn't installed; maybe the download didn't work

### ISSUE THREAD

**Issue by shevachr** [m-ab-s/media-autobuild_suite#1769] opened 2020-07-24 15:43 UTC
i receive the following error: 
MinGW64 GCC compiler isn't installed; maybe the download didn't work

the process is stuck.

**Comment by 1480c1** [comment] 2020-07-24 16:21
can you try getting a screen shot?

One alternative I could try to offer is try setting noMintty inside build/media-autobuild_suite.ini to 1

**Comment by dollabi11z** [comment] 2020-07-24 19:18
Same error I'll try your ini fix

**Comment by dollabi11z** [comment] 2020-07-24 19:22
That did it thx! Just wanna send a thx to you or whoever maintains this. I mainly use this to get a windows ffmpeg with FDKAAC, been uses this for year. I know it's changed owners 2-3 times but regardless... THANK YOU, THANK YOU & also THANK YOU :)

**Comment by shevachr** [comment] 2020-07-25 11:58
the problem is resoleved if run the batch file media-autobuild_suite.bat in the command prompt as administrator. 

however ffmpeg.exe in "media-autobuild_suite\local64\bin-video" is not static and requires dll-files from "NVIDIA GPU Computing Toolkit\CUDA\v10.1" . 

i bypassed the issue by compiling directly ffmpeg sources as static (located at "media-autobuild_suite\build\ffmpeg-git") by means of Mingw (media-autobuild_suite\msys64) : 
./configure --enable-gpl --enable-static --disable-shared --enable-libmfx
make

**Comment by creechy** [comment] 2020-07-26 14:41
I'm stuck on the same step. setting noMintty=1 doesn't do anything for me, but exposes the messages

`-------------------------------------------------------------------------------`
`install msys2 base system`
`-------------------------------------------------------------------------------`
`/usr/bin/bash: /build/pacman.sh: No such file or directory`
`-------------------------------------------------------------------------------`
`install 64 bit compiler`
`-------------------------------------------------------------------------------`
`/usr/bin/bash: /build/mingw.sh: No such file or directory`
`-------------------------------------------------------------------------------`

`MinGW64 GCC compiler isn't installed; maybe the download didn't work`
`Do you want to try it again?`

`-------------------------------------------------------------------------------`

I did not try running as an Administrator, that seems like overkill. 
I do see mingw.sh in the build/ folder.

Any thoughts?

**Comment by 1480c1** [comment] 2020-07-26 16:23
the issue with that is it looks like it's not reading fstab properly, so none of the scripts would actually work as intended.

I do know that it sometimes occurs, but I do not know exactly what might fix it since it usually goes away after either rebooting, closing all programs using msys.dll, flipping noMintty back and forth, and sometimes deleting msys64 and restarting, etc

**Comment by creechy** [comment] 2020-07-26 16:34
That makes sense. There were downstream problems after the set up completed. Thanks, I'll give it another try.

**Closed** 2020-07-28 03:45 UTC
