### ISSUE TITLE
mingw64 opus build error

### ISSUE THREAD

**Issue by kliffgomel** [m-ab-s/media-autobuild_suite#2597] opened 2024-02-04 19:06 UTC
21:54:45 ┌ opus git  .................................... [Updates found]
21:54:46 ├ Running uninstall...
21:54:46 ├ Running autogen...
Likely error (tail of the failed operation logfile):
CXXFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -march=znver2 -O3 -pipe -D__USE_MINGW_ANSI_STDIO=1 -Wno-implicit-function-declaration
LDFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -march=znver2 -O3 -pipe -D__USE_MINGW_ANSI_STDIO=1 -Wno-implicit-function-declaration -static-libgcc --start-no-unused-arguments -static-libstdc++ --end-no-unused-arguments
./autogen.sh
Downloading latest model
--2024-02-04 21:54:47--  https://media.xiph.org/opus/models/opus_data-ec04a94.tar.gz
Loaded CA certificate '/usr/ssl/certs/ca-bundle.crt'
Resolving media.xiph.org (media.xiph.org)... 54.39.18.101, 2607:5300:203:2965::
Connecting to media.xiph.org (media.xiph.org)|54.39.18.101|:443... connected.
ERROR: The certificate of ‘media.xiph.org’ is not trusted.
ERROR: The certificate of ‘media.xiph.org’ doesn't have a known issuer.
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/14157975/logs.zip)

**Comment by L4cache** [comment] 2024-02-05 21:33
That's obviously not m-ab-s problem, but some patch can be done to make it ignore this certificate thing. However I looked the certificate, it's from a legit and popular issuer, although being a free one which may cause abuse, it's really weird that your system distrust it.

**Comment by kliffgomel** [comment] 2024-02-07 16:33
Still need a patch

**Comment by L4cache** [comment] 2024-02-10 17:52
I just ran the suite with opus again (fresh, no previous opus git clone or build) and it works fine. You still have problem?
I think the problem is on you system or isp, dns hijacking maybe, or your system is super paranoid about security and distrusts let's encrypt.

**Comment by classicdoomenjoyer** [comment] 2024-02-11 13:20
Even I am having the same problem :(

**Comment by classicdoomenjoyer** [comment] 2024-02-11 13:20
> 21:54:45 ┌ opus git .................................... [Updates found] 21:54:46 ├ Running uninstall... 21:54:46 ├ Running autogen... Likely error (tail of the failed operation logfile): CXXFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -march=znver2 -O3 -pipe -D__USE_MINGW_ANSI_STDIO=1 -Wno-implicit-function-declaration LDFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -march=znver2 -O3 -pipe -D__USE_MINGW_ANSI_STDIO=1 -Wno-implicit-function-declaration -static-libgcc --start-no-unused-arguments -static-libstdc++ --end-no-unused-arguments ./autogen.sh Downloading latest model --2024-02-04 21:54:47-- https://media.xiph.org/opus/models/opus_data-ec04a94.tar.gz Loaded CA certificate '/usr/ssl/certs/ca-bundle.crt' Resolving media.xiph.org (media.xiph.org)... 54.39.18.101, 2607:5300:203:2965:: Connecting to media.xiph.org (media.xiph.org)|54.39.18.101|:443... connected. ERROR: The certificate of ‘media.xiph.org’ is not trusted. ERROR: The certificate of ‘media.xiph.org’ doesn't have a known issuer. [logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/14157975/logs.zip)

Even I am having the exact same problem :(

**Comment by Biswa96** [comment] 2024-02-11 14:09
Some/I can reproduce the issue and others do not. For quick workaround, try to remove the whole `dnn/download_model.sh` line in opus/autogen.sh file.

**Comment by kliffgomel** [comment] 2024-02-11 15:23
I still can't build the project
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/14232874/logs.zip)

**Comment by 1480c1** [comment] 2024-02-22 16:42
Fixed with https://github.com/m-ab-s/media-autobuild_suite/commit/0c689127fd309ae0d401707e19f9cef6a5f653a1

**Closed by 1480c1** 2024-02-22 16:42 UTC
