### ISSUE TITLE
cyanrip fails linking, seems to access the full ffmpeg instead of local libavfilter library

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1409] opened 2019-09-27 11:45 UTC
Reporting for a Win32 target compilation here.

The building and installation process for cyanrip backed up several previously built libav libraries in the `local32/lib` directory, but not libavfilter.a – which appears to be accessed in the linking step.

The file **build/cyanrip-git/build-32bit/src/cyanrip.exe.rsp** contains references to several libav libraries in a directory `local32/opt/cyanffmpeg/lib` except for `local32/lib/libavfilter.a` (see about the center of the following quote) so I guess it needs to be added to a list of substitutions now.

[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/3662564/ab-suite.build.log)

**cyanrip.exe.rsp**
>  -o src/cyanrip.exe src/25a6634@@cyanrip@exe/cyanrip_encode.c.obj src/25a6634@@cyanrip@exe/cyanrip_log.c.obj src/25a6634@@cyanrip@exe/cyanrip_main.c.obj "-IE:/MABS/local32/opt/cyanffmpeg/include" "-IE:/MABS/local32/include" "-LE:/MABS/local32/opt/cyanffmpeg/lib" "-LE:/MABS/local32/lib" "-Wl,-O1" "-mthreads" "-mtune=generic" "-O2" "-pipe" "-DLIBXML_STATIC" "-static-libgcc" "-static-libstdc++" "-Wl,--start-group" "E:/MABS/msys64/mingw32/lib/libcdio.a" "-lm" "E:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/lib/../lib/libwinmm.a" "E:/MABS/msys64/mingw32/lib/libiconv.a" "E:/MABS/msys64/mingw32/lib/libcdio_paranoia.a" "E:/MABS/msys64/mingw32/lib/libcdio_cdda.a" "E:/MABS/local32/lib/libdiscid.a" "E:/MABS/local32/lib/libmusicbrainz5.a" "E:/MABS/local32/lib/libmusicbrainz5cc.a" "E:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/libstdc++.a" "E:/MABS/local32/lib/libneon.a" "E:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/lib/../lib/libws2_32.a" "E:/MABS/msys64/mingw32/lib/libz.a" "E:/MABS/msys64/mingw32/lib/libxml2.a" "E:/MABS/msys64/mingw32/lib/liblzma.a" "E:/MABS/local32/opt/cyanffmpeg/lib/libavcodec.a" "E:/MABS/msys64/mingw32/lib/libmp3lame.a" "E:/MABS/local32/lib/libopus.a" "E:/MABS/msys64/mingw32/lib/libvorbis.a" "E:/MABS/msys64/mingw32/lib/libogg.a" "E:/MABS/msys64/mingw32/lib/libvorbisenc.a" "E:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/lib/../lib/libole32.a" "E:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/lib/../lib/libuser32.a" "E:/MABS/local32/opt/cyanffmpeg/lib/libavutil.a" "E:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/lib/../lib/libbcrypt.a" "E:/MABS/local32/opt/cyanffmpeg/lib/libavformat.a" "E:/MABS/local32/opt/cyanffmpeg/lib/libswresample.a" "E:/MABS/local32/lib/libavfilter.a" "-pthread" "E:/MABS/local32/lib/libbs2b.a" "E:/MABS/local32/lib/librubberband.a" "E:/MABS/local32/lib/libmysofa.a" "E:/MABS/local32/lib/libflite_cmu_time_awb.a" "E:/MABS/local32/lib/libflite_cmu_us_awb.a" "E:/MABS/local32/lib/libflite_cmu_us_kal.a" "E:/MABS/local32/lib/libflite_cmu_us_kal16.a" "E:/MABS/local32/lib/libflite_cmu_us_rms.a" "E:/MABS/local32/lib/libflite_cmu_us_slt.a" "E:/MABS/local32/lib/libflite_usenglish.a" "E:/MABS/local32/lib/libflite_cmulex.a" "E:/MABS/local32/lib/libflite.a" "E:/MABS/local32/lib/libfribidi.a" "E:/MABS/local32/lib/libtesseract.a" "-lpthread" "E:/MABS/local32/lib/liblept.a" "E:/MABS/msys64/mingw32/lib/libpng16.a" "E:/MABS/msys64/mingw32/lib/libjpeg.a" "E:/MABS/local32/lib/libtiff.a" "E:/MABS/msys64/mingw32/lib/libzstd.a" "E:/MABS/msys64/mingw32/lib/libarchive.a" "E:/MABS/msys64/mingw32/lib/libnettle.a" "E:/MABS/msys64/mingw32/lib/libregex.a" "E:/MABS/msys64/mingw32/lib/libexpat.a" "E:/MABS/msys64/mingw32/lib/liblz4.a" "E:/MABS/msys64/mingw32/lib/libbz2.a" "E:/MABS/local32/lib/libass.a" "E:/MABS/local32/lib/libharfbuzz.a" "E:/MABS/local32/lib/libfontconfig.a" "E:/MABS/msys64/mingw32/lib/libintl.a" "E:/MABS/local32/lib/libfreetype.a" "E:/MABS/local32/lib/libvidstab.a" "E:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/libgomp.a" "E:/MABS/msys64/mingw32/lib/libzmq.a" "E:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/lib/../lib/libiphlpapi.a" "E:/MABS/msys64/mingw32/lib/libsodium.a" "E:/MABS/local32/lib/libzimg.a" "E:/MABS/local32/lib/libOpenCL.a" "-ldl" "E:/MABS/local32/lib/libmfx.a" "E:/MABS/local32/lib/libswscale.a" "E:/MABS/local32/lib/libpostproc.a" "-mconsole" "-lkernel32" "-luser32" "-lgdi32" "-lwinspool" "-lshell32" "-lole32" "-loleaut32" "-luuid" "-lcomdlg32" "-ladvapi32" "-Wl,--end-group"

PS: May also apply to libswscale.a and libpostproc.a (near the end of the quote above)?

**Comment by wiiaboo** [comment] 2019-09-27 22:48
Duplicate of #1408

**Closed by wiiaboo** 2019-09-27 22:48 UTC
Labels: bug
