### ISSUE TITLE
Failure to build

### ISSUE THREAD

**Issue by jonathancolledge** [m-ab-s/media-autobuild_suite#2329] opened 2022-11-20 12:17 UTC
Can you help please? I redid this with even fewer options and it didn't work the second time. I

Building 64-bit (though it says 32 bit compilation tools below, but I chose 64 bit. 
Attempt 1
[logs.zip](https://0x0.st/ole4.zip)

Attempt 2
[logs.zip](https://0x0.st/ol2m.zip) 

The output is here:

        Warning: We will not accept any issues lacking any form of logs or logs.zip!

        Starting 32bit compilation of all tools
Imported options from ffmpeg_options.txt
License: nonfree
Imported options from mpv_options.txt

        Starting 32bit compilation of global tools
├ Running download_rustup...
├ Running install_rust...
├ Stripping...
└ rustinstall  ................................................. [Updated]
├ Running rustup_update...
├ Running set_default_toolchain...
  Running git clone for libxml2...
  Running git update for libxml2...
┌ libxml2 git  ........................................ [Recently updated]
├ Running autogen...
├ Running configure...
├ Running make...
├ Running install...
├ Stripping...
└ libxml2-git  ................................................. [Updated]
  Running git clone for libpng...
  Running git update for libpng...
┌ libpng git  ......................................... [Recently updated]
├ Running autoupdate...
├ Running configure...
├ Running make...
├ Running install...
├ Stripping...
└ libpng-git  .................................................. [Updated]
  Running git clone for aribb24...
  Running git update for aribb24...
┌ aribb24 git  ........................................ [Recently updated]
├ Running autoreconf...
├ Running configure...
├ Running make...
├ Running install...
├ Stripping...
└ aribb24-git  ................................................. [Updated]
  Running git clone for freetype...
  Running git update for freetype...
┌ freetype git  ....................................... [Recently updated]
├ Running meson...
├ Running build...
├ Running install...
├ Stripping...
└ freetype-git  ................................................ [Updated]
  Running git clone for fontconfig...
  Running git update for fontconfig...
┌ fontconfig git  ........................................ [Updates found]
├ Running autogen...
├ Running autoreconf...
├ Running configure...
├ Running make...
├ Running install...
├ Stripping...
└ fontconfig-git  .............................................. [Updated]
  Running git clone for harfbuzz...
  Running git update for harfbuzz...
┌ harfbuzz git  ....................................... [Recently updated]
├ Installing ragel... done
├ Installing icu... done
├ Running meson...
├ Running build...
├ Running install...
├ Stripping...
└ harfbuzz-git  ................................................ [Updated]
  Running git clone for fribidi...
  Running git update for fribidi...
┌ fribidi git  ........................................ [Recently updated]
├ Running meson...
├ Running build...
├ Running install...
├ Stripping...
└ fribidi-git  ................................................. [Updated]
  Running git clone for libass...
  Running git update for libass...
┌ libass git  ......................................... [Recently updated]
├ Running autoreconf...
├ Running configure...
├ Running make...
├ Running install...
├ Stripping...
└ libass-git  .................................................. [Updated]
gnutls 3.7.8  ............................................ [Not installed]
┌ gnutls-3.7.8  ............................................. [Downloaded]
├ Running extract...
├ Installing nettle... done
├ Running configure...
├ Running make...
├ Running install...
├ Stripping...
└ gnutls-3.7.8  ................................................ [Updated]
├ Installing openssl... done
├ Installing libunistring... done
libidn2 2.3.0  ........................................... [Not installed]
┌ libidn2-2.3.0  ............................................ [Downloaded]
├ Running extract...
├ Running configure...
├ Running make...
├ Running install...
├ Stripping...
└ libidn2-2.3.0  ............................................... [Updated]
libpsl 0.21.0  ........................................... [Not installed]
┌ libpsl-0.21.0  ............................................ [Downloaded]
├ Running extract...
├ Running configure...
├ Running make...
├ Running install...
├ Stripping...
└ libpsl-0.21.0  ............................................... [Updated]
├ Installing brotli... done
  Running git clone for curl...
  Running git update for curl...
┌ curl git  ........................................... [Recently updated]
├ Installing nghttp2... done
├ Running autoreconf...
├ Running configure...
├ Running make...
├ Running install...
├ Running ca-bundle...
├ Stripping...
└ curl-git  .................................................... [Updated]
  Running git clone for freeglut...
  Running git update for freeglut...
┌ freeglut git  ....................................... [Recently updated]
├ Running cmake...
├ Running build...
├ Running install...
├ Stripping...
└ freeglut-git  ................................................ [Updated]
  Running git clone for libtiff...
  Running git update for libtiff...
┌ libtiff git  ........................................ [Recently updated]
├ Installing libjpeg-turbo... done
├ Installing xz... done
├ Installing zlib... done
├ Installing zstd... done
├ Installing libdeflate... done
├ Running cmake...
├ Running build...
Likely error (tail of the failed operation logfile):
I:/media-autobuild_suite-master/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: I:/media-autobuild_suite-master/local32/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x2077): undefined reference to `_imp__glVertexPointer@16'
I:/media-autobuild_suite-master/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: I:/media-autobuild_suite-master/local32/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x2097): undefined reference to `_imp__glNormalPointer@12'
I:/media-autobuild_suite-master/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: I:/media-autobuild_suite-master/local32/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x20d3): undefined reference to `_imp__glTexCoordPointer@16'
I:/media-autobuild_suite-master/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: I:/media-autobuild_suite-master/local32/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x2126): undefined reference to `_imp__glDrawElements@16'
I:/media-autobuild_suite-master/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: I:/media-autobuild_suite-master/local32/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x2139): undefined reference to `_imp__glDisableClientState@4'
I:/media-autobuild_suite-master/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: I:/media-autobuild_suite-master/local32/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x21dd): undefined reference to `_imp__glDrawElements@16'
I:/media-autobuild_suite-master/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: I:/media-autobuild_suite-master/local32/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x2209): undefined reference to `_imp__glDrawArrays@12'
I:/media-autobuild_suite-master/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: I:/media-autobuild_suite-master/local32/lib/libglut.a(fg_ext_mswin.c.obj):fg_ext_mswin.c:(.text+0xfc): undefined reference to `_imp__wglGetProcAddress@4'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check I:/media-autobuild_suite-master/build/libtiff-git/build-32bit/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/ole4.zip
Copy and paste [logs.zip](https://0x0.st/ole4.zip) in the GitHub issue.
Make sure the suite is up-to-date  
-it is

**Comment by 1480c1** [comment] 2022-11-20 18:11
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2328

**Closed by 1480c1** 2022-11-20 18:11 UTC
