### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by dan1013** [m-ab-s/media-autobuild_suite#1925] opened 2021-02-26 21:49 UTC
[logs.zip](https://0x0.st/-KQ2.zip)

**Comment by 1480c1** [comment] 2021-02-26 22:12
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/1919 and https://github.com/m-ab-s/media-autobuild_suite/issues/1924

**Closed by 1480c1** 2021-02-26 22:12 UTC
