### ISSUE TITLE
mingw64 libweb build error - no such file or directory

### ISSUE THREAD

**Issue by ASopH** [m-ab-s/media-autobuild_suite#1990] opened 2021-06-06 10:26 UTC
Hi!
I get this error for a long time. After a clean install the error occours again!

12:03:54 ┌ libwebp git  .............................. [Recently updated]
12:03:58 ├ Running cmake...
12:04:11 ├ Running build...
Likely error (tail of the failed operation logfile):
[11/31] Building C object CMakeFiles/webpdsp.dir/src/dsp/alpha_processing_sse41.c.o
[12/31] Building C object CMakeFiles/webpdsp.dir/src/dsp/lossless_sse41.c.o
[13/31] Building C object CMakeFiles/webpmux.dir/examples/webpmux.c.o
FAILED: CMakeFiles/webpmux.dir/examples/webpmux.c.o
F:\m-a-s\msys64\mingw64\bin\ccache.exe  gcc -DHAVE_CONFIG_H -DUNICODE -DWEBP_SWAP_16BIT_CSP=1 -D_UNICODE -IF:/m-a-s/msys64/mingw64/include/libpng16 -Isrc -mthreads -mtune=generic -O2 -pipe -DFREEGLUT_STATIC -pthread -O3 -DNDEBUG   -Wall -MD -MT CMakeFiles/webpmux.dir/examples/webpmux.c.o -MF CMakeFiles\webpmux.dir\examples\webpmux.c.o.d -o CMakeFiles/webpmux.dir/examples/webpmux.c.o -c ../examples/webpmux.c
../examples/webpmux.c:62:10: fatal error: webp/decode.h: No such file or directory
   62 | #include "webp/decode.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
build failed. Check F:/m-a-s/build/libwebp-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
12:04:22   Creating diagnostics file...

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6604011/logs.zip)

**Comment by ggarra13** [comment] 2021-06-07 23:13
Same here.  The do_pacman_install giflib did not fix the includes problem.

**Comment by 1480c1** [comment] 2021-06-08 16:03
I push a new commit, can you test that?

**Comment by ASopH** [comment] 2021-06-08 16:31
Hi, fails again, 

after deleting .build\libwebp-git:

18:25:25 freeglut git  ..................................... [Up-to-date]
18:25:29   Running git update for libtiff...
18:25:30 libtiff git  ...................................... [Up-to-date]
18:25:30   Running git clone for libwebp...
18:25:36 ┌ libwebp git  .............................. [Recently updated]
18:25:40 ├ Running cmake...
18:25:53 ├ Running build...
Likely error (tail of the failed operation logfile):
ninja: build stopped: subcommand failed.
[1/25] Building C object CMakeFiles/webpinfo.dir/examples/webpinfo.c.o
FAILED: CMakeFiles/webpinfo.dir/examples/webpinfo.c.o
F:\m-a-s\msys64\mingw64\bin\ccache.exe  gcc -DHAVE_CONFIG_H -DUNICODE -DWEBP_SWAP_16BIT_CSP=1 -D_UNICODE -IF:/m-a-s/msys64/mingw64/include/libpng16 -Isrc -mthreads -mtune=generic -O2 -pipe -DFREEGLUT_STATIC -pthread -O3 -DNDEBUG   -Wall -MD -MT CMakeFiles/webpinfo.dir/examples/webpinfo.c.o -MF CMakeFiles\webpinfo.dir\examples\webpinfo.c.o.d -o CMakeFiles/webpinfo.dir/examples/webpinfo.c.o -c ../examples/webpinfo.c
In file included from ../examples/webpinfo.c:22:
../examples/../imageio/imageio_util.h:17:10: fatal error: webp/types.h: No such file or directory
   17 | #include "webp/types.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
build failed. Check F:/m-a-s/build/libwebp-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6618209/logs.zip)

**Comment by 1480c1** [comment] 2021-06-08 16:48
pushed another commit

**Comment by ASopH** [comment] 2021-06-08 17:12
... fails again - after deleting .build\libwebp-git:

19:07:05   Running git clone for libwebp...
19:07:11 ┌ libwebp git  .............................. [Recently updated]
19:07:15 ├ Running cmake...
19:07:28 ├ Running build...
Likely error (tail of the failed operation logfile):
[113/115] Linking C static library libwebp.a
ninja: build stopped: subcommand failed.
[1/3] Linking C executable webpmux.exe
FAILED: webpmux.exe
cmd.exe /C "cd . && F:\m-a-s\msys64\mingw64\bin\ccache.exe  gcc -mthreads -mtune=generic -O2 -pipe -DFREEGLUT_STATIC -pthread -O3 -DNDEBUG -pipe -static-libgcc -static-libstdc++ CMakeFiles/webpmux.dir/examples/webpmux.c.o -o webpmux.exe -Wl,--out-implib,libwebpmux.dll.a -Wl,--major-image-version,0,--minor-image-version,0  -lexampleutil  -limageioutil  -llibwebpmux  libwebp.a  -lshlwapi  -lole32  -lwindowscodecs  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
F:/m-a-s/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lexampleutil
F:/m-a-s/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -limageioutil
F:/m-a-s/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -llibwebpmux
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check F:/m-a-s/build/libwebp-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
19:07:38   Creating diagnostics file...

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6618444/logs.zip)

**Comment by ggarra13** [comment] 2021-06-08 22:31
Same error here.

**Comment by 1480c1** [comment] 2021-06-10 16:42
Going to close as duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/1985 since it still seems to be related to moving over to cmake

**Closed by 1480c1** 2021-06-10 16:42 UTC

**Comment by ggarra13** [comment] 2021-06-10 21:13
I still have this problem as 10th June 2021.  It keeps compiling with cmake if that's any indication.
[logs.zip](https://0x0.st/-LbQ.zip)
