### ISSUE TITLE
Error running make when running git update for ffmpeg - [/build/ffmpeg-git/ffbuild/common.mak:81: libavutil/hwcontext_vulkan.o] Error 1

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#2348] opened 2022-12-23 16:28 UTC
21:03:13 └ libplacebo-git  .................................... [Updated]
21:03:50   Running git update for ffmpeg...
21:04:49 ┌ ffmpeg git  .................................. [Updates found]
21:04:49 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
        Patch could not be applied with `git am`. Continuing without patching.
21:04:57 ├ Compiling static FFmpeg...
21:04:58 ├ Running uninstall...
21:04:58 ├ Running configure...
21:10:09 ├ Running make...
Likely error (tail of the failed operation logfile):
CC      libavutil/hwcontext_vulkan.o
src/libavutil/hwcontext_vulkan.c:367:7: error: 'VK_EXT_VIDEO_DECODE_H264_EXTENSION_NAME' undeclared here (not in a function); did you mean 'VK_EXT_VIDEO_ENCODE_H264_EXTENSION_NAME'?
  367 |     { VK_EXT_VIDEO_DECODE_H264_EXTENSION_NAME,                FF_VK_EXT_NO_FLAG                },
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       VK_EXT_VIDEO_ENCODE_H264_EXTENSION_NAME
src/libavutil/hwcontext_vulkan.c:368:7: error: 'VK_EXT_VIDEO_DECODE_H265_EXTENSION_NAME' undeclared here (not in a function); did you mean 'VK_EXT_VIDEO_ENCODE_H265_EXTENSION_NAME'?
  368 |     { VK_EXT_VIDEO_DECODE_H265_EXTENSION_NAME,                FF_VK_EXT_NO_FLAG                },
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       VK_EXT_VIDEO_ENCODE_H265_EXTENSION_NAME
make: *** [/build/ffmpeg-git/ffbuild/common.mak:81: libavutil/hwcontext_vulkan.o] Error 1
make failed. Check C:/MinGW-w64/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
21:16:15   Creating diagnostics file...

Attach C:\MinGW-w64\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/10296157/logs.zip
[ab-suite.make.log](https://github.com/m-ab-s/media-autobuild_suite/files/10296173/ab-suite.make.log)

**Comment by Biswa96** [comment] 2022-12-23 16:49
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2345

There is a temporary workaround at last of that thread.

**Comment by 1480c1** [comment] 2022-12-26 22:23
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2345

**Closed by 1480c1** 2022-12-26 22:23 UTC
