### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Doofussy2** [m-ab-s/media-autobuild_suite#2038] opened 2021-09-07 00:40 UTC
I ran my build without any changes from the previous successful build, but received a compilation error for ffmpeg, this time. I updated the package and ran it again. I have the same error.

This was printed out after compilation failure
```
┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to gplv3...
├ Compiling static FFmpeg...
├ Running configure...
Likely error (tail of the failed operation logfile):
CPPFLAGS: -D_FORTIFY_SOURCE=0 -D__USE_MINGW_ANSI_STDIO=1
CFLAGS: -mthreads -mtune=generic -O2 -pipe
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config=pkgconf --pkg-config-flags=--keep-system-libs --keep-system-cflags --static --cc=ccache gcc --cxx=ccache g++ --ld=ccache g++ --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libaom --disable-debug --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libopenmpt --enable-version2 --enable-librav1e --enable-libsrt --enable-libgsm --enable-libvmaf --enable-libsvtav1 --enable-chromaprint --enable-frei0r --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfribidi --enable-libgme --enable-libilbc --enable-libsvthevc --enable-libsvtvp9 --enable-libkvazaar --enable-libmodplug --enable-librtmp --enable-librubberband --enable-libtesseract --enable-libxavs --enable-libzmq --enable-libzvbi --enable-openal --enable-libcodec2 --enable-ladspa --enable-libglslang --enable-vulkan --enable-libdavs2 --enable-libxavs2 --enable-libuavs3d --enable-opencl --enable-opengl --enable-libopenh264 --enable-mbedtls --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --enable-version3 --extra-cflags=-DAL_LIBTYPE_STATIC --extra-cflags=-IG:/mpv_building_tools/local64/include --extra-cflags=-IG:/mpv_building_tools/local64/include/AL --extra-version=gb9426f371a+3
Unknown option "--enable-version2".
```

 [logs.zip](https://0x0.st/-w_X.zip)

**Comment by 1480c1** [comment] 2021-09-07 00:50
It seems you might have messed around with ffmpeg_options.txt since it should be `--enable-version3` and not `--enable-version2`, nothing in the suite writes `version2`

**Comment by Doofussy2** [comment] 2021-09-07 00:52
Ah, ok, I don't recall changing anything with that, but I will update it to version 3, and run it again. Thank you.

**Comment by Doofussy2** [comment] 2021-09-07 01:17
Well, that got me further (thank you), but now I have a new error.

```
  Running git update for mpv...
┌ mpv git  ............................................... [Updates found]
├ Running bootstrap...
├ Running configure...
├ Running build...
Likely error (tail of the failed operation logfile):
      |     ^~~~~~~~~~~~~~
In file included from G:/mpv_building_tools/local64/include/libavcodec/avcodec.h:45,
                 from ../demux/packet.c:23:
G:/mpv_building_tools/local64/include/libavcodec/packet.h:503:6: note: declared here
  503 | void av_init_packet(AVPacket *pkt);
      |      ^~~~~~~~~~~~~~

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'objects' failed with exit status 1 (run with -v to display more information)
```

[logs.zip](https://0x0.st/-w__.zip)

**Comment by 1480c1** [comment] 2021-09-07 13:04
Last error is a duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2033

try adding `--enable-ffmpeg-strict-abi` to `mpv_options.txt`

**Comment by Doofussy2** [comment] 2021-09-07 18:49
Yup, I haven't tested it yet, but it looks like that will be defaulted in the future.

https://github.com/mpv-player/mpv/pull/9195

**Comment by Doofussy2** [comment] 2021-09-09 03:47
Adding that option results in an error. 
[logs.zip](https://0x0.st/-wlj.zip)

```
Likely error (tail of the failed operation logfile):
                        disable macOS 10.11 SDK Features [autodetect]
    --disable-macos-10-12-2-features
                        disable macOS 10.12.2 SDK Features [autodetect]
    --disable-macos-10-14-features
                        disable macOS 10.14 SDK Features [autodetect]
    --disable-macos-media-player
                        disable macOS Media Player support [autodetect]
    --disable-macos-cocoa-cb
                        disable macOS libmpv backend [autodetect]
waf: error: no such option: --enable-ffmpeg-strict-abi
configure failed. Check G:/mpv_building_tools/build/mpv-git/ab-suite.configure.log
This is required for other packages, so this script will exit.
```

As this has been updated in mpv, I'm going to remove the option and run it again.

**Comment by Doofussy2** [comment] 2021-09-09 03:58
>As this has been updated in mpv, I'm going to remove the option and run it again.

And we have a successful build.

**Closed** 2021-09-09 03:58 UTC
