### ISSUE TITLE
chromaprint not found

### ISSUE THREAD

**Issue by martininguyen** [m-ab-s/media-autobuild_suite#1686] opened 2020-05-30 04:08 UTC
Currently trying to compile ffmpeg, it worked a few days ago, but now I'm getting this chromaprint error

ERROR: chromaprint not found

[if9t.zip](https://github.com/m-ab-s/media-autobuild_suite/files/4705073/if9t.zip)

**Comment by 1480c1** [comment] 2020-05-30 04:35
Duplicate of #1684

**Closed by 1480c1** 2020-05-30 04:35 UTC
