### ISSUE TITLE
[SVT-HEVC / SVT-VP9] Patch could not be applied with `git am`

### ISSUE THREAD

**Issue by OliverMD15** [m-ab-s/media-autobuild_suite#2152] opened 2022-03-25 02:00 UTC
```
01:45:56 ┌ ffmpeg git  ............................... [Recently updated]
01:45:56 ├ Changing options to comply to nonfree...
FFmpeg and related apps will depend on CUDA SDK to run!
master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
        Patch could not be applied with `git am`. Continuing without patching.
master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
        Patch could not be applied with `git am`. Continuing without patching.
01:46:03 ├ Compiling static FFmpeg...
```

**Comment by 1480c1** [comment] 2022-03-25 18:24
for hevc https://github.com/OpenVisualCloud/SVT-HEVC/pull/615

**Comment by OliverMD15** [comment] 2022-04-06 01:07
SVT-HEVC seems to work, but SVT-VP9 is still a bust. Any update on this?
```
03:04:25 ┌ ffmpeg git  .................................. [Updates found]
03:04:25 ├ Changing options to comply to nonfree...
FFmpeg and related apps will depend on CUDA SDK to run!
master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
        Patch could not be applied with `git am`. Continuing without patching.
03:04:30 ├ Compiling static FFmpeg...
```

**Comment by BedrockDotPng** [comment] 2022-04-07 11:09
Same in my case.

![image](https://user-images.githubusercontent.com/74654571/162185872-be9c2780-add7-482a-8f3f-da6491fa9c77.png)

**Comment by 1480c1** [comment] 2022-04-16 01:36
For svt-vp9 https://github.com/OpenVisualCloud/SVT-VP9/issues/156 seems there are some other issues even if the patch is rebased, I will remove the patch for now

**Comment by 1480c1** [comment] 2022-04-20 17:16
duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2148

**Closed by 1480c1** 2022-04-20 17:16 UTC
