### ISSUE TITLE
installing pacman (5.2.1-12) breaks dependency 'pacman-contrib' required by base

### ISSUE THREAD

**Issue by ImportTaste** [m-ab-s/media-autobuild_suite#1703] opened 2020-06-09 14:26 UTC
I'm not sure how this happened, it probably isn't media-autobuild_suite's fault, but I might require assistance to fix it since I don't know if this being fixed upstream will necessarily mean it will fix my environment. I started getting this yesterday when the suite tried to upgrade the core system:

```
Starting core system upgrade...
warning: terminate other MSYS2 programs before proceeding
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing pacman (5.2.1-12) breaks dependency 'pacman-contrib' required by base
-------------------------------------------------------------------------------
Updates finished.
-------------------------------------------------------------------------------
```

**Comment by 1480c1** [comment] 2020-06-09 15:43
Duplicate of #1701

**Comment by 1480c1** [comment] 2020-06-09 15:43
From what I could tell, best way is to delete msys64 and rerun

**Closed by 1480c1** 2020-06-09 15:43 UTC

**Comment by ImportTaste** [comment] 2020-06-09 15:56
You know, I actually checked the issues to see if anyone else had reported it, and somehow my eyes didn't register that one. Guess I need another coffee. Sorry about that.

**Comment by 1480c1** [comment] 2020-06-09 15:57
Haha, happens to some people
