### ISSUE TITLE
Building of ffmpeg not working

### ISSUE THREAD

**Issue by BlackScreen** [m-ab-s/media-autobuild_suite#1498] opened 2019-12-06 11:57 UTC
```
12:43:40   Running git update for ffmpeg...
12:43:43 ┌ ffmpeg git  .................................. [Updates found]
12:43:43 ├ Until SVT-AV1 issues a fix, libsvtav1 must be disabled while libsvthevc is enabled....
12:43:43 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
patch unexpectedly ends in middle of line
12:43:50 ├ Compiling static FFmpeg...
12:43:53 ├ Running configure...
12:48:46 ├ Running make...
Likely error (tail of the failed operation logfile):
make: *** [/build/ffmpeg-git/Makefile:114: ffprobe_g.exe] Error 1
C:/Development/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Development/MABS/local64/lib/librav1e.a(compiler_builtins-477d6ada7584f678.compiler_builtins.1c0g4lf3-cgu.0.rcgu.o): in function `___chkstk_ms':
C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\compiler_builtins-0.1.18\src/x86_64.rs:15: multiple definition of `___chkstk_ms'; C:/Development/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/libgcc.a(_chkstk_ms.o):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:114: ffplay_g.exe] Error 1
LD      ffmpeg_g.exe
C:/Development/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Development/MABS/local64/lib/librav1e.a(compiler_builtins-477d6ada7584f678.compiler_builtins.1c0g4lf3-cgu.0.rcgu.o): in function `___chkstk_ms':
C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\compiler_builtins-0.1.18\src/x86_64.rs:15: multiple definition of `___chkstk_ms'; C:/Development/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/libgcc.a(_chkstk_ms.o):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:114: ffmpeg_g.exe] Error 1
make failed. Check C:/Development/MABS/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
12:53:16   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zlDa.zip
Copy and paste [logs.zip](https://0x0.st/zlDa.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

**Comment by 1480c1** [comment] 2019-12-06 16:20
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/1483

**Closed by 1480c1** 2019-12-06 16:20 UTC
