### ISSUE TITLE
Error "/local64/lib/libapputils.a ...................... [Not found]" when running git update for vvenc

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#2290] opened 2022-09-25 07:26 UTC
14:43:30   Running git update for vvenc...
14:43:40 ┌ vvenc git  ................................... [Updates found]
14:43:41 ├ Running uninstall...
14:43:41 ├ Running cmake...
14:43:43 ├ Running build...
14:46:24 ├ Running install...
14:46:25 ├ /local64/lib/libapputils.a  ...................... [Not found]
14:46:25 └ vvenc-git  .......................................... [Failed]

Try deleting '/build/vvenc-git' and start the script again.
If you are sure there are no dependencies, <Enter> to continue building.
Close this window if you wish to stop building.

After deleting '/build/vvenc-git', the issue  '/local64/lib/libapputils.a  ...................... [Not found]' is still there

15:18:49   Running git clone for vvenc...
15:18:55   Running git update for vvenc...
15:18:55 ┌ vvenc git  ................................ [Recently updated]
15:18:55 ├ Running uninstall...
15:18:55 ├ Running cmake...
15:18:58 ├ Running build...
15:19:05 ├ Running install...
15:19:06 ├ /local64/lib/libapputils.a  ...................... [Not found]
15:19:06 └ vvenc-git  .......................................... [Failed]

Try deleting '/build/vvenc-git' and start the script again.
If you are sure there are no dependencies, <Enter> to continue building.
Close this window if you wish to stop building.

**Comment by Biswa96** [comment] 2022-09-25 07:29
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2289

**Comment by 1480c1** [comment] 2022-09-25 15:09
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2289

**Closed by 1480c1** 2022-09-25 15:09 UTC
