### ISSUE TITLE
[mingw64] [repo] FFmpeg compile failure with glslang enabled

### ISSUE THREAD

**Issue by Asphxiated** [m-ab-s/media-autobuild_suite#1753] opened 2020-07-16 05:56 UTC
I had this issue last time but I saw that there was a recent update that supposedly removed an unnecessary patch from glslang so I hoped that this addressed the issue but it doesn't. FFmpeg will compile if I disable glslang but why is it failing?

``` vulkan-loader git  ....................................... [Already built]
glslang git  ............................................. [Already built]
  Running git update for ffmpeg...
┌ ffmpeg git  ............................................ [Updates found]
├ Changing options to comply to nonfree...
├ Compiling static FFmpeg...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/libSPIRV.a(GlslangToSpv.cpp.obj):GlslangToSpv.cpp:(.text$_ZN7glslang5TType12setFieldNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcENS_14pool_allocatorIcEEEE[_ZN7glslang5TType12setFieldNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcENS_14pool_allocatorIcEEEE]+0x2a): undefined reference to `glslang::GetThreadPoolAllocator()'
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/libSPIRV.a(GlslangToSpv.cpp.obj):GlslangToSpv.cpp:(.text$_ZN7glslang5TType12setFieldNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcENS_14pool_allocatorIcEEEE[_ZN7glslang5TType12setFieldNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcENS_14pool_allocatorIcEEEE]+0x98): undefined reference to `glslang::TPoolAllocator::allocate(unsigned long long)'
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/libSPIRV.a(GlslangToSpv.cpp.obj):GlslangToSpv.cpp:(.text$_ZN7glslang5TTypeC1ERKS0_ib[_ZN7glslang5TTypeC1ERKS0_ib]+0x210): undefined reference to `glslang::GetThreadPoolAllocator()'
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/libSPIRV.a(GlslangToSpv.cpp.obj):GlslangToSpv.cpp:(.text$_ZN7glslang5TTypeC1ERKS0_ib[_ZN7glslang5TTypeC1ERKS0_ib]+0x21d): undefined reference to `glslang::TPoolAllocator::allocate(unsigned long long)'
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/libSPIRV.a(GlslangToSpv.cpp.obj):GlslangToSpv.cpp:(.text$_ZN7glslang5TTypeC1ERKS0_ib[_ZN7glslang5TTypeC1ERKS0_ib]+0x26c): undefined reference to `glslang::GetThreadPoolAllocator()'
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/libSPIRV.a(GlslangToSpv.cpp.obj):GlslangToSpv.cpp:(.text$_ZN7glslang5TTypeC1ERKS0_ib[_ZN7glslang5TTypeC1ERKS0_ib]+0x279): undefined reference to `glslang::TPoolAllocator::allocate(unsigned long long)'
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/libSPIRV.a(GlslangToSpv.cpp.obj):GlslangToSpv.cpp:(.text$_ZN7glslang5TTypeC1ERKS0_ib[_ZN7glslang5TTypeC1ERKS0_ib]+0x281): undefined reference to `glslang::GetThreadPoolAllocator()'
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/libSPIRV.a(GlslangToSpv.cpp.obj):GlslangToSpv.cpp:(.text$_ZN7glslang5TTypeC1ERKS0_ib[_ZN7glslang5TTypeC1ERKS0_ib]+0x2dd): undefined reference to `glslang::TPoolAllocator::allocate(unsigned long long)'
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:114: ffmpeg_g.exe] Error 1
make failed. Check C:/mabs/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.

```

[logs.zip](https://0x0.st/ivaf.zip)

**Comment by LigH-de** [comment] 2020-07-16 08:07
#1734 looks very similar.

**Comment by 1480c1** [comment] 2020-07-16 13:35
Duplicate of #1734

**Closed by 1480c1** 2020-07-16 13:35 UTC
