### ISSUE TITLE
how to specify  local ffmpeg dir to build

### ISSUE THREAD

**Issue by liudongbo** [m-ab-s/media-autobuild_suite#2055] opened 2021-09-27 03:41 UTC
update my file locally, how do I rebuild it when i try the autobuild suite, it does a git checkout and my changes are over written

**Comment by 1480c1** [comment] 2021-09-27 05:55
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2039

**Closed by 1480c1** 2021-09-27 05:55 UTC
