### ISSUE TITLE
Error running git update for libwebp

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#2125] opened 2022-02-17 08:01 UTC
15:34:35   Running git update for libwebp...
15:34:57 ┌ libwebp git  ................................. [Updates found]
15:35:07 ├ Running uninstall...
15:35:07 ├ Running cmake...
15:35:26 ├ Running build...
Likely error (tail of the failed operation logfile):
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/msys64/mingw64/lib/libtiff.a(tif_lzma.o):tif_lzma.c:(.text+0x54e): undefined reference to `lzma_stream_encoder'
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/msys64/mingw64/lib/libtiff.a(tif_lzma.o):tif_lzma.c:(.text+0x5f1): undefined reference to `lzma_lzma_preset'
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/msys64/mingw64/lib/libtiff.a(tif_lzma.o):tif_lzma.c:(.text+0x626): undefined reference to `lzma_stream_encoder'
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/msys64/mingw64/lib/libtiff.a(tif_lzma.o):tif_lzma.c:(.text+0x706): undefined reference to `lzma_code'
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/msys64/mingw64/lib/libtiff.a(tif_lzma.o):tif_lzma.c:(.text+0x718): undefined reference to `lzma_memusage'
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/msys64/mingw64/lib/libtiff.a(tif_lzma.o):tif_lzma.c:(.text+0x726): undefined reference to `lzma_stream_decoder'
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/msys64/mingw64/lib/libtiff.a(tif_lzma.o):tif_lzma.c:(.text+0x8ca): undefined reference to `lzma_stream_decoder'
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/msys64/mingw64/lib/libtiff.a(tif_lzma.o):tif_lzma.c:(.text+0xace): undefined reference to `lzma_lzma_preset'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check C:/MinGW-w64/build/libwebp-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
15:36:08   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/o8p-.zip
Copy and paste [logs.zip](https://0x0.st/o8p-.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

[logs.zip](https://0x0.st/o8p-.zip)
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/8086663/ab-suite.build.log)

**Comment by 1480c1** [comment] 2022-02-17 18:03
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2122

**Closed by 1480c1** 2022-02-17 18:03 UTC
