### ISSUE TITLE
install-rav1e-c failed

### ISSUE THREAD

**Issue by F1EJP** [m-ab-s/media-autobuild_suite#2682] opened 2024-05-14 22:08 UTC
building  64-bit 
error: could not compile `rav1e` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
Error: CliError { error: Some(1 job failed), exit_code: 101 }
[31minstall-rav1e-c failed. Check C:/media-autobuild_suite-master/build/rav1e-git/ab-suite.install-rav1e-c.log(B[m

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/15314206/logs.zip)

Thank you for your analyse, i have not see this in issue.

**Comment by LigH-de** [comment] 2024-05-15 05:56
Kind of duplicate of #2670 which got closed prematurely.

**Comment by LigH-de** [comment] 2024-05-15 19:10
A workaround, if not even a solution:

**media-suite_compile.sh** line 1147:
```diff
         PKG_CONFIG="$LOCALDESTDIR/bin/ab-pkg-config-static.bat" \
             CC="ccache clang" \
             CXX="ccache clang++" \
             log "install-rav1e-c" cargo capi install \
-            --release --jobs "$cpuCount" --prefix="$LOCALDESTDIR" \
+            --release --no-default-features --jobs "$cpuCount" --prefix="$LOCALDESTDIR" \
             --destdir="$PWD/install-$bits"
```

**Comment by 1480c1** [comment] 2024-05-17 02:46
I believe this has been fixed

**Comment by LigH-de** [comment] 2024-05-18 13:43
Unfortunately not, I still have to add `--no-default-features` until git2 gets substituted upstream (by e.g. gix).

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/15365254/logs.zip)

**Comment by 1480c1** [comment] 2024-05-20 13:01
> Unfortunately not, I still have to add `--no-default-features` until git2 gets substituted upstream (by e.g. gix).
> 
> [logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/15365254/logs.zip)

I ran a clean build using the config files in your zip file and it succeeded. I am running it again to make sure

**Comment by 1480c1** [comment] 2024-05-20 14:37
Ran it again and had no issues compiling

**Comment by LigH-de** [comment] 2024-05-20 15:20
So what's wrong in my setup?

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/15378717/logs.zip)

**Comment by 1480c1** [comment] 2024-05-20 15:32
can you try cleaning up `/opt/cargo/bin`? It's possible that there's some stuff left over from there during the transition to using msys2's rust packages

**Comment by 1480c1** [comment] 2024-05-20 16:01
you should be able to prune all of `/opt/cargo` safely as far as I know, it should only hold  `registry` and a few other files. Pretty much everything under `bin` was migrated to using msys2's packages

**Comment by LigH-de** [comment] 2024-05-20 16:37
Nope, same linker error.

I assume that ld would look for a file **libgit2.a** due to the parameter `-lgit2` ?

The only location where this file exists on my PC is
`G:\MABS\build\rav1e-git\target\release-no-lto\build\libgit2-sys-afacc7b5410267df\out\build\libgit2.a`

**Comment by 1480c1** [comment] 2024-05-20 18:22
hmm, would you be able to zip up `msys64`, `local*` and send them to me? Via email is fine

**Comment by LigH-de** [comment] 2024-05-20 18:29
Uhm, no, msys64 alone is 15 GB uncompressed, you won't get that through any email server. Or did I misunderstand you, did you only want the names of existing files?

**Comment by 1480c1** [comment] 2024-05-20 18:39
Darn, I wanted to see if I could trace what's different from my setup and yours. I thought it was fixed by way of hiding the .pc file, which it would check to see if it could use the system's libgit2. 

I'm going to go the route of building our own libgit2 since that seems to be the least hassle at this time.

**Comment by LigH-de** [comment] 2024-05-20 19:37
As I said, there is no libgit2 library file in the system. Except for crate and rlib files which must belong to rust exclusively, and the [above mentioned libgit2.a file](#issuecomment-2120806665) which was built but not copied to local libs, there are only these files in the MSYS2 system:

`G:\MABS\msys64\mingw32\bin\libgit2-1.7.dll`
`G:\MABS\msys64\mingw64\bin\libgit2-1.7.dll`

**Comment by LigH-de** [comment] 2024-05-21 12:18
Additional note: A rav1e.exe has been created in local32/bin-video; but its size is >50 MB. A previous build in local64/bin-video is just ~5 MB. So what actually fails may not be the building but the stripping, using ld? Confusing to me.

**Comment by ASopH** [comment] 2024-05-21 13:59
Hi,
same here: 32bit .exe is >50 MB, but an older 64 bit .exe is >63 MB
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/15390848/logs.zip)

hope the logs help a little bit :-)

**Comment by LigH-de** [comment] 2024-05-21 14:07
That last 64 bit exe in my suite was compiled with that `--no-default-features` option.

From Feb. 2024: 32 bit ~4 MB, 64 bit ~5 MB.

**Comment by ASopH** [comment] 2024-05-21 14:12
Hi LigH,
I've started yesterday a new, clean run without "--no-default-features" - after a new start ist breaks at 32bit compile...

**Comment by LigH-de** [comment] 2024-05-21 14:14
OK, the fact that it works for a 1st time is certainly interesting...

**Comment by ASopH** [comment] 2024-05-21 14:30
Ok, a new try: deleted local* dirs and started again .. must wait :-)

**Comment by ASopH** [comment] 2024-05-21 17:09
So, compiling ended - with error:
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/15393101/logs.zip)
perhaps something in MSYS ?? - no clue

**Comment by LigH-de** [comment] 2024-05-27 12:39
For me, rav1e builds without additional changes now. Probably thanks to https://github.com/m-ab-s/media-autobuild_suite/commit/5f6a79487106d57320a1cf72a9347a628d06f17f

**Comment by ASopH** [comment] 2024-05-27 12:40
ok, seems to work

**Comment by F1EJP** [comment] 2024-05-27 16:22
it's seem ok for me now

**Comment by F1EJP** [comment] 2024-05-27 17:43
thanks for all i close

**Closed** 2024-05-27 17:42 UTC
