### ISSUE TITLE
[x64] FFmpeg / "master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch" could not be applied

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2778] opened 2024-10-14 16:42 UTC
┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Compiling static FFmpeg...
├ Running uninstall...
├ Running configure...

FFmpeg compiles just fine. Just wanted to give a heads up about this

**Comment by LigH-de** [comment] 2024-10-18 22:12
I reported the failure several months ago in #2727

**Comment by 1480c1** [comment] 2024-10-18 22:14
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2727

**Closed by 1480c1** 2024-10-18 22:14 UTC
