### ISSUE TITLE
rav1e error compiling

### ISSUE THREAD

**Issue by somogpt1** [m-ab-s/media-autobuild_suite#2225] opened 2022-06-24 18:23 UTC
``` bash
   Compiling rav1e v0.5.0 (D:\_media_working_path\build\rav1e-git)
warning: use of deprecated associated function `clap_complete::Shell::possible_values`: Replaced with `EnumValueParser`
   --> src\bin\common.rs:400:46
    |
400 |                      .possible_values(Shell::possible_values().collect::<Vec<_>>())
    |                                              ^^^^^^^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1


```

[ab-suite.rust.build.zip](https://github.com/m-ab-s/media-autobuild_suite/files/8979069/ab-suite.rust.build.zip)

**Comment by 1480c1** [comment] 2022-06-24 18:24
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2217, and next time, please include the logs.zip

**Closed by 1480c1** 2022-06-24 18:24 UTC
