### ISSUE TITLE
Error running make when updating ffmpeg

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#2171] opened 2022-04-16 01:29 UTC
``` bash
09:14:02 ┌ ffmpeg git  .................................. [Updates found]
09:14:02 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
        Patch could not be applied with `git am`. Continuing without patching.
09:14:09 ├ Compiling static FFmpeg...
09:14:12 ├ Running configure...
09:19:12 ├ Running make...
Likely error (tail of the failed operation logfile):
AR      libavfilter/libavfilter.a
CC      libavcodec/libsvt_hevc.o
src/libavcodec/libsvt_hevc.c:571:6: error: 'FFCodec' has no member named 'encode2'
  571 |     .encode2        = eb_encode_frame,
      |      ^~~~~~~
src/libavcodec/libsvt_hevc.c:571:23: warning: initialization of 'int (*)(struct AVCodecContext *, struct AVFrame *, int *, struct AVPacket *)' from incompatible pointer type 'int (*)(AVCodecContext *, AVPacket *, const AVFrame *, int *)' [-Wincompatible-pointer-types]
  571 |     .encode2        = eb_encode_frame,
      |                       ^~~~~~~~~~~~~~~
src/libavcodec/libsvt_hevc.c:571:23: note: (near initialization for 'ff_libsvt_hevc_encoder.cb.decode')
make: *** [/build/ffmpeg-git/ffbuild/common.mak:78: libavcodec/libsvt_hevc.o] Error 1
make failed. Check C:/MinGW-w64/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
09:22:07   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/ocW7.zip
Copy and paste [logs.zip](https://0x0.st/ocW7.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

[logs.zip](https://0x0.st/ocW7.zip)
[ab-suite.make.log](https://github.com/m-ab-s/media-autobuild_suite/files/8499044/ab-suite.make.log)

**Comment by 1480c1** [comment] 2022-04-16 01:34
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2164

**Closed by 1480c1** 2022-04-16 01:34 UTC
