### ISSUE TITLE
Configuration Error

### ISSUE THREAD

**Issue by mwkenna** [m-ab-s/media-autobuild_suite#2634] opened 2024-04-08 09:38 UTC
I have an issue:

configure: error: TLS not detected, you will not be able to use HTTPS, FTPS, NTLM and more.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/14903683/logs.zip)

**Comment by mwkenna** [comment] 2024-04-08 12:10
I believe this something to do with the use of mbedtls which I have disabled in favor of libtls. It seems to be building now

**Comment by 1480c1** [comment] 2024-04-30 18:10
duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2627

**Closed by 1480c1** 2024-04-30 18:10 UTC
