### ISSUE TITLE
ffmpeg git failing 

### ISSUE THREAD

**Issue by Fishman0919** [m-ab-s/media-autobuild_suite#2469] opened 2023-06-23 21:08 UTC
16:56:10 ┌ ffmpeg git  ............................... [Recently updated]
16:56:10 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch
        Patch could not be applied with `git am`. Continuing without patching.
16:56:16 ├ Compiling static FFmpeg...
16:56:17 ├ Running configure...
16:59:16 ├ Running make...
Likely error (tail of the failed operation logfile):
C:/MAS/local64/include/jxl/decode.h:723:50: note: expected 'JxlColorProfileTarget' but argument is of type 'JxlPixelFormat *'
  723 |     const JxlDecoder* dec, JxlColorProfileTarget target,
      |                            ~~~~~~~~~~~~~~~~~~~~~~^~~~~~
C:/MAS/build/ffmpeg-git/libavcodec/libjxldec.c:261:20: error: too many arguments to function 'JxlDecoderGetColorAsEncodedProfile'
  261 |             jret = JxlDecoderGetColorAsEncodedProfile(ctx->decoder, &ctx->jxl_pixfmt, JXL_COLOR_PROFILE_TARGET_DATA, &jxl_color);
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/MAS/local64/include/jxl/decode.h:722:29: note: declared here
  722 | JXL_EXPORT JxlDecoderStatus JxlDecoderGetColorAsEncodedProfile(
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [/build/ffmpeg-git/ffbuild/common.mak:81: libavcodec/libjxldec.o] Error 1
make failed. Check C:/MAS/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
17:02:41   Creating diagnostics file...

Attach C:\MAS\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/11853047/logs.zip)

**Comment by Georgecolla** [comment] 2023-06-24 01:49
i have this issue to if someone have solution type

**Comment by Biswa96** [comment] 2023-06-24 04:11
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2466

**Comment by 1480c1** [comment] 2023-06-29 20:45
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2466

**Closed by 1480c1** 2023-06-29 20:45 UTC
