### ISSUE TITLE
Error running git update for SVT-AV1

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#1441] opened 2019-10-18 21:53 UTC
``` bash
22:57:34   Running git update for SVT-AV1...
22:57:43 ┌ SVT-AV1 git  ................................. [Updates found]
22:57:43 ├ Running uninstall...
22:57:43 ├ Running cmake...
22:57:52 ├ Running build...
Likely error (tail of the failed operation logfile):
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(selfguided_avx2.c.obj):selfguided_avx2.c:(.text+0x1361): undefined reference to `__memset_chk'
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(selfguided_avx2.c.obj):selfguided_avx2.c:(.text+0x1379): undefined reference to `__memset_chk'
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(EbCodingLoop.c.obj):EbCodingLoop.c:(.text+0x2fd7): undefined reference to `__memcpy_chk'
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(EbCodingLoop.c.obj):EbCodingLoop.c:(.text+0x3477): undefined reference to `__memcpy_chk'
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(EbCodingLoop.c.obj):EbCodingLoop.c:(.text+0x372d): undefined reference to `__memcpy_chk'
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(EbCodingLoop.c.obj):EbCodingLoop.c:(.text+0x3783): undefined reference to `__memcpy_chk'
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(EbCodingLoop.c.obj):EbCodingLoop.c:(.text+0x3801): undefined reference to `__memcpy_chk'
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(EbCodingLoop.c.obj):EbCodingLoop.c:(.text+0x3883): more undefined references to `__memcpy_chk' follow
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check C:/mingw/build/SVT-AV1-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
22:59:43   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zxhD.zip
Copy and paste [logs.zip](https://0x0.st/zxhD.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

[logs.zip](https://0x0.st/zxhD.zip)
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/3745790/ab-suite.build.log)

**Comment by 1480c1** [comment] 2019-10-18 21:57
Have you already tried deleting and rebuilding?

**Comment by 1480c1** [comment] 2019-10-18 22:06
Nevermind, seems to be related to fortify_source and stack-protector

**Comment by ImportTaste** [comment] 2019-10-20 21:59
Pasting this in a new mintty console will fix the issue for now.

```
echo '#!/bin/bash

_pre_cmake() {
    if curl --output /dev/null --silent --head --fail "https://github.com/1480c1/SVT-AV1/commit/2cdee179033055e7d3222125c56f02cffd86d2d0.patch"
    then
        do_patch "https://github.com/OpenVisualCloud/SVT-AV1/commit/2cdee179033055e7d3222125c56f02cffd86d2d0.patch"
    else
        rm -f /trunk/build/SVT-AV1_extra.sh
    fi
}'>build/SVT-AV1_extra.sh
```

**Comment by 1480c1** [comment] 2019-10-20 22:09
You can change that to
```bash
echo '#!/bin/bash

_pre_cmake() {
    if curl --output /dev/null --silent --head --fail "https://patch-diff.githubusercontent.com/raw/OpenVisualCloud/SVT-AV1/pull/717.patch"
    then
        do_patch "https://patch-diff.githubusercontent.com/raw/OpenVisualCloud/SVT-AV1/pull/717.patch"
    else
        rm -f /trunk/build/SVT-AV1_extra.sh
    fi
}'>/trunk/build/SVT-AV1_extra.sh
```

Although, why not just use `do_patch` directly? `curl --output /dev/null --silent --head --fail "https://github.com/1480c1/SVT-AV1/commit/2cdee179033055e7d3222125c56f02cffd86d2d0.patch"` should theoretically always resolve since that commit should never go away even if I delete the branch as long as there is an internet connection

**Comment by ImportTaste** [comment] 2019-10-20 22:26
You're right, my test must've been flawed. This should work:

```
echo '#!/bin/bash

_pre_cmake() {
    if curl --output /dev/null --silent --head --fail "https://github.com/1480c1/SVT-AV1/tree/stack"
    then
        do_patch "https://patch-diff.githubusercontent.com/raw/OpenVisualCloud/SVT-AV1/pull/717.patch"
    else
        rm -f /trunk/build/SVT-AV1_extra.sh
    fi
}'>build/SVT-AV1_extra.sh
```

Also updated the version above so someone won't use the wrong one by accident.

**Comment by ImportTaste** [comment] 2019-10-21 00:43
What do you think of this one? It takes a couple seconds but it seems like it's fool-proof.

```bash
echo '#!/bin/bash

_pre_cmake() {
    local any="[\s\S]*"
    local propen="title=\"Status\: Open\""
    if [ "`wget -qnv https://github.com/OpenVisualCloud/SVT-AV1/pull/717 -O - | sed -rn "s/$any($propen)$any/\1/p"`" ]
    then
        do_patch "https://patch-diff.githubusercontent.com/raw/OpenVisualCloud/SVT-AV1/pull/717.patch"
    else
        rm -f /trunk/build/SVT-AV1_extra.sh
    fi
}'>/trunk/build/SVT-AV1_extra.sh
```

**Comment by 1480c1** [comment] 2019-10-21 02:23
Seems good, but I do think that there's a way to use github's api to curl the status of a pr

**Comment by ImportTaste** [comment] 2019-10-21 06:23
I couldn't find a way to do it without doing a checkout.

**Comment by BlackScreen** [comment] 2019-10-21 11:42
I have the same problem as described in the first post:

```
12:29:52   Running git clone for SVT-AV1...
12:30:02 ┌ SVT-AV1 git  .............................. [Recently updated]
12:30:02 ├ Running cmake...
12:30:14 ├ Running build...
Likely error (tail of the failed operation logfile):
C:/Development/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(selfguided_avx2.c.obj):selfguided_avx2.c:(.text+0x1361): undefined reference to `__memset_chk'
C:/Development/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(selfguided_avx2.c.obj):selfguided_avx2.c:(.text+0x1379): undefined reference to `__memset_chk'
C:/Development/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(EbCodingLoop.c.obj):EbCodingLoop.c:(.text+0x2fd7): undefined reference to `__memcpy_chk'
C:/Development/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(EbCodingLoop.c.obj):EbCodingLoop.c:(.text+0x3477): undefined reference to `__memcpy_chk'
C:/Development/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(EbCodingLoop.c.obj):EbCodingLoop.c:(.text+0x372d): undefined reference to `__memcpy_chk'
C:/Development/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(EbCodingLoop.c.obj):EbCodingLoop.c:(.text+0x3783): undefined reference to `__memcpy_chk'
C:/Development/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(EbCodingLoop.c.obj):EbCodingLoop.c:(.text+0x3801): undefined reference to `__memcpy_chk'
C:/Development/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../Bin/Release/libSvtAv1Enc.a(EbCodingLoop.c.obj):EbCodingLoop.c:(.text+0x3883): more undefined references to `__memcpy_chk' follow
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check C:/Development/MABS/build/SVT-AV1-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
12:30:42   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/z3Ql.zip
Copy and paste [logs.zip](https://0x0.st/z3Ql.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

**Comment by 1480c1** [comment] 2019-10-21 11:44
Look at the successive posts. It should be fixed by https://github.com/OpenVisualCloud/SVT-AV1/pull/717, but I'm waiting a little bit to see if they merge it soon before adding the fix on mabs' side

**Comment by LigH-de** [comment] 2019-10-22 13:30
I am surpised that MABS tries to build STV-AV1 despite disabling it in the INI: `svtav1=2`

**Comment by 1480c1** [comment] 2019-10-22 13:38
Check ffmpeg_options.txt for `--enable-libsvtav1`

**Comment by wiiaboo** [comment] 2019-10-22 14:18
Most other encoding libs don't recompile themselves if the .bat option is disabled. If ffmpeg_options.txt includes them, they check if it's already compiled and leave it, or remove it from the options if it's not installed.
This is used to avoid building encoding libs too much.

**Comment by LigH-de** [comment] 2019-10-22 14:38
OK, using a minimal options file together with a limited INI works as intended.

**Comment by ImportTaste** [comment] 2019-10-24 04:11
Resolved with #1447

**Comment by 1480c1** [comment] 2019-10-24 04:13
Not really, but slightly

**Comment by 1480c1** [comment] 2019-10-24 04:14
The original patch has not been accepted upstream, so it's a bandaid

**Comment by ImportTaste** [comment] 2019-10-24 04:17
Resolved in the sense that the errors posted in the first post of the issue no longer occur, anyway.

**Closed** 2019-10-29 01:18 UTC
Labels: bug
