### ISSUE TITLE
Error running git update for libjxl

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#2101] opened 2022-01-15 10:08 UTC
17:50:36 └ libavif-git  ....................................... [Updated]
17:50:49   Running git update for libjxl...
17:51:14 ┌ libjxl git  .................................. [Updates found]
17:51:17 ├ Uninstalling asciidoc-py3-git... failed
17:51:34 ├ Running cmake...
Likely error (tail of the failed operation logfile):
  but not all the files it references.

Call Stack (most recent call first):
  C:/MinGW-w64/msys64/mingw64/lib/cmake/gflags/gflags-config.cmake:17 (include)
  third_party/CMakeLists.txt:168 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/MinGW-w64/build/libjxl-git/build-64bit/CMakeFiles/CMakeOutput.log".
See also "C:/MinGW-w64/build/libjxl-git/build-64bit/CMakeFiles/CMakeError.log".
cmake failed. Check C:/MinGW-w64/build/libjxl-git/build-64bit/ab-suite.cmake.log
This is required for other packages, so this script will exit.
17:51:44   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/o-wy.zip
Copy and paste [logs.zip](https://0x0.st/o-wy.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

 [logs.zip](https://0x0.st/o-wy.zip)
[CMakeOutput.log](https://github.com/m-ab-s/media-autobuild_suite/files/7874717/CMakeOutput.log)
[CMakeError.log](https://github.com/m-ab-s/media-autobuild_suite/files/7874718/CMakeError.log)

**Comment by moisespr123** [comment] 2022-01-16 13:42
Duplicate of #2100

**Closed** 2022-01-17 20:23 UTC
