### ISSUE TITLE
Error running make when update ffmpeg

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#2226] opened 2022-06-25 11:17 UTC
18:57:57 └ libplacebo-git  .................................... [Updated]
18:58:36   Running git update for ffmpeg...
18:59:36 ┌ ffmpeg git  .................................. [Updates found]
18:59:36 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
18:59:43 ├ Compiling static FFmpeg...
18:59:45 ├ Running uninstall...
18:59:45 ├ Running configure...
19:04:51 ├ Running make...
Likely error (tail of the failed operation logfile):
C:/MinGW-w64/local64/include/DeckLinkAPI.h:20309:28: warning: redundant redeclaration of 'void BSTR_UserFree(ULONG*, OLECHAR**)' in same scope [-Wredundant-decls]
20309 | void            __RPC_USER BSTR_UserFree     (ULONG *, BSTR *);
      |                            ^~~~~~~~~~~~~
C:/MinGW-w64/msys64/mingw64/include/propidl.h:1122:28: note: previous declaration of 'void BSTR_UserFree(ULONG*, OLECHAR**)'
 1122 | void            __RPC_USER BSTR_UserFree     (ULONG *, BSTR *);
      |                            ^~~~~~~~~~~~~
src/libavdevice/decklink_common.cpp: In function 'int ff_decklink_set_configs(AVFormatContext*, decklink_direction_t)':
src/libavdevice/decklink_common.cpp:187:58: warning: comparison of integer expressions of different signedness: 'int' and 'long long unsigned int' [-Wsign-compare]
  187 |             if (ctx->duplex_mode < 0 || ctx->duplex_mode >= FF_ARRAY_ELEMS(decklink_profile_id_map))
make: *** [/build/ffmpeg-git/ffbuild/common.mak:84: libavdevice/decklink_common.o] Error 1
make failed. Check C:/MinGW-w64/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
19:05:05   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oSQv.zip
Copy and paste [logs.zip](https://0x0.st/oSQv.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

[logs.zip](https://0x0.st/oSQv.zip)
[ab-suite.make.log](https://github.com/m-ab-s/media-autobuild_suite/files/8984573/ab-suite.make.log)

**Comment by hydra3333** [comment] 2022-06-26 01:36
could you add decklink to the title ?

I get a similar but different error message when cross-compiling ffmpeg under ubuntu with target windows x64, to do with decklink and use of "void".  I ended up having to disable decklink in the build.

Something changed.

**Comment by 1480c1** [comment] 2022-06-26 18:14
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2223

**Closed by 1480c1** 2022-06-26 18:14 UTC
