### ISSUE TITLE
FFmpeg fails to compile

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2350] opened 2022-12-27 03:17 UTC
┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
├ Compiling static FFmpeg...
├ Running uninstall...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
D:/MABS-ffmpeg/build/ffmpeg-git/libavutil/hwcontext_vulkan.c:364:7: error: 'VK_EXT_VIDEO_DECODE_H265_EXTENSION_NAME' undeclared here (not in a function); did you mean 'VK_EXT_VIDEO_ENCODE_H265_EXTENSION_NAME'?
  364 |     { VK_EXT_VIDEO_DECODE_H265_EXTENSION_NAME,                FF_VK_EXT_NO_FLAG                },
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       VK_EXT_VIDEO_ENCODE_H265_EXTENSION_NAME
D:/MABS-ffmpeg/build/ffmpeg-git/libavutil/hwcontext_vulkan.c: In function 'create_instance':
D:/MABS-ffmpeg/build/ffmpeg-git/libavutil/hwcontext_vulkan.c:742:32: warning: initialization of 'VkBool32 (__attribute__((stdcall)) *)(VkDebugUtilsMessageSeverityFlagBitsEXT,  VkDebugUtilsMessageTypeFlagsEXT,  const VkDebugUtilsMessengerCallbackDataEXT *, void *)' {aka 'unsigned int (__attribute__((stdcall)) *)(VkDebugUtilsMessageSeverityFlagBitsEXT,  unsigned int,  const VkDebugUtilsMessengerCallbackDataEXT *, void *)'} from incompatible pointer type 'VkBool32 (*)(VkDebugUtilsMessageSeverityFlagBitsEXT,  VkDebugUtilsMessageTypeFlagsEXT,  const VkDebugUtilsMessengerCallbackDataEXT *, void *)' {aka 'unsigned int (*)(VkDebugUtilsMessageSeverityFlagBitsEXT,  unsigned int,  const VkDebugUtilsMessengerCallbackDataEXT *, void *)'} [-Wincompatible-pointer-types]
  742 |             .pfnUserCallback = vk_dbg_callback,
      |                                ^~~~~~~~~~~~~~~
D:/MABS-ffmpeg/build/ffmpeg-git/libavutil/hwcontext_vulkan.c:742:32: note: (near initialization for 'dbg.pfnUserCallback')
make: *** [/build/ffmpeg-git/ffbuild/common.mak:81: libavutil/hwcontext_vulkan.o] Error 1
make failed. Check D:/MABS-ffmpeg/build/ffmpeg-git/build-static-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/10305648/logs.zip)

**Comment by 1480c1** [comment] 2022-12-27 03:20
Should be duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2345, I think it may be because you might be using n5.1? You could either try the vulkan-loader thing mentioned in that issue or `git cherry-pick eb0455d646` inside your ffmpeg_extra.sh

**Closed by 1480c1** 2022-12-27 03:20 UTC
