### ISSUE TITLE
[mingw64] Tesseract build fails

### ISSUE THREAD

**Issue by FredMSloniker** [m-ab-s/media-autobuild_suite#1509] opened 2019-12-25 02:12 UTC
I tried the December 24 download, but no soap. Here's the tail end of the log (link to full debug zip at the end):
```
  Running git clone for tesseract...
 ┌ tesseract git  ............................ [Recently updated]
 ├ Installing docbook-xsl... done
 ├ Installing libarchive... done
 ├ Running autogen...
 ├ Running configure...
 ├ Running make...
Likely error (tail of the failed operation logfile):
D:/Downloads/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Downloads/media-autobuild_suite-master/msys64/mingw64/lib/libpsl.a(libpsl_la-psl.o):(.text+0x12cb): undefined reference to `__imp_uninorm_nfkc'
D:/Downloads/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Downloads/media-autobuild_suite-master/msys64/mingw64/lib/libpsl.a(libpsl_la-psl.o):(.text+0x12f2): undefined reference to `u8_tolower'
D:/Downloads/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Downloads/media-autobuild_suite-master/msys64/mingw64/lib/libpsl.a(libpsl_la-psl.o):(.text+0x1378): undefined reference to `__imp_uninorm_nfkc'
D:/Downloads/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Downloads/media-autobuild_suite-master/msys64/mingw64/lib/libpsl.a(libpsl_la-psl.o):(.text+0x1393): undefined reference to `u8_tolower'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:2365: tesseract.exe] Error 1
make[2]: Leaving directory '/build/tesseract-git/build-64bit'
make[1]: *** [Makefile:4348: all-recursive] Error 1
make[1]: Leaving directory '/build/tesseract-git/build-64bit'
make: *** [Makefile:1577: all] Error 2
make failed. Check D:/Downloads/media-autobuild_suite-master/build/tesseract-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
```

[logs.zip](https://0x0.st/zGOl.zip)

**Comment by 1480c1** [comment] 2019-12-25 05:41
Was able to repo, I have a few ideas already on how to fix, but nothing promised soon(Valve Time ™)

**Comment by hydra3333** [comment] 2020-01-02 08:24
well, just a thought and not sure if this helps in any way whatsoever ...
based on Deadsix27's code it compiles with cflags=-O3 -fstack-protector-all -D_FORTIFY_SOURCE=2 using this stuff

```
{
	'repo_type' : 'git',
	'url' : 'https://github.com/tesseract-ocr/tesseract.git',
	'conf_system' : 'cmake',
	'source_subfolder' : '_build',
	'configure_options' : '.. {cmake_prefix_options} -DCMAKE_INSTALL_PREFIX={target_prefix} -DBUILD_SHARED_LIBS=0 -DBUILD_TRAINING_TOOLS=0 -DSW_BUILD=0 -DBUILD_TRAINING_TOOLS=0 -DBUILD_TESTS=0 -DSTATIC=1 -DHAVE_LIBARCHIVE=1 -DLIBRARY_TYPE=STATIC -DCMAKE_BUILD_TYPE=Release',
	'regex_replace': {
		'post_patch': [
			{
				0: 
					r'    if\(LibArchive_FOUND\)\n'
				,
				1:
					r'    set(LibArchive_LIBRARIES "!CMD(pkg-config libarchive --libs-only-l)CMD!")\n'
					r'    message(STATUS "LibArchive Libs: ${{LibArchive_LIBRARIES}}")\n'
    				r'    if(LibArchive_FOUND)\n'
				,
				'in_file': '../CMakeLists.txt'
			},
			{
				0: r'set\(LIB_Ws2_32 Ws2_32\)',
				1: r'set(LIB_Ws2_32 ws2_32)',
				'in_file': '../CMakeLists.txt'
			}
		],
		'post_install': [
			{
				0: r'^(?:[\s]+)?Libs:(?:[\s]+)?-L\${{libdir}}(?:[\s]+)?(-ltesseract[0-9]{{2}})(?:[^\n]+)?$',
				1: r'Requires: lept libarchive\nRequires.private: lept libarchive\nLibs: -L${{libdir}} \1 -lstdc++ -lws2_32',
				'in_file': '{pkg_config_path}/tesseract.pc'
			}
		]
	},
	'depends_on' : [ 'leptonica', 'libxml2', 'zlib', 'libarchive', 'libtiff'],
	'_info' : { 'version' : 'git (master)', 'fancy_name' : 'tesseract' },
}
```

**Comment by 1480c1** [comment] 2020-01-02 15:25
The main reason why this is failing is because of curl and its dependencies aren't being linked properly.

Tesseract is pulling msys2's mingw-w64 curl, which seems to have been built using a shared version of nghttp2 and doesn't have the required libraries listed to link.

Another difference between our setup is he is using their cmakelist and we are using autotools. Although I do want to use their cmakelist, it seems it's not highly supported and they are pushing people to use autotools instead of cmake, using only cmake if autotools are not available along with the two being slightly different in output.

**Comment by FredMSloniker** [comment] 2020-01-09 17:05
I just confirmed the 32-bit build also fails, same issue.

**Comment by aidik** [comment] 2020-03-22 20:06
Today after a while I got back to this issue and I'm surprised it wasn't anything small and the issue is still persistent.

Just in case someone is looking for a way how to build the suite. You can comment out the `--enable-libtesseract` option in _**build/ffmpeg_options.txt**_ and unless you really need Tesseract for your project you should be good to go.

**Comment by 1480c1** [comment] 2020-04-05 18:13
Closed in https://github.com/m-ab-s/media-autobuild_suite/commit/7b8c85c578de865cb5df72ac74fc503faa91965e

**Closed by 1480c1** 2020-04-05 18:13 UTC
Labels: Tesseract, bug
