### ISSUE TITLE
[mingw64] Building of ffmpeg with libcodec2 failed

### ISSUE THREAD

**Issue by lastrosade** [m-ab-s/media-autobuild_suite#1477] opened 2019-11-11 15:57 UTC
``` bash
 ┌ ffmpeg git  ............................... [Recently updated]
 ├ Changing options to comply to gplv3...
patch unexpectedly ends in middle of line
 ├ Compiling static FFmpeg...
 ├ Running uninstall...
 ├ Running configure...
 ├ Running make...
Likely error (tail of the failed operation logfile):
C:\mingw\media-autobuild_suite-master\build\codec2-0.8-svn\build-64bit/../src/c2wideband.c:339: multiple definition of `mean'; C:/mingw/media-autobuild_suite-master/local64/lib/libvidstab.a(transformtype.c.o):transformtype.c:(.text+0xc80): first defined here
C:/mingw/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/media-autobuild_suite-master/local64/lib/libxvidcore.a(idct.obj): warning: common of `idct' overridden by definition from C:/mingw/media-autobuild_suite-master/local64/lib/libcodec2.a(dct2.c.o)
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:111: ffmpeg_g.exe] Error 1
LD	ffmpeg_g.exe
C:/mingw/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/media-autobuild_suite-master/local64/lib/libcodec2.a(c2wideband.c.o): in function `mean':
C:\mingw\media-autobuild_suite-master\build\codec2-0.8-svn\build-64bit/../src/c2wideband.c:339: multiple definition of `mean'; C:/mingw/media-autobuild_suite-master/local64/lib/libvidstab.a(transformtype.c.o):transformtype.c:(.text+0xc80): first defined here
C:/mingw/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/media-autobuild_suite-master/local64/lib/libxvidcore.a(idct.obj): warning: common of `idct' overridden by definition from C:/mingw/media-autobuild_suite-master/local64/lib/libcodec2.a(dct2.c.o)
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:111: ffmpeg_g.exe] Error 1
make failed. Check C:/mingw/media-autobuild_suite-master/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
   Creating diagnostics file...
```

[logs.zip](https://0x0.st/zEtJ.zip)

**Comment by ycwan** [comment] 2019-11-14 08:53
#1473 
After force disable libssh, force recompilation of ffmpeg enconter error similar to this issue

**Comment by wiiaboo** [comment] 2019-11-15 09:48
This has nothing to do with libssh. It's xvid and codec2. Both have symbols with the same name. Since we compile codec2, we'd need to rename them, same as we already do to avoid conflicts with speex.

**Comment by wiiaboo** [comment] 2019-11-15 09:48
And also vidstab and codec2.

**Comment by 1480c1** [comment] 2019-11-23 21:01
@lastrosade, @ycwan, can you confirm that this still occurs?

**Comment by ycwan** [comment] 2019-11-24 05:07
12:16:28   Running git update for ffmpeg...
12:16:34 ┌ ffmpeg git  .................................. [Updates found]
12:16:34 ├ Until SVT-AV1 issues a fix, libsvtav1 must be disabled while libsvthevc is enabled....
12:16:34 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
patch unexpectedly ends in middle of line
12:16:46 ├ Compiling static FFmpeg...
12:16:50 ├ Running uninstall...
12:16:57 ├ Running configure...
12:25:04 ├ Running make...
Likely error (tail of the failed operation logfile):
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/msys64/mingw64/lib/libxml2.a(pathtools.o):(.text+0x6b0): multiple definition of `get_relocated_path'; C:/mingw/msys64/mingw64/lib/libcrypto.a(pathtools.o):(.text+0x7a0): first defined here
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/msys64/mingw64/lib/libxml2.a(pathtools.o):(.text+0x6f0): multiple definition of `get_executable_path'; C:/mingw/msys64/mingw64/lib/libcrypto.a(pathtools.o):(.text+0x7e0): first defined here
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/msys64/mingw64/lib/libxml2.a(pathtools.o):(.text+0x7c0): multiple definition of `strip_n_prefix_folders'; C:/mingw/msys64/mingw64/lib/libcrypto.a(pathtools.o):(.text+0x8b0): first defined here
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/msys64/mingw64/lib/libxml2.a(pathtools.o):(.text+0x820): multiple definition of `strip_n_suffix_folders'; C:/mingw/msys64/mingw64/lib/libcrypto.a(pathtools.o):(.text+0x910): first defined here
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/msys64/mingw64/lib/libxml2.a(pathtools.o):(.text+0x870): multiple definition of `split_path_list'; C:/mingw/msys64/mingw64/lib/libcrypto.a(pathtools.o):(.text+0x960): first defined here
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/msys64/mingw64/lib/libxml2.a(pathtools.o):(.text+0x890): multiple definition of `get_relocated_path_list'; C:/mingw/msys64/mingw64/lib/libcrypto.a(pathtools.o):(.text+0x980): first defined here
C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mingw/local64/lib/librav1e.a(compiler_builtins-477d6ada7584f678.compiler_builtins.1c0g4lf3-cgu.0.rcgu.o): in function `___chkstk_ms':
C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\compiler_builtins-0.1.18\src/x86_64.rs:15: multiple definition of `___chkstk_ms'; C:/mingw/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/libgcc.a(_chkstk_ms.o):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:111: ffmpeg_g.exe] Error 1
make failed. Check C:/mingw/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
12:48:25   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zIcD.zip
Copy and paste [logs.zip](https://0x0.st/zIcD.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

[ab-suite.make.log](https://github.com/m-ab-s/media-autobuild_suite/files/3883218/ab-suite.make.log)

**Comment by 1480c1** [comment] 2019-11-30 00:17
Closing since I can't reproduce this exact error plus we are no longer using codec2 from svn and instead have moved to their git development repository

**Closed by 1480c1** 2019-11-30 00:17 UTC
Labels: bug

**Comment by lastrosade** [comment] 2019-12-06 02:26
Sorry for beeing so late, the problem is indeed gone, thanks!

**Comment by lastrosade** [comment] 2019-12-07 00:54
@1480c1 update, I just launch an encoding job and it seems that ffmpeg doesn't integrate codec2

when doing ffmpeg.exe -codecs
`..A.L. codec2               codec2 (very low bitrate speech codec)`

Trying to encode
`PS F:\Record> ffmpeg.exe -i .\test.wav .\test.c2
ffmpeg version N-95978-g4fceaab6ba-g71fd72070c+2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.0 (Rev2, Built by MSYS2 project)
  configuration:  --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-gmp --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --disable-debug --enable-fontconfig --enable-libass --enable-libfreetype --enable-libmysofa --enable-libopenjpeg --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-gpl --enable-avisynth --enable-libxvid --enable-libopenmpt --enable-version3 --enable-libflite --enable-libfribidi --enable-libilbc --enable-libsvtav1 --enable-libmodplug --enable-librtmp --enable-librubberband --enable-libzmq --enable-libzvbi --enable-openal --enable-libsrt --enable-ladspa --enable-opencl --enable-opengl --enable-gnutls --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DZMQ_STATIC --extra-cflags=-DLIBXML_STATIC
  libavutil      56. 36.101 / 56. 36.101
  libavcodec     58. 64.101 / 58. 64.101
  libavformat    58. 35.101 / 58. 35.101
  libavdevice    58.  9.101 / 58.  9.101
  libavfilter     7. 67.100 /  7. 67.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, wav, from '.\test.wav':
  Metadata:
    encoder         : Lavf58.35.101
  Duration: 00:00:06.00, bitrate: 1411 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, stereo, s16, 1411 kb/s
Automatic encoder selection failed for output stream #0:0. Default encoder for format codec2 (codec codec2) is probably disabled. Please choose an encoder manually.
Error selecting an encoder for stream 0:0`

`PS F:\Record> ffmpeg.exe -i .\test.wav -c codec2 .\test.c2
ffmpeg version N-95978-g4fceaab6ba-g71fd72070c+2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.0 (Rev2, Built by MSYS2 project)
  configuration:  --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-gmp --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --disable-debug --enable-fontconfig --enable-libass --enable-libfreetype --enable-libmysofa --enable-libopenjpeg --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-gpl --enable-avisynth --enable-libxvid --enable-libopenmpt --enable-version3 --enable-libflite --enable-libfribidi --enable-libilbc --enable-libsvtav1 --enable-libmodplug --enable-librtmp --enable-librubberband --enable-libzmq --enable-libzvbi --enable-openal --enable-libsrt --enable-ladspa --enable-opencl --enable-opengl --enable-gnutls --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DZMQ_STATIC --extra-cflags=-DLIBXML_STATIC
  libavutil      56. 36.101 / 56. 36.101
  libavcodec     58. 64.101 / 58. 64.101
  libavformat    58. 35.101 / 58. 35.101
  libavdevice    58.  9.101 / 58.  9.101
  libavfilter     7. 67.100 /  7. 67.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, wav, from '.\test.wav':
  Metadata:
    encoder         : Lavf58.35.101
  Duration: 00:00:06.00, bitrate: 1411 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, stereo, s16, 1411 kb/s
Unknown encoder 'codec2'`

**Comment by 1480c1** [comment] 2019-12-07 01:03
```
Codecs:
 D..... = Decoding supported
 .E.... = Encoding supported
 ..V... = Video codec
 ..A... = Audio codec
 ..S... = Subtitle codec
 ...I.. = Intra frame-only codec
 ....L. = Lossy compression
 .....S = Lossless compression
```

`..A.L. codec2 codec2 (very low bitrate speech codec)`
For some reason, yours doesn't support `E`(Encoding), and `D`(Decoding)

**Comment by 1480c1** [comment] 2019-12-07 01:12
Perhaps it's because you are lacking `--enable-libcodec2` in your configuration?

**Comment by lastrosade** [comment] 2019-12-07 01:53
This is embarasing...

I did update the exe that's in my PATH.

Thanks !
