### ISSUE TITLE
x265 build error

### ISSUE THREAD

**Issue by BlackScreen** [m-ab-s/media-autobuild_suite#1268] opened 2019-06-26 15:59 UTC
Since the addition of svt-hevc to x265 there seems to be an error while building - probably has something to do with it?

```
15:48:41   Running hg clone for x265...
15:49:00 ┌ x265 hg .................................. [Recently updated]
15:49:01 ├ Building 12-bit lib for multilib...
15:49:01 ├ Running cmake...
15:49:11 ├ Running build...
15:53:57 ├ Building 10-bit lib for multilib...
15:53:57 ├ Running cmake...
15:54:07 ├ Running build...
15:59:02 ├ Building multilib lib/bin...
15:59:02 ├ Running cmake...
15:59:12 ├ Running build...
Likely error:
.\libx265_main12.a(asm-primitives.cpp.o):asm-primitives.cpp:(.rdata$.refptr.x265_12bit_filterPixelToShort_16x64_sse2[.refptr.x265_12bit_filterPixelToShort_16x64_sse2]+0x0): undefined reference to `x265_12bit_filterPixelToShort_16x64_sse2'
.\libx265_main12.a(asm-primitives.cpp.o):asm-primitives.cpp:(.rdata$.refptr.x265_12bit_scanPosLast_x64[.refptr.x265_12bit_scanPosLast_x64]+0x0): undefined reference to `x265_12bit_scanPosLast_x64'
.\libx265_main12.a(motion.cpp.o):motion.cpp:(.text+0x16af): undefined reference to `x265_12bit_cpu_emms'
.\libx265_main12.a(motion.cpp.o):motion.cpp:(.text+0x1e5f): undefined reference to `x265_12bit_cpu_emms'
.\libx265_main12.a(slicetype.cpp.o):slicetype.cpp:(.text+0x230): undefined reference to `x265_12bit_cpu_emms'
.\libx265_main12.a(slicetype.cpp.o):slicetype.cpp:(.text+0xe5b): undefined reference to `x265_12bit_cpu_emms'
.\libx265_main12.a(slicetype.cpp.o):slicetype.cpp:(.text+0xf5c): undefined reference to `x265_12bit_cpu_emms'
.\libx265_main12.a(slicetype.cpp.o):slicetype.cpp:(.text+0x101a): more undefined references to `x265_12bit_cpu_emms' follow
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check C:/AB-Suite/build/x265-hg/build-64bit/8bit/ab-suite.b
```

**Comment by Barough** [comment] 2019-06-26 22:02
Not sure about that BlackScreen. I haven't enabled SVT-HEVC here and i ran into the same problem....

┌ x265 hg ........................................... [Recently updated]
├ Building 12-bit lib for multilib...
├ Running cmake...
├ Running build...
├ Building 10-bit lib for multilib...
├ Running cmake...
├ Running build...
├ Building multilib lib/bin...
├ Running cmake...
├ Running build...
Likely error:
libx265.a(asm-primitives.cpp.o):asm-primitives.cpp:(.text+0x5754): undefined reference to `x265_pixel_ssd_16x16_xop'
libx265.a(asm-primitives.cpp.o):asm-primitives.cpp:(.text+0x575e): undefined reference to `x265_frame_init_lowres_core_xop'
libx265.a(motion.cpp.o):motion.cpp:(.text+0x154c): undefined reference to `x265_cpu_emms'
libx265.a(motion.cpp.o):motion.cpp:(.text+0x1d1c): undefined reference to `x265_cpu_emms'
libx265.a(slicetype.cpp.o):slicetype.cpp:(.text+0xeb): undefined reference to `x265_cpu_emms'
libx265.a(slicetype.cpp.o):slicetype.cpp:(.text+0xc6f): undefined reference to `x265_cpu_emms'
libx265.a(slicetype.cpp.o):slicetype.cpp:(.text+0xda7): undefined reference to `x265_cpu_emms'
libx265.a(slicetype.cpp.o):slicetype.cpp:(.text+0x1024): more undefined references to `x265_cpu_emms' follow
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check D:/media-autobuild_suite-ffmpeg/build/x265-hg/build-32bit/8bit/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/z2l0.zip
Copy and paste [logs.zip](https://0x0.st/z2l0.zip) in the GitHub issue.

**Comment by wiiaboo** [comment] 2019-06-26 22:08
Seems like a x265 issue. Create an issue there.

**Comment by BlackScreen** [comment] 2019-06-27 20:10
Done.
https://bitbucket.org/multicoreware/x265/issues/499/fails-to-build-with-media-autobuild_suite

**Comment by pat357** [comment] 2019-06-30 19:07
After some intensive testing, it looks like the problem comes from the recent changes in the suite.
Using the latest version from the suite, I could not find any commit that worked : all commits I've tried give the same errors. 
I went back till somewhere beginning this year ( commit 5b90dc5).

I also keep a shadow version from the suite that I update only if everything builds ok.
This version doesn't have the changes to the build-script for x265, it still has the code that we used for a very long time.
Using this older version of MABS, x265 builds without any errors !
So I guess something went wrong with the recent changes related to building x265 in the suite.

I went through the code myself but failed to spot any bug.

**Comment by 1480c1** [comment] 2019-06-30 20:10
How come this error only shows up now?

**Comment by pat357** [comment] 2019-06-30 22:18
Maybe there were no updates ?
Or people like me wanted to try the new option svthevc. ?
Honestly , otherwise I have no clue.

Just try the old code and you'll see x265 builds just fine.
I haven't tried the svthevc option though, so I can't comment on that.

**Comment by wiiaboo** [comment] 2019-06-30 23:42
Yeah, old code didn't break. For now I [reverted](https://github.com/jb-alvarado/media-autobuild_suite/commit/75585dc396ac3935a3bb0099183476bfd02e2871) it, except for the svthevc patch, while someone investigates what's the issue.

**Comment by wiiaboo** [comment] 2019-06-30 23:43
It's only reproducible with standalone=y since it's when compiling/linking the executable that it breaks.

**Comment by BlackScreen** [comment] 2019-07-01 07:51
> Yeah, old code didn't break. For now I [reverted](https://github.com/jb-alvarado/media-autobuild_suite/commit/75585dc396ac3935a3bb0099183476bfd02e2871) it, except for the svthevc patch, while someone investigates what's the issue.

Working again. Thanks for the temporary fix.
And yes, in my case, I rebuild x265 to test the svthevc inclusion.

**Comment by pat357** [comment] 2019-07-01 20:28
@BlackScreen
Maybe it's better to close the issue for the x265 maintainers @https://bitbucket.org/multicoreware/x265/issues/  because it's not really a x265 issue.

**Comment by BlackScreen** [comment] 2019-07-05 13:32
Done. Closed. :)

**Comment by wiiaboo** [comment] 2019-07-05 13:50
This was a suite issue, so this should still remain open.

**Comment by 1480c1** [comment] 2019-07-05 14:03
I'm currently on my way home from a vacation, I will try to look into what was wrong when I get back

**Comment by ImportTaste** [comment] 2019-08-07 21:19
@wiiaboo I am having this issue with the current commit. Based on what you said about temporarily fixing it on July 1st, I don't think this is expected?

**Comment by 1480c1** [comment] 2019-08-07 21:45
You mean building with x265 and SVT-HEVC?

**Comment by 1480c1** [comment] 2019-08-07 21:46
It's still not enabled yet

**Comment by ImportTaste** [comment] 2019-08-07 22:25
@1480c1 So it shouldn't be possible for the script to try? Because it's trying.

**Comment by ImportTaste** [comment] 2019-08-07 22:28
Ah, it's probably because I uncommented --enable-libsvthevc in ffmpeg_options.txt

**Comment by ImportTaste** [comment] 2019-08-07 23:10
Nope, still happening.

**Comment by ImportTaste** [comment] 2019-08-07 23:10
Still happening.
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/3479209/logs.zip)

**Comment by 1480c1** [comment] 2019-08-07 23:18
Different error, not related to building x265 with SVT-HEVC

**Comment by ImportTaste** [comment] 2019-08-07 23:52
I guess I need my eyes checked.

**Comment by 1480c1** [comment] 2019-08-08 00:00
Same honestly

**Comment by Helenerineium** [comment] 2019-08-08 03:44
It seems that [this new patch](https://github.com/msys2/MINGW-packages/commit/1ccbe5331faf0f04123c1f590e026f5e202454df#diff-c15b2291d2c6f3a11ac3157f30dcbda1) in binutils breaks rc compilation in x265.

**Solution:** Rebuild binutils without [that patch](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-binutils/0100-Put-filenames-from-command-line-in-quotes-to-handle-spaces-correctly.patch) or downgrade to a previous version.

**Comment by ImportTaste** [comment] 2019-08-08 15:03
>Solution: Rebuild binutils without that patch or downgrade to a previous version.

How?

**Comment by fangchunxi1999** [comment] 2019-08-08 18:05
> > Solution: Rebuild binutils without that patch or downgrade to a previous version.
> 
> How?

for me use https://stackoverflow.com/a/33986757 as reference 
i download http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-binutils-2.31.1-2-any.pkg.tar.xz to the same directory as mintty shortcut and start the .bat like normal 
after .bat file complet update all package and start to build 
i quickly open up another msmy2 windows and type `pacman -U mingw-w64-x86_64-binutils-2.31.1-2-any.pkg.tar.xz` to downgrade it 
it take some time to check other lib before get to x265 so you don't have to panic 

alternatively maybe you can edit media-suite_update.sh by adding
`have_updates=${have_updates/mingw-w64-x86_64-binutils/}`
after this `have_updates="$(pacman -Qu | grep -v ignored]$ | cut -d' ' -f1)"` line to block the update 
and downgrade this package before run .bat file
but it isn't tested yet

**Comment by wiiaboo** [comment] 2019-08-08 18:44
If not related to x265, continue this in https://github.com/jb-alvarado/media-autobuild_suite/issues/1335.
@fangchunxi1999 do not edit the suite's files. Edit /etc/pacman.conf by uncommenting the IgnorePkg line and adding `mingw-w64-x86_64-binutils` and `mingw-w64-i686-binutils` there after installing the downgraded version.

**Closed** 2019-09-14 15:47 UTC
