### ISSUE TITLE
[mingw64] [musj-git] failed to build musj-git

### ISSUE THREAD

**Issue by suvl** [m-ab-s/media-autobuild_suite#1757] opened 2020-07-18 14:12 UTC
``` bash
15:10:08 └ mujs-git  .......................................... [Updated]
Likely error (tail of the failed operation logfile):
++ vcs_get_latest_tag origin/HEAD git
++ case ${2:-$(vcs_get_current_type)}/${1:-unknown} in
++ false
++ echo origin/HEAD
+ git reset --hard origin/HEAD
warning: ignoring dangling symref refs/remotes/origin/HEAD
warning: ignoring dangling symref refs/remotes/origin/HEAD
fatal: ambiguous argument 'origin/HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
git.reset failed. Check C:/media-autobuild_suite/build/shaderc-git/ab-suite.git.reset.log
This is required for other packages, so this script will exit.
```

[logs.zip](https://0x0.st/ivwv.zip)

**Comment by 1480c1** [comment] 2020-07-18 21:36
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/1733

**Comment by 1480c1** [comment] 2020-07-18 21:37
Please delete `build/shaderc-git` and rerun, the issue is they changed the master branch to main

**Closed by 1480c1** 2020-07-18 21:36 UTC
