### ISSUE TITLE
[clang64] [ffmpeg shared] libplacebo

### ISSUE THREAD

**Issue by esator** [m-ab-s/media-autobuild_suite#2665] opened 2024-05-03 09:13 UTC
Failed to compile ffmpeg shared with libplacebo
```
defined at libplacebo.a(common.c.obj)
defined at avfilter-10.dll

ld.lld: warning: duplicate symbol: pl_transform2x2_invert
defined at libplacebo.a(common.c.obj)
defined at avfilter-10.dll

ld.lld: error: pl_bit_encoding_equal was replaced
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/build/ffmpeg-git/Makefile:139: ffplay_g.exe] Error 1
```

**Comment by 1480c1** [comment] 2024-05-18 04:33
No logs, and I think it's a duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2644

**Closed by 1480c1** 2024-05-18 04:33 UTC
