### ISSUE TITLE
[mingw64] [libwebp] fails to build due to missing gif library

### ISSUE THREAD

**Issue by ggarra13** [m-ab-s/media-autobuild_suite#1985] opened 2021-05-24 03:58 UTC
When compiling the newest libwebp with all the latest files from the repository (cmake compilation included), the build fails when compiling webpmux/webpinfo/etc.  

The problem seems to be twofold: the include directory is set wrong and the gif library is not found (as the media-autobuild_suite never downloads it).  The lack of the gif library turns off the compilation of all the auxiliary libwebp libraries.

``` bash
[103/115] Building C object CMakeFiles/webpencode.dir/src/enc/quant_enc.c.o
ninja: build stopped: subcommand failed.
[1/13] Building C object CMakeFiles/webpmux.dir/examples/webpmux.c.o
FAILED: CMakeFiles/webpmux.dir/examples/webpmux.c.o
D:\abs\msys64\mingw64\bin\ccache.exe  gcc -DHAVE_CONFIG_H -DUNICODE -DWEBP_SWAP_16BIT_CSP=1 -D_UNICODE -Isrc -mthreads -mtune=generic -O2 -pipe -DFREEGLUT_STATIC -pthread -O3 -DNDEBUG   -Wall -MD -MT CMakeFiles/webpmux.dir/examples/webpmux.c.o -MF CMakeFiles\webpmux.dir\examples\webpmux.c.o.d -o CMakeFiles/webpmux.dir/examples/webpmux.c.o -c ../examples/webpmux.c
../examples/webpmux.c:62:10: fatal error: webp/decode.h: No such file or directory
   62 | #include "webp/decode.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```

[logs.zip](https://0x0.st/-eYR.zip)

**Comment by MadameMinty** [comment] 2021-05-25 16:49
Same here. Pretty sure it was working on May 19th. Today I'm having the same issue: https://0x0.st/-eRV.zip

**Comment by moob158** [comment] 2021-05-27 16:44
Same here too

**Comment by 1480c1** [comment] 2021-05-31 18:30
I have cleaned my suite multiple times, but I am still unable to reproduce this issue, have you guys tried deleting the libwep-git and libtiff-git and  checked again?

**Comment by ggarra13** [comment] 2021-05-31 22:03
Yes, I tried deleting both and the same error happens when --enable-libwebp is in one of ffmpeg_options.txt or ffmpeg_options_shared.txt.  Looking at the cmake file it is clear that it won't compile if the gif library cannot be found (which is my case).

**Comment by moob158** [comment] 2021-06-01 23:24
Same here...

![Capturar](https://user-images.githubusercontent.com/60049180/120401936-eacfbd80-c338-11eb-8f48-058d75cb8c50.PNG)

**Comment by RomainKurtz** [comment] 2021-06-02 21:43
Same here.

**Comment by 1480c1** [comment] 2021-06-06 04:19
Try again, I haven't had the issue yet reproduce

**Comment by topse** [comment] 2021-06-07 08:35
I am trying every 2nd day :-/

**Comment by MadameMinty** [comment] 2021-06-09 17:36
Still persists on the version I downloaded 15 minutes ago.  https://0x0.st/-Lsn.zip

https://i.imgur.com/pLxh1iJ.png

Continues to work on this version: https://0x0.st/-LsC.7z

**Comment by 1480c1** [comment] 2021-06-09 17:38
currently trying to fix their cmakelist to make it work

**Comment by topse** [comment] 2021-06-11 04:59
In my case the error changed today in the morning:
 ´´´
[2/4] Linking C executable webpmux.exe
FAILED: webpmux.exe
cmd.exe /C "cd . && Z:\media-autobuild_suite-master\msys64\mingw64\bin\ccache.exe  gcc -mthreads -mtune=generic -O2 -pipe -DFREEGLUT_STATIC -pthread -O3 -DNDEBUG -pipe -static-libgcc -static-libstdc++ CMakeFiles/webpmux.dir/examples/webpmux.c.o -o webpmux.exe -Wl,--out-implib,libwebpmux.dll.a -Wl,--major-image-version,0,--minor-image-version,0  -lexampleutil  -limageioutil  -llibwebpmux  libwebp.a  -lshlwapi  -lole32  -lwindowscodecs  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
Z:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lexampleutil
Z:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -limageioutil
Z:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -llibwebpmux
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
´´´

https://0x0.st/-Lb1.zip

**Comment by 1480c1** [comment] 2021-06-12 06:09
pushed some additional patches, please try again after updating to the latest suite

**Comment by 1480c1** [comment] 2021-06-12 06:10
If they work, I might try to get them upstreamed, depending on their reaction.

**Comment by ASopH** [comment] 2021-06-12 06:16
Just tested, sadly no success (I deleted the libwebp folder before - thanks for invetigate!
08:13:10   Running git clone for libwebp...
08:13:17 ┌ libwebp git  .............................. [Recently updated]
08:13:28 ├ Running cmake...
08:13:37 ├ Running build...
Likely error (tail of the failed operation logfile):
F:/m-a-s/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -limageioutil
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
[1/2] Linking C executable webpmux.exe
FAILED: webpmux.exe
cmd.exe /C "cd . && F:\m-a-s\msys64\mingw64\bin\ccache.exe  gcc -mthreads -mtune=generic -O2 -pipe -DFREEGLUT_STATIC -pthread -O3 -DNDEBUG -pipe -static-libgcc -static-libstdc++ CMakeFiles/webpmux.dir/examples/webpmux.c.o -o webpmux.exe -Wl,--out-implib,libwebpmux.dll.a -Wl,--major-image-version,0,--minor-image-version,0  -lexampleutil  -limageioutil  libwebpmux.a  libwebp.a  -lshlwapi  -lole32  -lwindowscodecs  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
F:/m-a-s/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lexampleutil
F:/m-a-s/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -limageioutil
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6641757/logs.zip)

**Comment by 1480c1** [comment] 2021-06-12 06:21
pushed another patch

**Comment by 1480c1** [comment] 2021-06-12 06:23
Wait, you were compiling with standalone off, okay, I think that just means I need to add another flag to remove webpmux

**Comment by ASopH** [comment] 2021-06-12 06:31
passed, but I want compile 32bit too :-)

08:24:10   Running git clone for libwebp...
08:24:17 ┌ libwebp git  .............................. [Recently updated]
0001-FindPkgConfig-split-args-if-loaded-from-environment.patch
        Patch could not be applied with `patch`. Continuing without patching.
0002-FindTIFF-Use-pkg-config-for-finding-dependencies.patch
        Patch could not be applied with `patch`. Continuing without patching.
0003-FindGLUT-Use-pkg-config-for-finding-dependencies.patch
        Patch could not be applied with `patch`. Continuing without patching.
0004-FindZLIB-Use-pkg-config-for-finding-dependencies.patch
        Patch could not be applied with `patch`. Continuing without patching.
0005-FindPNG-Use-pkg-config-for-finding-dependencies.patch
        Patch could not be applied with `patch`. Continuing without patching.
0006-FindJPEG-Use-pkg-config-for-finding-dependencies.patch
        Patch could not be applied with `patch`. Continuing without patching.
08:24:28 ├ Running cmake...
08:24:36 ├ Running build...
08:24:48 ├ Running install...
08:24:48 ├ Stripping...
08:24:48 └ libwebp-git  ....................................... [Updated]

**Comment by 1480c1** [comment] 2021-06-12 06:32
Yeah, that's mainly there because it's patching some system libraries. it's fine to ignore for now

**Comment by ASopH** [comment] 2021-06-12 06:35
I've started a new run with x32 and x64. This will take a while, because it's a new build setup..

**Comment by ASopH** [comment] 2021-06-12 07:58
hmm, it seems x32 don't go on ...
09:35:42   Running git update for libwebp...
09:35:42 ┌ libwebp git  .............................. [Recently updated]
09:35:54 ├ Running cmake...
09:36:22 ├ Running build...
Likely error (tail of the failed operation logfile):
[9/56] Building C object CMakeFiles/webpencode.dir/src/enc/analysis_enc.c.o
[10/56] Building C object CMakeFiles/webpencode.dir/src/enc/alpha_enc.c.o
[11/56] Linking C static library libwebpdecoder.a
[12/56] Linking C executable webpinfo.exe
FAILED: webpinfo.exe
cmd.exe /C "cd . && F:\m-a-s\msys64\mingw32\bin\ccache.exe  gcc -mthreads -mtune=generic -O2 -pipe -DFREEGLUT_STATIC -pthread -O3 -DNDEBUG -pipe -static-libgcc -static-libstdc++ CMakeFiles/webpinfo.dir/examples/webpinfo.c.o -o webpinfo.exe -Wl,--out-implib,libwebpinfo.dll.a -Wl,--major-image-version,0,--minor-image-version,0  -lexampleutil  -limageioutil  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
F:/m-a-s/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lexampleutil
F:/m-a-s/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -limageioutil
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check F:/m-a-s/build/libwebp-git/build-32bit/ab-suite.build.log
This is required for other packages, so this script will exit.
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6641857/logs.zip)

**Comment by ASopH** [comment] 2021-06-12 09:12
and standalone 64bit fails too...
11:08:47   Running git clone for libwebp...
11:08:54 ┌ libwebp git  .............................. [Recently updated]
11:09:02 ├ Running cmake...
11:09:28 ├ Running build...
Likely error (tail of the failed operation logfile):
F:/m-a-s/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -limageioutil
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
[1/1] Linking C executable webpinfo.exe
FAILED: webpinfo.exe
cmd.exe /C "cd . && F:\m-a-s\msys64\mingw64\bin\ccache.exe  gcc -mthreads -mtune=generic -O2 -pipe -DFREEGLUT_STATIC -pthread -O3 -DNDEBUG -pipe -static-libgcc -static-libstdc++ CMakeFiles/webpinfo.dir/examples/webpinfo.c.o -o webpinfo.exe -Wl,--out-implib,libwebpinfo.dll.a -Wl,--major-image-version,0,--minor-image-version,0  -lexampleutil  -limageioutil  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
F:/m-a-s/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lexampleutil
F:/m-a-s/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -limageioutil
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6641926/logs.zip)

**Comment by ASopH** [comment] 2021-06-14 06:06
dpn' run...

08:02:36   Running git clone for libwebp...
08:02:42 ┌ libwebp git  .............................. [Recently updated]
08:02:52 ├ Running uninstall...
08:02:52 ├ Running cmake...
08:03:00 ├ Running build...
08:03:11 ├ Running install...
08:03:11 ├ /local64/lib/libwebpmux.a  ....................... [Not found]
08:03:11 └ libwebp-git  ........................................ [Failed]

Try deleting '/build/libwebp-git' and start the script again.
If you are sure there are no dependencies, <Enter> to continue building.
Close this window if you wish to stop building.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6645943/logs.zip)

**Comment by ASopH** [comment] 2021-06-14 07:58
Hi, I think you are on the right way :-)

09:53:15   Running git update for libwebp...
09:53:21 ┌ libwebp git  .............................. [Recently updated]
Failed to apply patch ''
Patch without filename, ignoring. Specify an explicit filename.
09:53:28 ├ Running uninstall...
09:53:28 ├ Running cmake...
09:53:37 ├ Running build...
09:53:49 ├ Running install...
09:53:50 ├ Stripping...
09:53:50 └ libwebp-git  ....................................... [Updated]

if you need logs, I sent them tomorrw

**Comment by topse** [comment] 2021-06-14 10:53
Works like charm now!! This project is really a life saver!!! Thanks guys and girls!

**Comment by MadameMinty** [comment] 2021-06-14 14:35
It throws a warning, but in the end compiles successfully:
![image](https://user-images.githubusercontent.com/24495074/121909213-002beb00-cd2e-11eb-8fd9-d7cd5c31bcfb.png)

**Comment by ASopH** [comment] 2021-06-15 10:27
Hi, I think it works now! It can be close if it works for all.
Thanks for fixing!

**Closed** 2021-06-15 17:06 UTC
