### ISSUE TITLE
cargo-c v0.6.1 will not install when trying to install rav1e on the latest build  of MAS

### ISSUE THREAD

**Issue by buhlaze** [m-ab-s/media-autobuild_suite#1586] opened 2020-03-23 05:37 UTC
cargo-c v0.6.1 will not install when trying to install rav1e on the latest build (Latest commit
6655f1e from 2 days ago), What can i do to fix this?

11:44:35   Running git update for rav1e...
11:44:36 ┌ rav1e git  ................................ [Recently updated]
11:44:36 ├ Running submodule...
11:44:37 ├ Running rust.update...
11:44:53 ├ Running rust.build...
11:48:16 ├ Running install-cargo-c...
Likely error (tail of the failed operation logfile):

error: aborting due to previous error

error: failed to compile `cargo-c v0.6.1`, intermediate artifacts can be found at `C:\Users\blayz\AppData\Local\Temp\cargo-installolhXhC`

Caused by:
  could not compile `cargo-c`.

To learn more, run the command again with --verbose.
install-cargo-c failed. Check C:/media-autobuild_suite/build/rav1e-git/ab-suite.install-cargo-c.log
This is required for other packages, so this script will exit.
11:55:36   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/iaOI.zip
Copy and paste [logs.zip](https://0x0.st/iaOI.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment] 2020-03-23 11:48
Fails on linking due to "ld: cannot find -lntdll". Not investigating it
atm, just as a followup.

**Comment by wiiaboo** [comment] 2020-03-23 15:34
Duplicate of #1585

**Comment by wiiaboo** [comment] 2020-03-23 19:51
This one has proper logs.

**Comment by wiiaboo** [comment] 2020-03-23 19:53
> 
> 
> But weird, I do have it in `/trunk/msys64/mingw64/x86_64-w64-mingw32/lib/libntdll.a`.
> And it's not owned by any package.

Nevermind, it's owned by mingw-w64-x86_64-crt-git

**Comment by wiiaboo** [comment] 2020-03-23 19:55
It's missing from `/opt/cargo/toolchains/stable-x86_64-pc-windows-gnu/lib/rustlib/x86_64-pc-windows-gnu/lib/` though.

**Comment by wiiaboo** [comment] 2020-03-23 20:14
@buhlaze @pat357 try with 126429b

**Comment by buhlaze** [comment] 2020-03-24 07:36
still cargo-c failed

**Comment by im1x** [comment] 2020-03-24 11:38
Yep, still not working for me too

**Comment by 1480c1** [comment] 2020-03-24 17:41
It seems to be an issue caused by rust's side.

**Comment by wiiaboo** [comment] 2020-03-24 18:16
Yeah, but it's wontfix. Their suggestion was using LIBRARY_PATH.
It might be fixed in non-stable versions since they try to use the system's
mingw if available.

**Comment by soulspark666** [comment] 2020-03-28 05:39
Same error on a newer build too
```
error: aborting due to previous error

error: failed to compile `cargo-c v0.6.2`, intermediate artifacts can be found at `C:\Users\anime\AppData\Local\Temp\cargo-installc4YbzU`

Caused by:
  could not compile `cargo-c`.
```

**Closed** 2020-04-03 02:35 UTC
Labels: bug, rav1e
