### ISSUE TITLE
jq build error

### ISSUE THREAD

**Issue by slyfox1186** [m-ab-s/media-autobuild_suite#1463] opened 2019-11-05 19:49 UTC
Compile failure. jq-git
https://0x0.st/zgWh.zip

```
14:50:39
        Starting 64bit compilation of all tools
Imported default FFmpeg options from .bat
License: nonfree
Imported default mpv options from .bat
14:50:46
        Starting 64bit compilation of global tools
14:50:46 oniguruma git  ................................. [Already built]
14:50:47   Running git update for jq...
14:50:47 ┌ jq git  ................................... [Recently updated]
14:50:47 ├ Running autoreconf...
Likely error (tail of the failed operation logfile):
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
autoreconf -fiv
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I config/m4
autoreconf: aclocal terminated by signal: 2
autom4te: /usr/bin/m4 terminated by signal: 2
autoreconf failed. Check C:/MAB/build/jq-git/ab-suite.autoreconf.log
This is required for other packages, so this script will exit.
14:50:51   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zg4X.zip
Copy and paste [logs.zip](https://0x0.st/zg4X.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

```

**Comment by 1480c1** [comment] 2019-11-05 20:25
```
C:/MAB/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./.libs/libjq.a(jv_print.o):jv_print.c:(.text+0x1721): undefined reference to `__strncpy_chk'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:965: jq.exe] Error 1
make[2]: Leaving directory '/build/jq-git/build-64bit'
make[1]: *** [Makefile:1161: all-recursive] Error 1
make[1]: Leaving directory '/build/jq-git/build-64bit'
make: *** [Makefile:792: all] Error 2
make  all-recursive
make[1]: Entering directory '/build/jq-git/build-64bit'
make[2]: Entering directory '/build/jq-git/build-64bit'
  CCLD     jq.exe
C:/MAB/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./.libs/libjq.a(jv_print.o):jv_print.c:(.text+0x1721): undefined reference to `__strncpy_chk'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:965: jq.exe] Error 1
make[2]: Leaving directory '/build/jq-git/build-64bit'
make[1]: *** [Makefile:1161: all-recursive] Error 1
make[1]: Leaving directory '/build/jq-git/build-64bit'
make: *** [Makefile:792: all] Error 2
```

Also related to FORTIFY_SOURCE stuff

**Comment by slyfox1186** [comment] 2019-11-06 00:35
While we are figuring this out you can download jq from this site `https://stedolan.github.io/jq/download/`

Place the downloaded exe file in your `\local64\bin-global` folder and rename it jq.exe

**Comment by wiiaboo** [comment] 2019-11-06 23:09
Why are you using a version of the suite from September?

**Comment by slyfox1186** [comment] 2019-11-06 23:58
I have since upgraded to the latest version and still have similar if not almost identical build failures.

**Comment by wiiaboo** [comment] 2019-11-07 22:45
Yeah, I didn't say that would fix the issue, just wanted to know if there was a special reason why you were using an older version, since that would've been a reason for closing the issue.

**Comment by wiiaboo** [comment] 2019-11-10 23:37
Can't reproduce this issue.

**Closed by wiiaboo** 2019-11-10 23:37 UTC
Labels: bug
