### ISSUE TITLE
vulkan-loader failed to build + patch could not be applied with 'git am'

### ISSUE THREAD

**Issue by Barough** [m-ab-s/media-autobuild_suite#2147] opened 2022-03-13 17:02 UTC
┌ vulkan-loader git  .................................. [Recently updated]
├ Running uninstall...
0001-loader-cross-compile-static-linking-hacks.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Running dependencies...
├ Installing Vulkan-Headers...
├ Running uninstall...
├ Running cmake...
├ Running build...
├ Running install...
├ Building Vulkan-Loader...
├ Running cmake...
├ Running build...
Likely error (tail of the failed operation logfile):
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:/MABS-ffmpeg/build/vulkan-loader-git/loader/vk_loader_platform.h:377:13: warning: 'loader_platform_file_exists' defined but not used [-Wunused-function]
  377 | static bool loader_platform_file_exists(const char *path) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
[4/20] Building RC object loader/CMakeFiles/vulkan.dir/loader.rc.obj
[5/20] Building ASM_MASM object loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
ml  -ID:/MABS-ffmpeg/build/vulkan-loader-git/build-32bit/loader -ID:/MABS-ffmpeg/local32/include  -c -Fo loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj D:/MABS-ffmpeg/build/vulkan-loader-git/loader/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.
build failed. Check D:/MABS-ffmpeg/build/vulkan-loader-git/build-32bit/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oZJH.zip
Copy and paste [logs.zip](https://0x0.st/oZJH.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by BlackScreen** [comment] 2022-03-16 15:09
Yes, same here.

**Comment by Biswa96** [comment] 2022-03-16 15:18
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2141

**Comment by 1480c1** [comment] 2022-03-17 21:54
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2141

**Closed by 1480c1** 2022-03-17 21:54 UTC
