### ISSUE TITLE
building mpv failed

### ISSUE THREAD

**Issue by ASopH** [m-ab-s/media-autobuild_suite#2098] opened 2022-01-06 14:48 UTC
15:17:53 ┌ mpv git  .................................. [Recently updated]
15:17:54 ├ Running bootstrap...
15:18:00 ├ Running configure...
15:18:14 ├ Running build...
Likely error (tail of the failed operation logfile):
F:/m-a-s/msys64/mingw32/i686-w64-mingw32/include/ksmedia.h:4449:58: error: redefinition of 'KSCATEGORY_ENCODER'
 4449 | DEFINE_GUIDSTRUCT("19689BF6-C384-48fd-AD51-90E58C79F70B",KSCATEGORY_ENCODER);
      |                                                          ^~~~~~~~~~~~~~~~~~
F:/m-a-s/msys64/mingw32/i686-w64-mingw32/include/ks.h:641:1: note: previous definition of 'KSCATEGORY_ENCODER' with type 'GUID'
  641 | DEFINE_GUIDSTRUCT("19689BF6-C384-48FD-AD51-90E58C79F70B",KSCATEGORY_ENCODER);
      | ^~~~~~~~~~~~~~~~~

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'objects' failed with exit status 1 (run with -v to display more information)
build failed. Check F:/m-a-s/build/mpv-git/ab-suite.build.log
This is required for other packages, so this script will exit.
15:18:46   Creating diagnostics file...

deleting mpv don' work
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/7822553/logs.zip)

**Comment by Biswa96** [comment] 2022-01-06 14:52
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2095

**Closed** 2022-01-08 03:46 UTC
