### ISSUE TITLE
[mingw32|mingw64] [repo] 64 bit static ffmpeg compilation failed on Windows 10

### ISSUE THREAD

**Issue by arnabanimesh** [m-ab-s/media-autobuild_suite#1863] opened 2020-11-21 06:27 UTC
``` bash
Likely error (tail of the failed operation logfile):
make: *** [/build/ffmpeg-git/Makefile:124: ffplay_g.exe] Error 1
make: *** [/build/ffmpeg-git/Makefile:124: ffprobe_g.exe] Error 1
LD      ffmpeg_g.exe
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/libSvtAv1Enc.a(palette.c.obj):palette.c:(.text+0x10): multiple definition of `av1_calc_indices_dim1_c'; C:/mabs/local64/lib/libaom.a(palette.c.o):palette.c:(.text+0x2cc0): first defined here
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/libSvtAv1Enc.a(palette.c.obj):palette.c:(.text+0x80): multiple definition of `av1_k_means_dim1_c'; C:/mabs/local64/lib/libaom.a(palette.c.o):palette.c:(.text+0x2d30): first defined here
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/libSvtAv1Enc.a(palette.c.obj):palette.c:(.text+0x4e0): multiple definition of `av1_calc_indices_dim2_c'; C:/mabs/local64/lib/libaom.a(palette.c.o):palette.c:(.text+0x2ef0): first defined here
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/libSvtAv1Enc.a(palette.c.obj):palette.c:(.text+0x570): multiple definition of `av1_k_means_dim2_c'; C:/mabs/local64/lib/libaom.a(palette.c.o):palette.c:(.text+0x2f80): first defined here
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/libSvtAv1Enc.a(palette_avx2.c.obj):palette_avx2.c:(.text+0x0): multiple definition of `av1_calc_indices_dim1_avx2'; C:/mabs/local64/lib/libaom.a(av1_k_means_avx2.c.o):av1_k_means_avx2.c:(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:124: ffmpeg_g.exe] Error 1
```

[logs.zip](https://0x0.st/i5CT.zip)

**Comment by 1480c1** [comment] 2020-11-21 22:41
Duplicate of #1862

**Closed by 1480c1** 2020-11-21 22:41 UTC
