### ISSUE TITLE
qtdeclarative seems to be broken

### ISSUE THREAD

**Issue by Fawaz816** [m-ab-s/media-autobuild_suite#1894] opened 2020-12-24 14:35 UTC
I'm trying to set up the thing and qtdeclarative keeps on erroring, I've tried updating it multiple times and also deleting the folder but nothing seems to work.
Here are the logs:
https://0x0.st/iCIA.zip

Traceback:
17:09:08 ┌ qtdeclarative git  ........................ [Recently updated]
17:09:09 ├ Running uninstall...
17:09:09 ├ Running qmake...
17:09:22 ├ Running install...
Likely error (tail of the failed operation logfile):
make[5]: Leaving directory '/build/qtdeclarative-git/src/plugins/scenegraph/d3d12'
make[4]: *** [Makefile:55: release-install] Error 2
make[4]: Leaving directory '/build/qtdeclarative-git/src/plugins/scenegraph/d3d12'
make[3]: *** [Makefile:62: sub-d3d12-install_subtargets] Error 2
make[3]: Leaving directory '/build/qtdeclarative-git/src/plugins/scenegraph'
make[2]: *** [Makefile:88: sub-scenegraph-install_subtargets] Error 2
make[2]: Leaving directory '/build/qtdeclarative-git/src/plugins'
make[1]: *** [Makefile:429: sub-plugins-install_subtargets-ordered] Error 2
make[1]: Leaving directory '/build/qtdeclarative-git/src'
make: *** [Makefile:65: sub-src-install_subtargets] Error 2

**Comment by wordlesswind** [comment] 2021-05-08 22:15
Duplicate of #1874

**Closed** 2021-06-06 04:58 UTC
