### ISSUE TITLE
GMP not found while building ffmpeg-git on Windows 10 Light build (64 bit)

### ISSUE THREAD

**Issue by ryankashi** [m-ab-s/media-autobuild_suite#2355] opened 2023-01-03 09:34 UTC
Hi everyone!

I ran into this issue earlier today while compiling FFMPEG. Specifically, while compiling ffmpeg-git, I have received the error:

`ERROR: gmp not found`

Other than that, everything during the build process seemed to work fine. Of course, this is a pretty big blocker regarding compilations.

I am building 64-bit and have chosen the recommended build settings. In addition, I chose the "Light" build regarding the ffmpeg packages included. I have attached the .zip as requested as well.

What can be done to solve this error so that I can compile FFMPEG?

Thanks!

``` bash
01:16:08 Warning: We will not accept any issues lacking any form of logs or logs.zip!
01:16:08
        Starting 64bit compilation of all tools
Imported default FFmpeg options from .bat
License: nonfree
Imported default mpv options from .bat
01:16:48
        Starting 64bit compilation of global tools
01:16:50
        Starting 64bit compilation of audio tools
01:16:59   Running git update for fdk-aac...
01:16:59 fdk-aac git  ...................................... [Up-to-date]
01:17:03   Running git update for opus...
01:17:03 opus git  ......................................... [Up-to-date]
01:17:03
        Starting 64bit compilation of video tools
01:17:09   Running git update for vpx...
01:17:09 vpx git  .......................................... [Up-to-date]
01:17:17   Running git update for aom...
01:17:18 aom git  .......................................... [Up-to-date]
01:17:23   Running git update for dav1d...
01:17:24 dav1d git  ........................................ [Up-to-date]
01:17:27   Running git update for SDL...
01:17:28 SDL git  .......................................... [Up-to-date]
01:17:32   Running git update for AMF...
01:17:32 AMF git  .......................................... [Up-to-date]
01:17:37   Running git update for x264...
01:17:38 x264 git  ......................................... [Up-to-date]
01:17:41   Running git update for x265_git...
01:17:42 x265_git git  ..................................... [Up-to-date]
01:17:46   Running git update for ffnvcodec...
01:17:46 ffnvcodec git  .................................... [Up-to-date]
01:17:48   Running git clone for ffmpeg...
01:19:16   Running git update for ffmpeg...
01:19:17 ┌ ffmpeg git  ............................... [Recently updated]
01:19:17 ├ Changing options to comply to nonfree...
01:19:20 ├ Compiling static FFmpeg...
01:19:22 ├ Running configure...
Likely error (tail of the failed operation logfile):
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config=pkgconf --pkg-config-flags=--keep-system-libs --keep-system-cflags --static --cc=ccache gcc --cxx=ccache g++ --ld=ccache g++ --extra-cxxflags=-fpermissive --extra-cflags=-Wno-int-conversion --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-schannel --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-gmp --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libaom --disable-debug --enable-libfdk-aac --extra-libs=-liconv --enable-gpl --enable-version3 --enable-nonfree --extra-version=gf0d2ed135c+1
ERROR: gmp not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
configure failed. Check C:/ffmpeg_installer_new/build/ffmpeg-git/build-static-64bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
01:21:39   Creating diagnostics file...

Attach C:\ffmpeg_installer_new\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.
```
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/10335471/logs.zip)

**Comment by 1480c1** [comment] 2023-01-03 18:58
Sounding like we need to compile our own gmp more and more. 

Probably near duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2352 as fixing one would fix the other, going to close and consolidate to that one

**Closed by 1480c1** 2023-01-03 18:58 UTC
