### ISSUE TITLE
[mingw64] [gpac] - undefined reference to `__imp_nghttp2_session_send'

### ISSUE THREAD

**Issue by imalkevich** [m-ab-s/media-autobuild_suite#1923] opened 2021-02-26 11:03 UTC
``` bash
11:59:57 ┌ gpac git  ................................. [Recently updated]
11:59:57 ├ Running configure...
12:00:40 ├ Running make...
Likely error (tail of the failed operation logfile):
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xdfef): undefined reference to `__imp_nghttp2_session_send'
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xdff6): undefined reference to `__imp_nghttp2_session_mem_recv'
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xe15c): undefined reference to `__imp_nghttp2_strerror'
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(downloader.o):downloader.c:(.text+0xe1d1): undefined reference to `__imp_nghttp2_strerror'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:56: gpac.exe] Error 1
make[2]: Leaving directory '/build/gpac-git/build-64bit/applications/gpac'
make[1]: *** [Makefile:41: apps] Error 2
make[1]: Leaving directory '/build/gpac-git/build-64bit/applications'
make: *** [Makefile:14: all] Error 2
make failed. Check C:/mabs/build/gpac-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
12:04:38   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-KTk.zip
Copy and paste [logs.zip](https://0x0.st/-KTk.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

[logs.zip](https://0x0.st/-KTk.zip)

**Comment by BlackScreen** [comment] 2021-02-26 13:02
See #1918

**Comment by 1480c1** [comment] 2021-02-26 22:18
Seems to be a duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/1918

**Closed by 1480c1** 2021-02-26 22:18 UTC
