### ISSUE TITLE
[mingw32|mingw64] [repo] Keeps failing at last ffmpeg build stage

### ISSUE THREAD

**Issue by Bassquake** [m-ab-s/media-autobuild_suite#1502] opened 2019-12-09 09:28 UTC
As title.

Trying to build 64bit of the ffmpeg, but it keeps failing at the ffmpeg build stage at the end.

```
├ Installing ladspa-sdk... done
  Running git clone for ffmpeg...
┌ ffmpeg git  ......................................... [Recently updated]
├ Until SVT-AV1 issues a fix, libsvtav1 must be disabled while libsvthevc is enabled....
├ Changing options to comply to nonfree...
├ Installing clang... done
FFmpeg and related apps will depend on CUDA SDK to run!
patch unexpectedly ends in middle of line
├ Compiling static FFmpeg...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
C:/MinGW_auto/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW_auto/msys64/mingw64/lib/libxml2.a(pathtools.o):(.text+0x6b0): multiple definition of `get_relocated_path'; C:/MinGW_auto/msys64/mingw64/lib/libcrypto.a(pathtools.o):(.text+0x7a0): first defined here
C:/MinGW_auto/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW_auto/msys64/mingw64/lib/libxml2.a(pathtools.o):(.text+0x6f0): multiple definition of `get_executable_path'; C:/MinGW_auto/msys64/mingw64/lib/libcrypto.a(pathtools.o):(.text+0x7e0): first defined here
C:/MinGW_auto/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW_auto/msys64/mingw64/lib/libxml2.a(pathtools.o):(.text+0x7c0): multiple definition of `strip_n_prefix_folders'; C:/MinGW_auto/msys64/mingw64/lib/libcrypto.a(pathtools.o):(.text+0x8b0): first defined here
C:/MinGW_auto/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW_auto/msys64/mingw64/lib/libxml2.a(pathtools.o):(.text+0x820): multiple definition of `strip_n_suffix_folders'; C:/MinGW_auto/msys64/mingw64/lib/libcrypto.a(pathtools.o):(.text+0x910): first defined here
C:/MinGW_auto/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW_auto/msys64/mingw64/lib/libxml2.a(pathtools.o):(.text+0x870): multiple definition of `split_path_list'; C:/MinGW_auto/msys64/mingw64/lib/libcrypto.a(pathtools.o):(.text+0x960): first defined here
C:/MinGW_auto/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW_auto/msys64/mingw64/lib/libxml2.a(pathtools.o):(.text+0x890): multiple definition of `get_relocated_path_list'; C:/MinGW_auto/msys64/mingw64/lib/libcrypto.a(pathtools.o):(.text+0x980): first defined here
C:/MinGW_auto/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW_auto/local64/lib/librav1e.a(compiler_builtins-477d6ada7584f678.compiler_builtins.1c0g4lf3-cgu.0.rcgu.o): in function `___chkstk_ms':
C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\compiler_builtins-0.1.18\src/x86_64.rs:15: multiple definition of `___chkstk_ms'; C:/MinGW_auto/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/libgcc.a(_chkstk_ms.o):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:114: ffmpeg_g.exe] Error 1
make failed. Check C:/MinGW_auto/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...
```

Theres a line that says "patch unexpectedly ends in middle of line" after cuda sdk but it doesnt say what file it is.

Log:
https://0x0.st/zl7C.zip

Have deleted all files and retried a few times for it to keep failing.

**Comment by 1480c1** [comment] 2019-12-09 12:17
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/1483
and duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/1479

**Closed by 1480c1** 2019-12-09 12:17 UTC
