### ISSUE TITLE
Request: new Fraunhofer HHI VVC codec instead of VTM test codec

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#1878] opened 2020-12-11 10:35 UTC
github: [vvenc](https://github.com/fraunhoferhhi/vvenc) + [vvdec](https://github.com/fraunhoferhhi/vvdec)

Jamaika published [patches](https://forum.doom9.org/showthread.php?p=1930419#post1930419) but I am not sure how persistent they will be. Invited him here.

**Comment by 1480c1** [comment] 2020-12-11 16:25
Duplicate of #1810

**Closed by 1480c1** 2020-12-11 16:25 UTC
