### ISSUE TITLE
librtmp: (ld) undefined reference to `_imp____gmpz_*'

### ISSUE THREAD

**Issue by LigH-de** [m-ab-s/media-autobuild_suite#2354] opened 2023-01-02 23:09 UTC
I erased all binaries to rebuild everything after a while...

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/10333711/logs.zip)

**build/librtmp-git/ab-suite.install.log**
```
...
ccache gcc -Wall -pipe -static-libgcc -static-libstdc++ -o rtmpdump.exe rtmpdump.o -Llibrtmp -lrtmp -LG:/MABS/local32/lib -lgnutls -lws2_32 -lws2_32 -lws2_32 -lgmp -latomic -ladvapi32 -lcrypt32 -lncrypt -lbcrypt -lcrypt32 -LG:/MABS/msys64/mingw32/lib -lnettle -lhogweed -lgmp -LG:/MABS/msys64/mingw32/lib -lnettle -ltasn1 -lz -lbrotlienc -LG:/MABS/msys64/mingw32/lib -lbrotlicommon -lbrotlidec -LG:/MABS/msys64/mingw32/lib -lbrotlicommon -lzstd  -lz -lws2_32 -lwinmm -lgdi32 
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0x4c2): undefined reference to `_imp____gmpz_init2'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0x4db): undefined reference to `_imp____gmpz_set_ui'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0x4e5): undefined reference to `_imp____gmpz_cmp'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0x4ff): undefined reference to `_imp____gmpz_set'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0x514): undefined reference to `_imp____gmpz_sub_ui'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0x546): undefined reference to `_imp____gmpz_powm'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0x557): undefined reference to `_imp____gmpz_cmp_ui'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0x569): undefined reference to `_imp____gmpz_clear'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0x643): undefined reference to `_imp____gmpz_init2'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0x656): undefined reference to `_imp____gmpz_sizeinbase'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0x6c8): undefined reference to `_imp____gmp_randinit_mt'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0x6d9): undefined reference to `_imp____gmp_randseed_ui'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0x6ed): undefined reference to `_imp____gmpz_urandomb'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0x6f6): undefined reference to `_imp____gmp_randclear'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0x74a): undefined reference to `_imp____gmpz_powm'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0x77e): undefined reference to `_imp____gmpz_set_str'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0x79b): undefined reference to `_imp____gmpz_clear'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0x7ea): undefined reference to `_imp____gmpz_clear'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0x848): undefined reference to `_imp____gmpz_clear'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0xbaa): undefined reference to `_imp____gmpz_sizeinbase'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0xc61): undefined reference to `_imp____gmpz_init2'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0xcae): undefined reference to `_imp____gmpz_set_str'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0xcc6): undefined reference to `_imp____gmpz_set_ui'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0xce4): undefined reference to `_imp____gmpz_clear'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0xd7d): undefined reference to `_imp____gmpz_init2'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0xdd4): undefined reference to `_imp____gmpz_set_str'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0xded): undefined reference to `_imp____gmpz_clear'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0xe5b): undefined reference to `_imp____gmpz_sizeinbase'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0xeba): undefined reference to `_imp____gmpz_powm'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0xedb): undefined reference to `_imp____gmpz_clear'
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: librtmp/librtmp.a(rtmp.o):rtmp.c:(.text+0x457b): undefined reference to `_imp____gmpz_clear'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:78: rtmpdump] Error 1
```

**Comment by Biswa96** [comment] 2023-01-03 04:09
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2352

**Comment by 1480c1** [comment] 2023-01-03 18:57
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2352

**Closed by 1480c1** 2023-01-03 18:57 UTC
