### ISSUE TITLE
64 bit, Error running make when updating shaderc – "ninja: build stopped: subcommand failed"

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#1665] opened 2020-05-19 19:57 UTC
``` bash
22:26:25   Running git update for shaderc...
22:26:30 ┌ shaderc git  ................................. [Updates found]
22:26:30 ├ Running uninstall...
22:26:30 ├ Running glslang-reset...
22:27:50 ├ Running glslang-pull...
22:28:02 ├ Running spirv-tools-reset...
22:28:53 ├ Running spirv-tools-pull...
22:29:00 ├ Running spirv-headers-reset...
22:29:04 ├ Running spirv-headers-pull...
22:29:06 ├ Running spirv-cross-reset...
22:30:10 ├ Running spirv-cross-pull...
22:30:17 ├ Running cmake...
22:30:31 ├ Running make...
Likely error (tail of the failed operation logfile):
../third_party/glslang/glslang/MachineIndependent/preprocessor/PpContext.h: In member function 'int glslang::TPpContext::TokenStream::Token::get(glslang::TPpToken&)':
../third_party/glslang/glslang/MachineIndependent/preprocessor/PpContext.h:265:17: error: 'snprintf' was not declared in this scope
  265 |                 snprintf(ppToken.name, sizeof(ppToken.name), "%s", name.c_str());
      |                 ^~~~~~~~
In file included from ../third_party/glslang/glslang/MachineIndependent/Scan.cpp:57:
../third_party/glslang/glslang/MachineIndependent/preprocessor/PpContext.h:88:1: note: 'snprintf' is defined in header '<cstdio>'; did you forget to '#include <cstdio>'?
   87 | #include "PpTokens.h"
  +++ |+#include <cstdio>
   88 |
ninja: build stopped: subcommand failed.
make failed. Check C:/MinGW64/build/shaderc-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
22:31:08   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/i9Ms.zip
Copy and paste [logs.zip](https://0x0.st/i9Ms.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

```

[logs.zip](https://0x0.st/i9Ms.zip)
[ab-suite.make.log](https://github.com/m-ab-s/media-autobuild_suite/files/4652787/ab-suite.make.log)

**Comment by 1480c1** [comment] 2020-05-19 20:08
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/1665

**Closed by 1480c1** 2020-05-19 20:08 UTC
