### ISSUE TITLE
Error running build when update mpv - cannot find -lC:/MinGW-w64/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#2016] opened 2021-07-24 00:35 UTC
``` bash
23:29:46   Running git update for mpv...
23:30:03 ┌ mpv git  ..................................... [Updates found]
23:30:05 ├ Running bootstrap...
23:30:11 ├ Running configure...
23:30:34 ├ Running build...
Likely error (tail of the failed operation logfile):
[439/488] Compiling video/filter/vf_d3d11vpp.c
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lC:/MinGW-w64/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lC:/MinGW-w64/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lC:/MinGW-w64/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lC:/MinGW-w64/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a
collect2.exe: error: ld returned 1 exit status

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
build failed. Check C:/MinGW-w64/build/mpv-git/ab-suite.build.log
This is required for other packages, so this script will exit.
23:31:48   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-VFK.zip
Copy and paste [logs.zip](https://0x0.st/-VFK.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

[logs.zip](https://0x0.st/-VFK.zip)
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/6871648/ab-suite.build.log)

**Comment by 1480c1** [comment] 2021-07-24 17:22
I don't think I've ever seen it complain about libstdc++

can you confirm the file `C:/MinGW-w64/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a` doesn't exist?

**Comment by snowbie** [comment] 2021-07-24 18:27
Same issue building with clang, latest MABS version.  

```
┌ mpv git  ............................................... [Updates found]
├ Running bootstrap...
├ Running configure...
├ Running build...
Likely error (tail of the failed operation logfile):
C:/mabs/msys64/mingw64/bin/ld: cannot find -lC:/mabs/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a
C:/mabs/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0\libstdc++.a(shared_ptr.o): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
C:/mabs/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0\libstdc++.a(shared_ptr.o): duplicate section `.rdata$_ZTSSt19_Sp_make_shared_tag[_ZTSSt19_Sp_make_shared_tag]' has different size
C:/mabs/msys64/mingw64/bin/ld: cannot find -lC:/mabs/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a
C:/mabs/msys64/mingw64/bin/ld: cannot find -lC:/mabs/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Waf: Leaving directory `/build/mpv-git/build'
Build failed
```
[logs.zip](https://0x0.st/-WXk.zip)
However, it appears the file **does** exist, so I don't understand why it's failing to build.

![20210724-142333186](https://user-images.githubusercontent.com/47767611/126877922-079ebf4d-0fa6-4e06-adcd-9455ad019d5b.png)

**Comment by ycwan** [comment] 2021-07-24 20:46
@1480c1
confirm the file C:/MinGW-w64/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a exist
![image](https://user-images.githubusercontent.com/33979551/126880718-c9cda3e9-d817-4611-998d-70f7dae061a2.png)

**Comment by githubReneFischer** [comment] 2021-07-26 16:52
File is in the above mentioned directory but there is an error raised that it cannot be found and the build of mpv fails:

 mpv git  ............................................ [Recently updated]
├ Running bootstrap...
├ Running configure...
├ Running build...
Likely error (tail of the failed operation logfile):
[347/488] Compiling player/osd.c
E:/APPS/MAS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lE:/APPS/MAS/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a
E:/APPS/MAS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lE:/APPS/MAS/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a
E:/APPS/MAS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lE:/APPS/MAS/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a
E:/APPS/MAS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lE:/APPS/MAS/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a
collect2.exe: error: ld returned 1 exit status

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)

**Comment by Ajaja** [comment] 2021-07-31 09:31
Any temporary solution?

**Comment by crhepner** [comment] 2021-08-03 21:31
I'm getting the same error with the current version of the media autobuild suite:

```bash
┌ mpv git  ............................................... [Updates found]
├ Running bootstrap...
├ Running configure...
├ Running build...
Likely error (tail of the failed operation logfile):
[316/488] Compiling input/event.c
C:/ab-suite-20120727/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lC:/ab-suite-20120727/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a
C:/ab-suite-20120727/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lC:/ab-suite-20120727/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a
C:/ab-suite-20120727/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lC:/ab-suite-20120727/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a
C:/ab-suite-20120727/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lC:/ab-suite-20120727/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a
collect2.exe: error: ld returned 1 exit status

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
build failed. Check C:/ab-suite-20120727/build/mpv-git/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-4eS.zip
Copy and paste [logs.zip](https://0x0.st/-4eS.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

[logs.zip](https://0x0.st/-4eS.zip)

**Comment by Jolar** [comment] 2021-08-04 11:05
Coming from a coding ignorant - could it be as simple that there's no blank space in between -l and the path? -lC:\ and not -l C:\ for example?

**Comment by seriousm4x** [comment] 2021-08-08 22:55
Same exact problem here. Looked in the mpv issues but couldn't find anything related.

**Comment by Ajaja** [comment] 2021-08-16 16:24
`--disable-vulkan` in `mpv_options.txt` helps.
Removing  `-l..msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a`  from `vulkan.pc`  works too.

**Comment by Weezzel** [comment] 2021-08-18 19:30
Getting MPV Error today after current Git Pull.


12:52:03   Running git update for mpv...
12:52:04 ┌ mpv git  ..................................... [Updates found]
12:52:05 ├ Running bootstrap...
12:52:09 ├ Running configure...
12:52:52 ├ Running build...
Likely error (tail of the failed operation logfile):
[250/250] Linking build/mpv.exe
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lC:/MABS/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lC:/MABS/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lC:/MABS/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lC:/MABS/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/10.3.0/libstdc++.a
collect2.exe: error: ld returned 1 exit status

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)

[logs.zip](https://0x0.st/-yfC.zip)

**Comment by 7e4** [comment] 2021-08-18 23:59
Vulkan references it. Remove reference from vulkan.pc and build goes fine.

Notepad X:\build\ab\local64\lib\pkgconfig\vulkan.pc
    Libs.private: -lmingwthrd -lmingw32 -lgcc -lmoldname -lmingwex -lkernel32 -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingwthrd -lmingw32 -lgcc -lmoldname -lmingwex -lkernel32 -lcfgmgr32

Rebuild.

(thanks @Ajaja )

**Comment by 7e4** [comment] 2021-08-19 01:07
Bit of a chickend and egg problem, I was rebuilding ffmpeg and ffmpeg/vulkan combo somehow needs it. so a workaround is to exclude vulkan from ffmpeg_options: as well. 

#--enable-vulkan

until the root cause is found.

**Comment by 1480c1** [comment] 2021-08-22 15:22
fixed on vulkan's pkg-config generation side, please try again

**Closed** 2021-08-24 16:00 UTC
Labels: bug

**Comment by ycwan** [comment] 2021-08-24 16:02
Deleted build/libtiff-git & rebuild completed successfully.
