### ISSUE TITLE
64 bit, Error when running build and install when updating vvc – "ninja: build stopped: subcommand failed"

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#1666] opened 2020-05-19 20:29 UTC
``` bash
04:16:04 ┌ vvc git  .................................. [Recently updated]
04:16:08 ├ Running cmake...
04:16:11 ├ Running build...
Likely error (tail of the failed operation logfile):
../source/Lib/CommonLib/UnitTools.cpp:1268:58: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
 1268 |       mrgCtx.interDirNeighbours [ uiArrayAddr          ] = 3;
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
In file included from ../source/Lib/CommonLib/UnitTools.h:43,
                 from ../source/Lib/CommonLib/UnitTools.cpp:38:
../source/Lib/CommonLib/ContextModelling.h:451:17: note: at offset 6 to object 'MergeCtx::interDirNeighbours' with size 6 declared here
  451 |   unsigned char interDirNeighbours[ MRG_MAX_NUM_CANDS      ];
      |                 ^~~~~~~~~~~~~~~~~~
cc1plus.exe: all warnings being treated as errors
ninja: build stopped: subcommand failed.
build failed. Check C:/MinGW64/build/vvc-git/build-64bit/ab-suite.build.log
This isn't required for anything so we can move on.
04:16:39 ├ Running install...
Likely error (tail of the failed operation logfile):
../source/Lib/CommonLib/UnitTools.cpp:1268:58: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
 1268 |       mrgCtx.interDirNeighbours [ uiArrayAddr          ] = 3;
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
In file included from ../source/Lib/CommonLib/UnitTools.h:43,
                 from ../source/Lib/CommonLib/UnitTools.cpp:38:
../source/Lib/CommonLib/ContextModelling.h:451:17: note: at offset 6 to object 'MergeCtx::interDirNeighbours' with size 6 declared here
  451 |   unsigned char interDirNeighbours[ MRG_MAX_NUM_CANDS      ];
      |                 ^~~~~~~~~~~~~~~~~~
cc1plus.exe: all warnings being treated as errors
ninja: build stopped: subcommand failed.
install failed. Check C:/MinGW64/build/vvc-git/build-64bit/ab-suite.install.log
This isn't required for anything so we can move on.

```

[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/4652939/ab-suite.build.log)

**Comment by 1480c1** [comment] 2020-05-19 20:29
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/1663

**Closed by 1480c1** 2020-05-19 20:29 UTC
