### ISSUE TITLE
Error while building/installing rav1e [64-bit]

### ISSUE THREAD

**Issue by KarimElSheikh** [m-ab-s/media-autobuild_suite#2266] opened 2022-08-14 17:13 UTC
I get an error when the autobuild gets to the installing rav1e-c part.

From compile.log:
``` bash
  error occurred: Command "ccache" "gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m32" "-mthreads" "-mtune=generic" "-O2" "-pipe" "-I" "src/zlib" "-o" "F:\\build_suite\\build\\rav1e-git\\target\\release\\build\\libz-sys-ec8988e7122cebb6\\out\\lib\\src/zlib/adler32.o" "-c" "src/zlib/adler32.c" with args "gcc" did not execute successfully (status code exit code: 1).


warning: build failed, waiting for other jobs to finish...
Error: CliError { error: Some(1 job failed), exit_code: 101 }
rav1e-c failed. Check F:/build_suite/build/rav1e-git/ab-suite.install-rav1e-c.log
This is required for other packages, so this script will exit.
   Creating diagnostics file...
```
[compile.log](https://github.com/m-ab-s/media-autobuild_suite/files/9333789/compile.log)
[logs.zip](https://0x0.st/o2Ye.zip)

**Comment by 1480c1** [comment] 2022-08-15 05:10
trying to fix this issue but found another

**Comment by kliffgomel** [comment] 2022-08-15 10:40
13:32:35 ├ Running rust.build...
Likely error (tail of the failed operation logfile):
          C:/ffmpeg-autobuild/msys64/opt/cargo\registry\src\github.com-1ecc6299db9ec823\console-0.15.1\src/utils.rs:(.text+0x76): undefined reference to `__imp__ZN7console5utils13STDOUT_COLORS17h17545f2ff6571861E'
          C:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg-autobuild/msys64/opt/cargo\registry\src\github.com-1ecc6299db9ec823\console-0.15.1\src/utils.rs:(.text+0x7f): undefined reference to `__imp__ZN7console5utils13STDERR_COLORS17h136e5b4a10a47f8dE'
          C:/ffmpeg-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/ffmpeg-autobuild/msys64/opt/cargo\registry\src\github.com-1ecc6299db9ec823\console-0.15.1\src/utils.rs:(.text+0x94): undefined reference to `__imp__ZN7console5utils13STDERR_COLORS17h136e5b4a10a47f8dE'
          collect2.exe: error: ld returned 1 exit status

  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `rav1e` due to previous error


[logs.zip](https://0x0.st/o2lN.zip)

**Comment by waldonnis** [comment] 2022-08-18 19:32
I haven't tested the resulting binaries/libs, but rav1e builds and links fine for me using either the `release-no-lto` profile or simply changing the `release` profile's `lto` to false in Cargo.toml.  Doing so has implications, obviously, but I would think that any potential benefits from even-more-limited (local-crate-only) lto would be better than just disabling it entirely like `release-no-lto` does (assuming lto is beneficial at all for this case; I never bothered checking it myself).

Locally, I patched the main release profile in Cargo.toml to allow a build to complete, but if maintaining yet another patch for a likely-temporary issue isn't preferred (understandable) and you don't want to use the release-no-lto profile, you can alternatively use the `CARGO_PROFILE_RELEASE_LTO` environment variable to override the lto config in the main `release` profile until the lto issues get sorted out (way) upstream (doing so works; it was the first thing I tried but decided a local rav1e patch was easier for me to deal with going forward compared to hacking that into media-suite_compile.sh).

Side note: Changing or disabling lto seems to remove the need to lock crossbeam to an older revision, as it built/linked okay after I reverted that particular patch locally (I was curious if this addressed that issue too since it seemed to have the same symptoms), so...bonus.

_Reminder: I have not tested the resulting libs/bins, so someone should validate that they work properly before just adopting this idea.  I'm also not thrilled with just altering this over the long term, as this seems like an lto regression that should be fixed upstream.  I'm just not familiar enough with rust/cargo to know to whom or where the issue would best be reported._

**Comment by 1480c1** [comment] 2022-08-18 20:52
`83b8206b40 rav1e: set profile to release-no-lto` I currently have a commit in the works for that, however, my main issue right now is the capi for use with FFmpeg since it keeps on failing to build. I guess I can take this one at a time and first just go ahead and get rav1e.exe building in master

**Comment by 1480c1** [comment] 2022-08-18 20:55
pushed the commits

**Comment by Barough** [comment] 2022-08-19 10:08
rav1e builds now :)

**Comment by Barough** [comment] 2022-08-19 14:35
Ran a ffmpeg mabs setup and there so didn't rav1e wanna compile

┌ rav1e git  ............................................. [Updates found]
├ Running rust.update...
├ Running rust.build...
├ Running install-rav1e-c...
Likely error (tail of the failed operation logfile):
  exit code: 1

  --- stderr


  error occurred: Command "ccache" "gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m32" "-mthreads" "-mtune=generic" "-O2" "-pipe" "-I" "src/zlib" "-o" "D:\\MABS-ffmpeg\\build\\rav1e-git\\target\\release\\build\\libz-sys-6d80d6f5b931b953\\out\\lib\\src/zlib/adler32.o" "-c" "src/zlib/adler32.c" with args "gcc" did not execute successfully (status code exit code: 1).


warning: build failed, waiting for other jobs to finish...
Error: CliError { error: Some(1 job failed), exit_code: 101 }
install-rav1e-c failed. Check D:/MABS-ffmpeg/build/rav1e-git/ab-suite.install-rav1e-c.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oLgu.zip
Copy and paste [logs.zip](https://0x0.st/oLgu.zip) in the GitHub issue.

**Comment by ASopH** [comment] 2022-08-19 14:36
hi, 
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/9382986/logs.zip)

same here with 32bit

**Comment by fspezi** [comment] 2022-08-24 08:10
Same issue for me.

So, i removed it by request of installation:

open "build/media-autobuild_suite.ini"
change "rav1e=1" row to "rav1e=2"
re-run "media-autobuild_suite.bat"
But the installation break in the same point.

### This is the error message:

```log
        Starting 64bit compilation of video tools
10:10:27   Running git update for vpx...
10:10:27 vpx git  .......................................... [Up-to-date]
10:10:36   Running git update for aom...
10:10:37 aom git  .......................................... [Up-to-date]
10:10:41   Running git update for dav1d...
10:10:42 dav1d git  ........................................ [Up-to-date]
10:10:45   Running git update for cargo-c...
10:10:46 cargo-c git  ...................................... [Up-to-date]
10:10:50   Running git update for rav1e...
10:10:54 ┌ rav1e git  ................................ [Recently updated]
10:11:03 ├ Running rust.update...
10:11:04 ├ Running rust.build...
Likely error (tail of the failed operation logfile):
          D:/Apps/ffmpeg/media-autobuild_suite-master/msys64/opt/cargo\registry\src\github.com-1ecc6299db9ec823\console-0.15.1\src/utils.rs:(.text+0x76): undefined reference to `__imp__ZN7console5utils13STDOUT_COLORS17hcce10a805ac03887E'
          D:/Apps/ffmpeg/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Apps/ffmpeg/media-autobuild_suite-master/msys64/opt/cargo\registry\src\github.com-1ecc6299db9ec823\console-0.15.1\src/utils.rs:(.text+0x7f): undefined reference to `__imp__ZN7console5utils13STDERR_COLORS17h431a34178b191106E'
          D:/Apps/ffmpeg/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/Apps/ffmpeg/media-autobuild_suite-master/msys64/opt/cargo\registry\src\github.com-1ecc6299db9ec823\console-0.15.1\src/utils.rs:(.text+0x94): undefined reference to `__imp__ZN7console5utils13STDERR_COLORS17h431a34178b191106E'
          collect2.exe: error: ld returned 1 exit status

  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `rav1e` due to previous error
rust.build failed. Check D:/Apps/ffmpeg/media-autobuild_suite-master/build/rav1e-git/ab-suite.rust.build.log
This is required for other packages, so this script will exit.
10:14:00   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oLxZ.zip
Copy and paste [logs.zip](https://0x0.st/oLxZ.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

This is my LOG file: [oLxi.zip](https://github.com/m-ab-s/media-autobuild_suite/files/9414146/oLxi.zip)

This is the LOG of RAV1E: [ab-suite.rust.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/9414161/ab-suite.rust.build.log)

**Comment by LigH-de** [comment] 2022-08-25 07:29
Regression?

```
  cargo-warning=Could not run `"G:/MABS/msys64/mingw32/bin/pkgconf --keep-system-libs --keep-system-cflags --static" "--libs" "--cflags" "zlib"`
  The pkg-config command could not be found.
```

See https://github.com/m-ab-s/media-autobuild_suite/issues/2207#issuecomment-1148928065

[ab-suite.install-rav1e-c.log](https://github.com/m-ab-s/media-autobuild_suite/files/9422437/ab-suite.install-rav1e-c.log)

**Comment by Selur** [comment] 2022-08-26 16:03
32bit fails htere too
[logs.zip](https://0x0.st/o9ko.zip)

**Comment by Barough** [comment] 2022-08-27 01:05
rav1e builds fine now on my mabs ffmpeg setup after the latest 2 added commits. 
both x86 & x64

┌ rav1e git  ............................................. [Updates found]
├ Running rust.update...
├ Running rust.build...
├ Running install-rav1e-c...
├ Stripping...
└ rav1e-git  ................................................... [Updated]

**Comment by 1480c1** [comment] 2022-09-07 02:46
"Fix" for now is to just compile using clang

https://github.com/m-ab-s/media-autobuild_suite/commit/d71222116f8eb56afcecc8602d48f39bdf2c7c90

**Closed by 1480c1** 2022-09-07 02:46 UTC

**Comment by hamwong** [comment] 2024-08-21 07:09
I get a new fault, and even though I chose not to compile (rav1e=2), I still got the below error. I fix it by running "cargo install cargo-c" in MinGW, the media-autobuild_suite script downloaded yesterday in a fresh environment.
`CPPFLAGS: 
CFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -mthreads
CXXFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1
LDFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -static-libgcc -static-libstdc++
cargo capi install --release --jobs 6 --prefix=/local64 --destdir=/build/rav1e-git/install-64bit
error: no such command: `capi`

	Did you mean `add`?

	View all installed commands with `cargo --list`
	Find a package to install `capi` with `cargo search cargo-capi``

**Comment by LigH-de** [comment] 2024-08-21 07:41
Different reason - new issue, please.
