### ISSUE TITLE
[mingw64] libxvid conflicts with libsvt_av1

### ISSUE THREAD

**Issue by nistvan86** [m-ab-s/media-autobuild_suite#1521] opened 2020-01-05 00:53 UTC
I get the following error in ffmpeg's make log output when trying to build a 64 bit ffmpeg where both Xvid and SVT-AV1 is enabled:

	C:/tmp/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/tmp/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbFullLoop.c.obj): warning: definition of `allowed_tx_set_a' overriding common from C:/tmp/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbProductCodingLoop.c.obj)
	C:/tmp/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/tmp/media-autobuild_suite/local64/lib/libxvidcore.a(mbcoding.obj):mbcoding.c:(.text+0x4110): multiple definition of `get_mv'; C:/tmp/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbInitialRateControlProcess.c.obj):EbInitialRateControlProcess.c:(.text+0x790): first defined here
	collect2.exe: error: ld returned 1 exit status
	make: *** [/build/ffmpeg-git/Makefile:114: ffmpeg_g.exe] Error 1

Applying the following git patch makes the build continue, but of course no support for Xvid in the resulting ffmpeg:

	diff --git a/build/media-suite_compile.sh b/build/media-suite_compile.sh
	index 7e442f0..42389a3 100644
	--- a/build/media-suite_compile.sh
	+++ b/build/media-suite_compile.sh
	@@ -1822,6 +1822,11 @@ if [[ $ffmpeg != "no" ]]; then
			 # See issue https://github.com/OpenVisualCloud/SVT-AV1/issues/567 for the reasons behind the follow codeblock:
			 # start of SVT-AV1 temporary measures
			 if enabled libsvtav1; then
	+			if enabled libxvid; then
	+				do_print_progress "libxvid conflicts with SVT-AV1 so removing for now."
	+				do_removeOption --enable-libxvid
	+			fi
	+
				 if enabled libaom && enabled libopencore-amrwb; then
					 do_print_progress "Until SVT-AV1 issues a fix, libaom & libopencore-amrwb must be disabled while libsvtav1 is enabled."
					 do_removeOption --enable-libaom

My full log:
[logs.zip](https://0x0.st/znuz.zip)

**Comment by 1480c1** [comment] 2020-01-05 01:28
OpenVisualCloud/SVT-AV1#935

Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/1520

**Closed by 1480c1** 2020-01-05 01:28 UTC
