### ISSUE TITLE
FAILED: libshaderc_util/CMakeFiles/shaderc_util.dir/src/compiler.cc.o 

### ISSUE THREAD

**Issue by ZhuxiaopinpCN** [m-ab-s/media-autobuild_suite#1599] opened 2020-04-03 07:29 UTC
FAILED: libshaderc_util/CMakeFiles/shaderc_util.dir/src/compiler.cc.o 
C:\media-autobuild_suite\msys64\mingw32\bin\ccache.exe  g++  -DENABLE_HLSL -I../libshaderc_util/include -I../third_party/glslang -I../third_party/glslang/glslang/.. -I../third_party/glslang/SPIRV/.. -I../third_party/glslang/SPIRV/../External -I../third_party/spirv-tools/include -I../third_party/spirv-headers/include -mthreads -mtune=generic -O2 -pipe -Wimplicit-fallthrough -O3 -DNDEBUG   -Wextra-semi -Wall -Werror -fvisibility=hidden -std=c++11 -std=gnu++11 -MD -MT libshaderc_util/CMakeFiles/shaderc_util.dir/src/compiler.cc.o -MF libshaderc_util\CMakeFiles\shaderc_util.dir\src\compiler.cc.o.d -o libshaderc_util/CMakeFiles/shaderc_util.dir/src/compiler.cc.o -c ../libshaderc_util/src/compiler.cc
In file included from ../third_party/glslang/SPIRV/SpvTools.h:49,
                 from ../third_party/glslang/SPIRV/GlslangToSpv.h:42,
                 from ../libshaderc_util/src/compiler.cc:22:
../third_party/glslang/glslang/MachineIndependent/localintermediate.h:230:62: error: extra ';' after in-class function definition [-Werror=extra-semi]
  230 |     TMap<TString, int>& operator[](int i) { return maps[i]; };
      |                                                              ^
      |                                                              -
../third_party/glslang/glslang/MachineIndependent/localintermediate.h:231:74: error: extra ';' after in-class function definition [-Werror=extra-semi]
  231 |     const TMap<TString, int>& operator[](int i) const { return maps[i]; };
      |                                                                          ^
https://0x0.st/iusV.zip

**Comment by 1480c1** [comment] 2020-04-03 15:38
Repull

Duplicate of #1598

**Closed by 1480c1** 2020-04-03 15:38 UTC
