### ISSUE TITLE
Build worked a few days ago, now fails, even when starting afresh [mingw32|mingw64] [repo]

### ISSUE THREAD

**Issue by jonathancolledge** [m-ab-s/media-autobuild_suite#1996] opened 2021-06-10 15:08 UTC
Here is the last bit of what it says:

ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
├ Compiling static FFmpeg...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
CC      libavfilter/vf_thumbnail_cuda.ptx.o
CC      libavfilter/vf_yadif_cuda.ptx.o
AR      libavfilter/libavfilter.a
CC      libavcodec/libsvt_hevc.o
F:/mabs/build/ffmpeg-git/libavcodec/libsvt_hevc.c: In function 'eb_encode_frame':
F:/mabs/build/ffmpeg-git/libavcodec/libsvt_hevc.c:426:14: error: implicit declaration of function 'ff_alloc_packet2' [-Werror=implicit-function-declaration]
  426 |     av_ret = ff_alloc_packet2(avctx, pkt, header_ptr->nFilledLen, 0);
      |              ^~~~~~~~~~~~~~~~
cc1.exe: some warnings being treated as errors
make: *** [/build/ffmpeg-git/ffbuild/common.mak:67: libavcodec/libsvt_hevc.o] Error 1
make failed. Check F:/mabs/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-LPj.zip
Copy and paste [logs.zip](https://0x0.st/-LPj.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

This is for a 64 bit build.

``` bash
Paste output of the suite here
```
I've copied the above here too:
ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
├ Compiling static FFmpeg...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
CC      libavfilter/vf_thumbnail_cuda.ptx.o
CC      libavfilter/vf_yadif_cuda.ptx.o
AR      libavfilter/libavfilter.a
CC      libavcodec/libsvt_hevc.o
F:/mabs/build/ffmpeg-git/libavcodec/libsvt_hevc.c: In function 'eb_encode_frame':
F:/mabs/build/ffmpeg-git/libavcodec/libsvt_hevc.c:426:14: error: implicit declaration of function 'ff_alloc_packet2' [-Werror=implicit-function-declaration]
  426 |     av_ret = ff_alloc_packet2(avctx, pkt, header_ptr->nFilledLen, 0);
      |              ^~~~~~~~~~~~~~~~
cc1.exe: some warnings being treated as errors
make: *** [/build/ffmpeg-git/ffbuild/common.mak:67: libavcodec/libsvt_hevc.o] Error 1
make failed. Check F:/mabs/build/ffmpeg-git/build-static-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-LPj.zip
Copy and paste [logs.zip](https://0x0.st/-LPj.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite)

**Comment by Biswa96** [comment] 2021-06-10 15:16
Duplicate of this issue https://github.com/m-ab-s/media-autobuild_suite/issues/1993

**Comment by 1480c1** [comment] 2021-06-10 16:30
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/1993

**Closed by 1480c1** 2021-06-10 16:30 UTC
