### ISSUE TITLE
Error running build when update aom – (ivfdec: replace uses of warn with fprintf(stderr))

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#2036] opened 2021-08-31 05:47 UTC
``` bash
13:35:53 vmaf git  ......................................... [Up-to-date]
13:36:12   Running git update for aom...
13:36:22 ┌ aom git  ..................................... [Updates found]
13:36:26 ├ Running uninstall...
13:36:27 ├ Running cmake...
13:36:43 ├ Running build...
Likely error (tail of the failed operation logfile):
C:/MinGW-w64/build/aom-git/common/ivfdec.c:115:1: error: version control conflict marker in file
  115 | =======
      | ^~~~~~~
C:/MinGW-w64/build/aom-git/common/ivfdec.c:117:1: error: version control conflict marker in file
  117 | >>>>>>> 2dbdf19b1 (ivfdec: replace uses of warn with fprintf(stderr))
      | ^~~~~~~
C:/MinGW-w64/build/aom-git/common/ivfdec.c:117:9: error: invalid suffix "dbdf19b1" on integer constant
  117 | >>>>>>> 2dbdf19b1 (ivfdec: replace uses of warn with fprintf(stderr))
      |         ^~~~~~~~~
ninja: build stopped: subcommand failed.
build failed. Check C:/MinGW-w64/build/aom-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
13:36:46   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-vHc.zip
Copy and paste [logs.zip](https://0x0.st/-vHc.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

[logs.zip](https://0x0.st/-vHc.zip)
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/7081508/ab-suite.build.log)

**Comment by Biswa96** [comment] 2021-08-31 05:58
Duplicate of this fixed issue https://github.com/m-ab-s/media-autobuild_suite/issues/2034

**Comment by Biswa96** [comment] 2021-08-31 05:59
Does this https://github.com/m-ab-s/media-autobuild_suite/issues/2034 fixes your issue?

**Comment by ycwan** [comment] 2021-08-31 06:39
@Biswa96 
I have checked. The fix is already in my build/media-suite_compile.sh

![aom_cherry-pick warn related patch](https://user-images.githubusercontent.com/33979551/131454261-9c569ba6-5bbd-4c55-b4ba-064931ea2b77.jpg)

**Comment by FXJunkie** [comment] 2021-08-31 10:51
Same exact issue when trying to compile ffmpeg. Any help appreciated.

**Comment by magnusoverli** [comment] 2021-08-31 10:52
+1

```
12:38:06   Running git update for aom...
12:38:07 ┌ aom git  .................................. [Recently updated]
12:38:10 ├ Running cmake...
12:38:47 ├ Running build...
Likely error (tail of the failed operation logfile):
C:/media-autobuild_suite-master/build/aom-git/common/ivfdec.c:115:1: error: version control conflict marker in file
  115 | =======
      | ^~~~~~~
C:/media-autobuild_suite-master/build/aom-git/common/ivfdec.c:117:1: error: version control conflict marker in file
  117 | >>>>>>> 2dbdf19b1 (ivfdec: replace uses of warn with fprintf(stderr))
      | ^~~~~~~
C:/media-autobuild_suite-master/build/aom-git/common/ivfdec.c:117:9: error: invalid suffix "dbdf19b1" on integer constant
  117 | >>>>>>> 2dbdf19b1 (ivfdec: replace uses of warn with fprintf(stderr))
      |         ^~~~~~~~~
ninja: build stopped: subcommand failed.
build failed. Check C:/media-autobuild_suite-master/build/aom-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
12:39:28   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-vXU.zip
```

**Comment by 1480c1** [comment] 2021-08-31 12:04
removed merged patch, try again https://github.com/m-ab-s/media-autobuild_suite/commit/b5a08779e5ad4b728d67b2e4940b12e7e53b0937

**Comment by magnusoverli** [comment] 2021-08-31 15:13
Still failing for me...
```
17:09:55   Running git clone for aom...
17:10:37 ┌ aom git  .................................. [Recently updated]
17:10:42 ├ Running cmake...
17:11:19 ├ Running build...
Likely error (tail of the failed operation logfile):
C:/media-autobuild_suite-master/build/aom-git/common/ivfdec.c:115:1: error: version control conflict marker in file
  115 | =======
      | ^~~~~~~
C:/media-autobuild_suite-master/build/aom-git/common/ivfdec.c:117:1: error: version control conflict marker in file
  117 | >>>>>>> 2dbdf19b1 (ivfdec: replace uses of warn with fprintf(stderr))
      | ^~~~~~~
C:/media-autobuild_suite-master/build/aom-git/common/ivfdec.c:117:9: error: invalid suffix "dbdf19b1" on integer constant
  117 | >>>>>>> 2dbdf19b1 (ivfdec: replace uses of warn with fprintf(stderr))
      |         ^~~~~~~~~
ninja: build stopped: subcommand failed.
build failed. Check C:/media-autobuild_suite-master/build/aom-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
17:12:04   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-vPA.zip
Copy and paste [logs.zip](https://0x0.st/-vPA.zip) in the GitHub issue.
```
[-vPA.zip](https://github.com/m-ab-s/media-autobuild_suite/files/7084978/-vPA.zip)

**Comment by ycwan** [comment] 2021-08-31 17:27
@1480c1  Removing merged patch caused issue #2033 to recur

01:09:43   Running git update for mpv...
01:10:02 ┌ mpv git  ..................................... [Updates found]
01:10:04 ├ Running bootstrap...
01:10:11 ├ Running configure...
01:10:31 ├ Running build...
Likely error (tail of the failed operation logfile):
[143/490] Compiling osdep/path-win.c
[144/490] Compiling player/loadfile.c
../demux/demux_lavf.c: In function 'update_read_stats':
../demux/demux_lavf.c:273:31: error: 'AVIOContext' has no member named 'bytes_read'
  273 |         int64_t cur = nest->id->bytes_read;
      |                               ^~

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'objects' failed with exit status 1 (run with -v to display more information)
build failed. Check C:/MinGW-w64/build/mpv-git/ab-suite.build.log
This is required for other packages, so this script will exit.
01:10:58   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-vZA.zip
Copy and paste [logs.zip](https://0x0.st/-vZA.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

[logs.zip](https://0x0.st/-vZA.zip)
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/7085736/ab-suite.build.log)

**Comment by 1480c1** [comment] 2021-08-31 17:31
You need to add `--enable-ffmpeg-strict-abi` to your mpv_options.txt

**Comment by FXJunkie** [comment] 2021-08-31 20:14
Keeping what was already there, I just copied over the four '\build' files as well as the main .bat from the newly extracted version into my current installation's relevant folders and when running the .bat file again the error disappeared, aom-git finished and ffmpeg compiled successfully without any errors.

**Closed** 2021-09-04 04:52 UTC
