### ISSUE TITLE
64 bit, Error after mujs-git  .......... [Updated] –git.reset failed

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#1772] opened 2020-07-27 21:05 UTC
``` bash
03:04:43 ├ Compiling mpv with Vapoursynth R50
03:04:43 ├ mpv will need vapoursynth.dll and vsscript.dll to use vapoursynth filter!
03:04:49   Running git update for mujs...
03:04:52 ┌ mujs git  .................................... [Updates found]
03:04:53 ├ Running uninstall...
03:04:53 ├ Running clean...
03:04:53 ├ Running make...
03:04:58 ├ Stripping...
03:04:58 └ mujs-git  .......................................... [Updated]
warning: ignoring dangling symref refs/remotes/origin/HEAD
fatal: Not a valid object name origin/HEAD
03:05:02   Running git update for shaderc...
Likely error (tail of the failed operation logfile):
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
vcs_reset origin/HEAD
++ vcs_get_latest_tag origin/HEAD
++ case $1 in
++ false
++ echo origin/HEAD
+ git checkout --no-track -fB ab-suite origin/HEAD
warning: ignoring dangling symref refs/remotes/origin/HEAD
fatal: 'origin/HEAD' is not a commit and a branch 'ab-suite' cannot be created from it
git.reset failed. Check C:/MinGW64/build/shaderc-git/ab-suite.git.reset.log
This is required for other packages, so this script will exit.
03:05:02   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/ixiO.zip
Copy and paste [logs.zip](https://0x0.st/ixiO.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.


```

[logs.zip](https://0x0.st/ixiO.zip)
[ab-suite.git.reset.log](https://github.com/m-ab-s/media-autobuild_suite/files/4984364/ab-suite.git.reset.log)

**Comment by 1480c1** [comment] 2020-07-27 21:58
you need to delete build/shaderc-git and rerun, they changed their default branch from master to main causing this issue

**Comment by 1480c1** [comment] 2020-07-27 21:58
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/1733

**Closed by 1480c1** 2020-07-27 21:58 UTC
