### ISSUE TITLE
can't build  mpv-git

### ISSUE THREAD

**Issue by dxdvostfr** [m-ab-s/media-autobuild_suite#2097] opened 2022-01-02 15:22 UTC
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/7799275/logs.zip)

**Comment by Biswa96** [comment] 2022-01-02 15:32
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2095

**Closed** 2022-01-03 18:56 UTC
