### ISSUE TITLE
error: too many arguments to function 'JxlDecoderGetColorAsEncodedProfile'

### ISSUE THREAD

**Issue by CuplexUser** [m-ab-s/media-autobuild_suite#2468] opened 2023-06-23 17:09 UTC
I get a compile error on ffmpeg:

J:/media-autobuild_suite/local64/include/jxl/decode.h:723:50: note: expected 'JxlColorProfileTarget' but argument is of type 'JxlPixelFormat *'
  723 |     const JxlDecoder* dec, JxlColorProfileTarget target,
      |                            ~~~~~~~~~~~~~~~~~~~~~~^~~~~~
src/libavcodec/libjxldec.c:261:20: error: too many arguments to function 'JxlDecoderGetColorAsEncodedProfile'
  261 |             jret = JxlDecoderGetColorAsEncodedProfile(ctx->decoder, &ctx->jxl_pixfmt, JXL_COLOR_PROFILE_TARGET_DATA, &jxl_color);
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
J:/media-autobuild_suite/local64/include/jxl/decode.h:722:29: note: declared here
  722 | JXL_EXPORT JxlDecoderStatus JxlDecoderGetColorAsEncodedProfile(

Logs attached
[logs.zip](https://1drv.ms/u/s!AqSmnyNivIRtidgzY_QICO2SJFu1RQ?e=Xlzu2G)

**Comment by Biswa96** [comment] 2023-06-23 17:37
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2466

**Comment by CuplexUser** [comment] 2023-06-23 17:48
@Biswa96 
Yes I noticed that too after submitting the Issue. 
Builds perfectly now without any problems after updating ffmpeg_options.txt with:
#--enable-libjxl

**Closed** 2023-06-23 17:49 UTC
