### ISSUE TITLE
mingw64 MinGW64 GCC compiler isn't installed; maybe the download didn't work Do you want to try it again?

### ISSUE THREAD

**Issue by Motophan** [m-ab-s/media-autobuild_suite#1864] opened 2020-11-22 22:10 UTC
![image](https://user-images.githubusercontent.com/42502676/99918491-bd3bf480-2cc3-11eb-97dc-4088accf8b80.png)
I just need to compile w/ libfdaac regular ffmpeg so I selected no to most things. I dont know much about programming. Is there anything I can do to get this compiled?
[pacman.log](https://github.com/m-ab-s/media-autobuild_suite/files/5580453/pacman.log)

[firstrun.log](https://github.com/m-ab-s/media-autobuild_suite/files/5580454/firstrun.log)
[firstUpdate.log](https://github.com/m-ab-s/media-autobuild_suite/files/5580455/firstUpdate.log)
[mingw64.log](https://github.com/m-ab-s/media-autobuild_suite/files/5580456/mingw64.log)
[secondUpdate.log](https://github.com/m-ab-s/media-autobuild_suite/files/5580458/secondUpdate.log)

**Comment by spechacek** [comment] 2020-11-24 22:43
Just close the console window and go into task manager and stop any of the processes (if any) that started with that session.

Then run media-autobuild_suite.bat again, it should go through (at least it does for me, even after a fresh repo pull).

**Comment by voltagex** [comment] 2020-12-01 12:13
for whatever reason this doesn't seem to work correctly from Windows Terminal. Double clicking the .bat file directly worked.

**Comment by 1480c1** [comment] 2020-12-01 19:45
@Motophan you might want to try using the noMintty option, this can be achieved post suite configure by editing the build/media-suite_helper.ini file and changing the noMintty=0 line to noMintty=1 or answering 1 to the `Are you running this script through ssh or similar?` question

**Comment by denixx** [comment] 2020-12-21 17:16
> Just close the console window and go into task manager and stop any of the processes (if any) that started with that session.
> 
> Then run media-autobuild_suite.bat again, it should go through (at least it does for me, even after a fresh repo pull).

I could confirm, just closed the console and rebooted for sanity. Then double-clicked media-autobuild_suite.bat, and it continued the process.

**Comment by voltagex** [comment] 2021-01-02 09:52
There's also a bug where entering `y` at `try again [y/n]: y` doesn't cause a retry.

**Comment by voltagex** [comment] 2021-01-02 09:56
Hit this again on a clean install / new checkout right now

```
-------------------------------------------------------------------------------
install msys2 base system
-------------------------------------------------------------------------------
/usr/bin/bash: line 1: /build/pacman.sh: No such file or directory
-------------------------------------------------------------------------------
install 64 bit compiler
-------------------------------------------------------------------------------
/usr/bin/bash: line 1: /build/mingw.sh: No such file or directory
-------------------------------------------------------------------------------

MinGW64 GCC compiler isn't installed; maybe the download didn't work
Do you want to try it again?

-------------------------------------------------------------------------------
try again [y/n]:
```

@1480c1 noMinTty=1 doesn't fix this for me

**Comment by voltagex** [comment] 2021-01-02 10:09
Windows Terminal was a red herring, it seems like this is an issue with choosing a 64 bit only build system

**Comment by deseipel** [comment] 2021-01-04 20:11
I did not double click on first try, I ran it from a command prompt and got the error.  Upon rerun, this time double clicking the .bat, its installing the base system, which it didn't before.  I'll reply with updates  (BTW first post on github, I think)

**Comment by ScribbleGhost** [comment] 2021-01-10 12:14
I am also having this problem. Closing the window and running `media-autobuild_suite.bat` seems to resume the script. Though I have no idea if this affects anything else.

**Comment by malco7m** [comment] 2021-01-15 13:17
I am also experiencing this failure with a 64 bit build under Windows 10.

I have no expertise using MinGW, Powershell or with this build system, so please exercise some latitude interpreting the terminology I use here.

The issue seems to be that the build directory lives outside the MinGW root environment.

I seem to have the build system running now by changing the `build` environment variable in the top level `media-autobuild_suite.bat` script to:

    set build=%instdir%\msys64\build

This line

    call :runBash mingw%1.log /build/mingw.sh
 
 seems to require `/build` to be under the MinGW root.  Should there be some sort of symlink from `%instdir%\build` to `%instdir%\msys64\build` which isn't being created for some reason?  A quick review of the script didn't reveal to me where that should be occuring / why it isn't.

**Comment by 1480c1** [comment] 2021-01-15 16:49
the `/build`, `/local64`, and `/local32` folders are supposed to be handled by `msys64/etc/fstab`, however, it seems it's not always being read or triggered

**Comment by malco7m** [comment] 2021-01-15 17:07
> the `/build`, `/local64`, and `/local32` folders are supposed to be handled by `msys64/etc/fstab`, however, it seems it's not always being read or triggered

That's great info, thanks... my script hack didn't allow the script to progress completely so this is a good lead 👍

**Comment by Selur** [comment] 2021-02-16 20:00
I got this for 32bit and 64bit, for me it helped to delete 
media-autobuild_suite/msys64/mingw32/lib/libonig.dll.a
and
media-autobuild_suite/msys64/mingw64/lib/libonig.dll.a

**Comment by voltagex** [comment] 2021-04-19 13:37
Bump. Still hitting this with a 64 bit build.

**Comment by Selur** [comment] 2021-04-19 13:38
did you try deleting the files I mentioned?

**Comment by voltagex** [comment] 2021-04-19 13:40
@Selur those files don't exist for me.

**Comment by Motophan** [comment] 2021-04-19 23:23
Is there any alternative software that works

**Comment by 1480c1** [comment] 2021-04-19 23:24
If you have wsl, you could try https://github.com/rdp/ffmpeg-windows-build-helpers

**Comment by 1480c1** [comment] 2021-06-22 02:44
Still unsure what is the cause, but I am not sure if I can help solve this either way

**Closed by 1480c1** 2021-06-22 02:44 UTC
