### ISSUE TITLE
ERROR: libbluray not found using pkg-config

### ISSUE THREAD

**Issue by b1aqW0lf** [m-ab-s/media-autobuild_suite#2524] opened 2023-10-01 14:02 UTC
I cannot build FFMPEG. I used the latest build suite, and tried this morning. It failed with error: ERROR: libbluray not found using pkg-config.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/12777326/logs.zip)

**Comment by mrtajniak** [comment] 2023-10-03 17:01
Same problem for me

**Comment by hydra3333** [comment] 2023-10-03 23:56
Not 100% sure it is libbluray given a config log shows this error when linking with libxml2:
```
require_pkg_config libbluray libbluray libbluray/bluray.h bd_open
check_pkg_config libbluray libbluray libbluray/bluray.h bd_open
test_pkg_config libbluray libbluray libbluray/bluray.h bd_open
pkgconf --exists --print-errors libbluray
check_func_headers libbluray/bluray.h bd_open -IC:/MABS/local64/include -IC:/MABS/msys64/mingw64/include -IC:/MABS/local64/include/libxml2 -DLIBXML_STATIC -LC:/MABS/local64/lib -lbluray -LC:/MABS/msys64/mingw64/lib -llzma -lz -LC:/MABS/local64/lib -lxml2 -liconv -lm -lws2_32
test_ld cc -IC:/MABS/local64/include -IC:/MABS/msys64/mingw64/include -IC:/MABS/local64/include/libxml2 -DLIBXML_STATIC -LC:/MABS/local64/lib -lbluray -LC:/MABS/msys64/mingw64/lib -llzma -lz -LC:/MABS/local64/lib -lxml2 -liconv -lm -lws2_32
test_cc -IC:/MABS/local64/include -IC:/MABS/msys64/mingw64/include -IC:/MABS/local64/include/libxml2 -DLIBXML_STATIC -LC:/MABS/local64/lib -LC:/MABS/msys64/mingw64/lib -LC:/MABS/local64/lib
BEGIN /tmp/ffconf.Cfxv2VhN/test.c
    1	#include <libbluray/bluray.h>
    2	#include <stdint.h>
    3	long check_bd_open(void) { return (long) bd_open; }
    4	int main(void) { int ret = 0;
    5	 ret |= ((intptr_t)check_bd_open) & 0xFFFF;
    6	return ret; }
END /tmp/ffconf.Cfxv2VhN/test.c
ccache gcc -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DWIN32_LEAN_AND_MEAN -U__STRICT_ANSI__ -D__USE_MINGW_ANSI_STDIO=1 -D__printf__=__gnu_printf__ -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DPIC -fstack-protector-strong -mtune=generic -O2 -pipe -mthreads -IC:/MABS/local64/include -Wno-int-conversion -DLIBTWOLAME_STATIC -DCACA_STATIC -DMODPLUG_STATIC -DCHROMAPRINT_NODLL -DZMQ_STATIC -DLIBXML_STATIC -DAL_LIBTYPE_STATIC -IC:/MABS/local64/include -IC:/MABS/local64/include/AL -std=c11 -fomit-frame-pointer -IC:/MABS/local64/include -pthread -IC:/MABS/msys64/mingw64/include -I/mingw64/include -IC:/MABS/local64/include -IC:/MABS/msys64/mingw64/include -IC:/MABS/local64/include -IC:/MABS/local64/include -IC:/MABS/local64/include/libpng16 -IC:/MABS/msys64/mingw64/include -IC:/MABS/local64/include -IC:/MABS/msys64/mingw64/include -IC:/MABS/local64/include/harfbuzz -IC:/MABS/local64/include/fribidi -DFRIBIDI_LIB_STATIC -IC:/MABS/local64/include/freetype2 -IC:/MABS/local64/include -IC:/MABS/msys64/mingw64/include -IC:/MABS/local64/include/libxml2 -DLIBXML_STATIC -LC:/MABS/local64/lib -LC:/MABS/msys64/mingw64/lib -LC:/MABS/local64/lib -c -o /tmp/ffconf.Cfxv2VhN/test.o /tmp/ffconf.Cfxv2VhN/test.c
C:/MABS/msys64/tmp/ffconf.Cfxv2VhN/test.c: In function 'check_bd_open':
C:/MABS/msys64/tmp/ffconf.Cfxv2VhN/test.c:3:35: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    3 | long check_bd_open(void) { return (long) bd_open; }
      |                                   ^
ccache g++ -pipe -static-libgcc -fstack-protector-strong -static-libstdc++ -IC:/MABS/local64/include -LC:/MABS/local64/lib -lfdk-aac -L/local64/lib -L/mingw64/lib -Wl,--nxcompat,--dynamicbase -Wl,--high-entropy-va -Wl,--as-needed -Wl,--pic-executable,-e,mainCRTStartup -Wl,--image-base,0x140000000 -IC:/MABS/local64/include -IC:/MABS/msys64/mingw64/include -IC:/MABS/local64/include/libxml2 -DLIBXML_STATIC -LC:/MABS/local64/lib -LC:/MABS/msys64/mingw64/lib -LC:/MABS/local64/lib -o /tmp/ffconf.Cfxv2VhN/test.exe /tmp/ffconf.Cfxv2VhN/test.o -lbluray -llzma -lz -lxml2 -liconv -lm -lws2_32 -liconv -lpsapi -lstdc++ -lstdc++
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xmlIO.c.o):xmlIO.c:(.text+0x5ab): undefined reference to `gzdopen'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xmlIO.c.o):xmlIO.c:(.text+0x5ec): undefined reference to `gzopen'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xmlIO.c.o):xmlIO.c:(.text+0x698): undefined reference to `gzdopen'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xmlIO.c.o):xmlIO.c:(.text+0x787): undefined reference to `deflateInit2_'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xmlIO.c.o):xmlIO.c:(.text+0x79d): undefined reference to `crc32'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xmlIO.c.o):xmlIO.c:(.text+0x853): undefined reference to `deflateEnd'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xmlIO.c.o):xmlIO.c:(.text+0x8f0): undefined reference to `deflateEnd'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xmlIO.c.o):xmlIO.c:(.text+0xf85): undefined reference to `gzclose'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xmlIO.c.o):xmlIO.c:(.text+0xfb5): undefined reference to `gzread'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xmlIO.c.o):xmlIO.c:(.text+0x1165): undefined reference to `gzwrite'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xmlIO.c.o):xmlIO.c:(.text+0x1978): undefined reference to `gzdopen'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xmlIO.c.o):xmlIO.c:(.text+0x19d7): undefined reference to `gzopen'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xmlIO.c.o):xmlIO.c:(.text+0x1a58): undefined reference to `gzdopen'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xmlIO.c.o):xmlIO.c:(.text+0x2762): undefined reference to `gzdirect'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xmlIO.c.o):xmlIO.c:(.text+0x3959): undefined reference to `deflate'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xmlIO.c.o):xmlIO.c:(.text+0x3974): undefined reference to `crc32'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xmlIO.c.o):xmlIO.c:(.text+0x4106): undefined reference to `deflateEnd'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xmlIO.c.o):xmlIO.c:(.text+0x4645): undefined reference to `gzclose'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xmlIO.c.o):xmlIO.c:(.text+0x4791): undefined reference to `deflate'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xzlib.c.o):xzlib.c:(.text+0x5e6): undefined reference to `lzma_code'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xzlib.c.o):xzlib.c:(.text+0x685): undefined reference to `inflate'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xzlib.c.o):xzlib.c:(.text+0x7ac): undefined reference to `crc32'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xzlib.c.o):xzlib.c:(.text+0x82a): undefined reference to `crc32'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xzlib.c.o):xzlib.c:(.text+0xa24): undefined reference to `lzma_auto_decoder'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xzlib.c.o):xzlib.c:(.text+0xab0): undefined reference to `lzma_properties_decode'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xzlib.c.o):xzlib.c:(.text+0xbaa): undefined reference to `inflateInit2_'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xzlib.c.o):xzlib.c:(.text+0xf58): undefined reference to `inflateReset'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xzlib.c.o):xzlib.c:(.text+0xf64): undefined reference to `crc32'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xzlib.c.o):xzlib.c:(.text+0x1785): undefined reference to `lzma_end'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(xzlib.c.o):xzlib.c:(.text+0x17c8): undefined reference to `inflateEnd'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(nanohttp.c.o):nanohttp.c:(.text+0xad): undefined reference to `inflateEnd'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(nanohttp.c.o):nanohttp.c:(.text+0x1033): undefined reference to `inflate'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libxml2.a(nanohttp.c.o):nanohttp.c:(.text+0x1ebf): undefined reference to `inflateInit2_'
collect2.exe: error: ld returned 1 exit status
ERROR: libbluray not found using pkg-config
```

**Comment by hydra3333** [comment] 2023-10-04 00:30
Ah. Of interest, I note in another build system, this has been in place for some time:

`sed -i.bak \'s/-lbluray.*$/-lbluray -lfreetype -lexpat -lz -lbz2 -lxml2 -lws2_32 -lgdi32 -liconv -laacs/\' "{pkg_config_path}/libbluray.pc"`

I wonder if parts of that could be of use here ?

**Comment by Selur** [comment] 2023-10-04 03:59
same (ERROR: libbluray not found using pkg-config) here
[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/12799090/logs.zip)

**Comment by hydra3333** [comment] 2023-10-04 05:21
Found a different build system's "hack" to fix a few things, including libavif which failed for me.
Had to disable vulkan, libplacebo, glslang in the interim though.
Pending a successful build, hope to generate a pull today, with a comment in the description on how to do the disables.
At least nvenc and whatnot appear build, which is what I care about most.

Bear in mind I'm a dummy. 
I don't know how/why it built in the past, no doubt the author and other good people will do much better patches and whatnot, so  the pull will be just a few hacks which worked for me.

Perhaps I'll see how vulkan is done in other build systems and attempt a kludged pull, unless people a lot smarter than me do a pull first.

**Comment by mrtajniak** [comment] 2023-10-04 07:09
There is a patch for vulkan. I have disabled libbluray now I am facing another problem "nvenc requested but not found" #2522

**Comment by hydra3333** [comment] 2023-10-04 09:02
> This project is a mess
Well ... no.
From a dumb user (me), I've almost a working build with just a few tweaks (ex vulkan/placebo/glslang ATM).
It's rebuilding right now (hopefully working this time) however that takes m quite a while on a 2010 i5 vintage laptop.

**Comment by b1aqW0lf** [comment] 2023-10-08 13:55
I ran MABS using the current (988b408 commit) version, and was able to build ffmpeg.  I also deleted the libbluray dlls and re-ran MABS. It re-created the libbluray dlls and rebuilt ffmpeg. I guess we need someone else to confirm that MABS is now building the libbluray for them.

**Comment by Selur** [comment] 2023-10-08 14:30
Worked fine for me too

**Comment by hydra3333** [comment] 2023-10-08 20:40
good for you !
it failed fo me:
```
BEGIN /tmp/ffconf.p8FyKWdW/test.c
    1	#include <libplacebo/vulkan.h>
    2	#include <stdint.h>
    3	long check_pl_vulkan_create(void) { return (long) pl_vulkan_create; }
    4	int main(void) { int ret = 0;
    5	 ret |= ((intptr_t)check_pl_vulkan_create) & 0xFFFF;
    6	return ret; }
END /tmp/ffconf.p8FyKWdW/test.c
ccache gcc -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DWIN32_LEAN_AND_MEAN -U__STRICT_ANSI__ -D__USE_MINGW_ANSI_STDIO=1 -D__printf__=__gnu_printf__ -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DPIC -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -mthreads -IC:/MABS/local64/include -Wno-int-conversion -DLIBTWOLAME_STATIC -DCACA_STATIC -DMODPLUG_STATIC -DCHROMAPRINT_NODLL -DZMQ_STATIC -DLIBXML_STATIC -DAL_LIBTYPE_STATIC -IC:/MABS/local64/include -IC:/MABS/local64/include/AL -std=c11 -fomit-frame-pointer -IC:/MABS/local64/include -pthread -IC:/MABS/msys64/mingw64/include -I/mingw64/include -IC:/MABS/local64/include -IC:/MABS/msys64/mingw64/include -IC:/MABS/local64/include -IC:/MABS/local64/include -IC:/MABS/local64/include/libpng16 -IC:/MABS/msys64/mingw64/include -IC:/MABS/local64/include -IC:/MABS/msys64/mingw64/include -IC:/MABS/local64/include/harfbuzz -IC:/MABS/local64/include/fribidi -DFRIBIDI_LIB_STATIC -IC:/MABS/local64/include/freetype2 -IC:/MABS/local64/include -IC:/MABS/local64/include/libxml2 -DLIBXML_STATIC -IC:/MABS/msys64/mingw64/include -IC:/MABS/local64/include/bs2b -IC:/MABS/msys64/mingw64/include -IC:/MABS/local64/include -IC:/MABS/local64/include -IC:/MABS/local64/include -IC:/MABS/local64/include -IC:/MABS/local64/include/freetype2 -IC:/MABS/msys64/mingw64/include -IC:/MABS/local64/include/freetype2 -IC:/MABS/local64/include/fribidi -DFRIBIDI_LIB_STATIC -IC:/MABS/local64/include -IC:/MABS/local64/include -IC:/MABS/msys64/mingw64/include -DHWY_STATIC_DEFINE -DJXL_STATIC_DEFINE -IC:/MABS/local64/include -DJXL_THREADS_STATIC_DEFINE -IC:/MABS/local64/include -IC:/MABS/local64/include/mfx -IC:/MABS/msys64/mingw64/include -IC:/MABS/local64/include -IC:/MABS/msys64/mingw64/include/openjpeg-2.5 -DOPJ_STATIC -IC:/MABS/local64/include -IC:/MABS/local64/include/opus -IC:/MABS/local64/include/opus -IC:/MABS/local64/include -DPL_STATIC -IC:/MABS/local64/include/spirv_cross -IC:/MABS/msys64/mingw64/include -LC:/MABS/local64/lib C:/MABS/local64/lib/../lib/libSPIRV.a C:/MABS/local64/lib/../lib/libMachineIndependent.a C:/MABS/local64/lib/../lib/libOSDependent.a C:/MABS/local64/lib/../lib/libOGLCompiler.a C:/MABS/local64/lib/../lib/libGenericCodeGen.a C:/MABS/local64/lib/../lib/libSPIRV-Tools.a C:/MABS/local64/lib/../lib/libSPIRV-Tools-opt.a -Llib -LC:/MABS/msys64/mingw64/lib -pthread -c -o /tmp/ffconf.p8FyKWdW/test.o /tmp/ffconf.p8FyKWdW/test.c
C:/MABS/msys64/tmp/ffconf.p8FyKWdW/test.c: In function 'check_pl_vulkan_create':
C:/MABS/msys64/tmp/ffconf.p8FyKWdW/test.c:3:44: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    3 | long check_pl_vulkan_create(void) { return (long) pl_vulkan_create; }
      |                                            ^
gcc.exe: warning: C:/MABS/local64/lib/../lib/libSPIRV.a: linker input file unused because linking not done
gcc.exe: warning: C:/MABS/local64/lib/../lib/libMachineIndependent.a: linker input file unused because linking not done
gcc.exe: warning: C:/MABS/local64/lib/../lib/libOSDependent.a: linker input file unused because linking not done
gcc.exe: warning: C:/MABS/local64/lib/../lib/libOGLCompiler.a: linker input file unused because linking not done
gcc.exe: warning: C:/MABS/local64/lib/../lib/libGenericCodeGen.a: linker input file unused because linking not done
gcc.exe: warning: C:/MABS/local64/lib/../lib/libSPIRV-Tools.a: linker input file unused because linking not done
gcc.exe: warning: C:/MABS/local64/lib/../lib/libSPIRV-Tools-opt.a: linker input file unused because linking not done
ccache g++ -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -mthreads -static-libgcc -static-libstdc++ -IC:/MABS/local64/include -LC:/MABS/local64/lib -lfdk-aac -L/local64/lib -L/mingw64/lib -Wl,--nxcompat,--dynamicbase -Wl,--high-entropy-va -Wl,--as-needed -Wl,--pic-executable,-e,mainCRTStartup -Wl,--image-base,0x140000000 -IC:/MABS/local64/include -DPL_STATIC -IC:/MABS/local64/include/spirv_cross -IC:/MABS/msys64/mingw64/include -LC:/MABS/local64/lib C:/MABS/local64/lib/../lib/libSPIRV.a C:/MABS/local64/lib/../lib/libMachineIndependent.a C:/MABS/local64/lib/../lib/libOSDependent.a C:/MABS/local64/lib/../lib/libOGLCompiler.a C:/MABS/local64/lib/../lib/libGenericCodeGen.a C:/MABS/local64/lib/../lib/libSPIRV-Tools.a C:/MABS/local64/lib/../lib/libSPIRV-Tools-opt.a -Llib -LC:/MABS/msys64/mingw64/lib -pthread -o /tmp/ffconf.p8FyKWdW/test.exe /tmp/ffconf.p8FyKWdW/test.o -lplacebo -lm -lshlwapi -lglslang-default-resource-limits -lversion -lspirv-cross -lvulkan -lcfgmgr32 -llcms2 -llcms2_fast_float -lm -ldovi -lkernel32 -ladvapi32 -lbcrypt -lkernel32 -lntdll -luserenv -lws2_32 -lkernel32 -lws2_32 -lkernel32 -liconv -lpsapi -lstdc++ -lstdc++
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libplacebo.a(glsl_glslang.cc.obj):glslang.cc:(.text+0x41): undefined reference to `glslang::InitializeProcess()'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libplacebo.a(glsl_glslang.cc.obj):glslang.cc:(.text+0x81): undefined reference to `glslang::FinalizeProcess()'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libplacebo.a(glsl_glslang.cc.obj):glslang.cc:(.text+0x119): undefined reference to `glslang::TShader::TShader(EShLanguage)'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libplacebo.a(glsl_glslang.cc.obj):glslang.cc:(.text+0x158): undefined reference to `glslang::TShader::setStrings(char const* const*, int)'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libplacebo.a(glsl_glslang.cc.obj):glslang.cc:(.text+0x1df): undefined reference to `glslang::TShader::parse(TBuiltInResource const*, int, EProfile, bool, bool, EShMessages, glslang::TShader::Includer&)'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libplacebo.a(glsl_glslang.cc.obj):glslang.cc:(.text+0x1fc): undefined reference to `glslang::TProgram::TProgram()'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libplacebo.a(glsl_glslang.cc.obj):glslang.cc:(.text+0x231): undefined reference to `glslang::TProgram::link(EShMessages)'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libplacebo.a(glsl_glslang.cc.obj):glslang.cc:(.text+0x274): undefined reference to `glslang::GlslangToSpv(glslang::TIntermediate const&, std::vector<unsigned int, std::allocator<unsigned int> >&, glslang::SpvOptions*)'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libplacebo.a(glsl_glslang.cc.obj):glslang.cc:(.text+0x2f4): undefined reference to `glslang::TProgram::getInfoLog()'
C:/MABS/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MABS/local64/lib/libplacebo.a(glsl_glslang.cc.obj):glslang.cc:(.text+0x324): undefined reference to `glslang::TShader::getInfoLog()'
collect2.exe: error: ld returned 1 exit status
ERROR: libplacebo >= 4.192.0 not found using pkg-config
```

**Comment by hydra3333** [comment] 2023-10-08 20:43
I suppose success could depend on what options one selects. Here's mine:
[ffmpeg_options.txt](https://github.com/m-ab-s/media-autobuild_suite/files/12841718/ffmpeg_options.txt)
[media-autobuild_suite.ini.txt](https://github.com/m-ab-s/media-autobuild_suite/files/12841720/media-autobuild_suite.ini.txt)

**Comment by hydra3333** [comment] 2023-10-10 08:16
OK, here's mine which works. I had to use --disable-libplacebo.
[media-autobuild_suite.ini.txt](https://github.com/m-ab-s/media-autobuild_suite/files/12854513/media-autobuild_suite.ini.txt)
[ffmpeg_options.txt](https://github.com/m-ab-s/media-autobuild_suite/files/12854514/ffmpeg_options.txt)

**Comment by 1480c1** [comment] 2024-03-05 16:33
Cannot reproduce using the original ini file, possibly fixed in the meantime

**Closed by 1480c1** 2024-03-05 16:33 UTC
