### ISSUE TITLE
libplacebo build error, from clean [mingw64] [repo]

### ISSUE THREAD

**Issue by Hunterswood** [m-ab-s/media-autobuild_suite#1949] opened 2021-03-25 10:07 UTC
┌ libplacebo git  ..................................... [Recently updated]
├ Installing python-mako... done
├ Running meson...
├ Running build...
Likely error (tail of the failed operation logfile):
D:/MAB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/MAB_Suite/local64/lib/../lib/libshaderc_combined.a(validate_memory_semantics.cpp.o):validate_memory_semantics.cpp:(.text+0xd8a): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long long)'
D:/MAB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/MAB_Suite/local64/lib/../lib/libshaderc_combined.a(validate_memory_semantics.cpp.o):validate_memory_semantics.cpp:(.text+0xde9): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long long)'
D:/MAB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/MAB_Suite/local64/lib/../lib/libshaderc_combined.a(validate_memory_semantics.cpp.o):validate_memory_semantics.cpp:(.text+0xe0c): undefined reference to `std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
D:/MAB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/MAB_Suite/local64/lib/../lib/libshaderc_combined.a(validate_memory_semantics.cpp.o):validate_memory_semantics.cpp:(.text+0xe28): undefined reference to `std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
D:/MAB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/MAB_Suite/local64/lib/../lib/libshaderc_combined.a(validate_memory_semantics.cpp.o):validate_memory_semantics.cpp:(.text+0xe3c): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
D:/MAB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/MAB_Suite/local64/lib/../lib/libshaderc_combined.a(validate_memory_semantics.cpp.o):validate_memory_semantics.cpp:(.text+0xe53): undefined reference to `std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
D:/MAB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/MAB_Suite/local64/lib/../lib/libshaderc_combined.a(validate_memory_semantics.cpp.o):validate_memory_semantics.cpp:(.text+0x2d): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long long)'
D:/MAB_Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/MAB_Suite/local64/lib/../lib/libshaderc_combined.a(validate_memory_semantics.cpp.o):validate_memory_semantics.cpp:(.text+0x51): undefined reference to `std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check D:/MAB_Suite/build/libplacebo-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

[logs.zip](https://0x0.st/-qt-.zip)

**Comment by LigH-de** [comment] 2021-03-26 23:46
Duplicate of issue #1944 ?

**Closed** 2021-03-31 01:13 UTC
