### ISSUE TITLE
[mingw64] [sox git]

### ISSUE THREAD

**Issue by lopes143** [m-ab-s/media-autobuild_suite#2724] opened 2024-06-20 16:56 UTC
``` bash
17:48:50 Warning: We will not accept any issues lacking any form of logs or logs.zip!
17:48:50
        Starting 64bit compilation of all tools
Imported options from ffmpeg_options.txt
License: nonfree
Imported options from mpv_options.txt
17:49:06
        Starting 64bit compilation of global tools
17:49:08 libxml2 git  ................................... [Already built]
17:49:09 libpng git  .................................... [Already built]
17:49:09 aribb24 git  ................................... [Already built]
17:49:18 ├ Uninstalling freetype... failed
17:49:21 ├ Uninstalling fontconfig... failed
17:49:24 ├ Uninstalling harfbuzz... failed
17:49:27 ├ Uninstalling fribidi... failed
17:49:31 freetype git  .................................. [Already built]
17:49:31 fontconfig git  ................................ [Already built]
17:49:31 harfbuzz git  .................................. [Already built]
17:49:31 fribidi git  ................................... [Already built]
17:49:32 libass git  .................................... [Already built]
17:49:35 gnutls 3.8.5  ..................................... [Up-to-date]
17:49:41 libidn2 2.3.7  .................................... [Up-to-date]
17:49:41 libpsl 0.21.0  .................................... [Up-to-date]
17:49:47 curl git  ...................................... [Already built]
17:49:47 freeglut git  .................................. [Already built]
17:50:01 libtiff git  ................................... [Already built]
17:50:04 libwebp git  ................................... [Already built]
17:50:04 gflags git  .................................... [Already built]
17:50:11 libjxl git  .................................... [Already built]
17:50:11 ├ FFmpeg and related apps will depend on OpenCL.dll
17:50:14 OpenCL-Headers git  ............................ [Already built]
17:50:17 leptonica git  ................................. [Already built]
17:50:25 tesseract git  ................................. [Already built]
17:50:26 rubberband git  ................................ [Already built]
17:50:26 zimg git  ...................................... [Already built]
17:50:26
        Starting 64bit compilation of audio tools
17:50:38 libilbc git  ................................... [Already built]
17:50:38 ogg git  ....................................... [Already built]
17:50:38 vorbis git  .................................... [Already built]
17:50:39 speex git  ..................................... [Already built]
17:50:39 flac git  ...................................... [Already built]
17:50:42 vo-amrwbenc 0.1.3  ................................ [Up-to-date]
17:50:43 fdk-aac git  ................................... [Already built]
17:50:43 opus git  ...................................... [Already built]
17:50:43 libsoxr git  ................................... [Already built]
17:50:43 codec2 git  .................................... [Already built]
17:50:44 libgme 0.6.3  ..................................... [Up-to-date]
17:50:44 libbs2b 3.1.0  .................................... [Up-to-date]
17:50:44 sndfile git  ................................... [Already built]
17:50:52   Running git update for sox...
17:50:53 ┌ sox git  .................................. [Recently updated]
17:50:54 ├ Running autoreconf...
17:51:21 ├ Running configure...
17:52:42 ├ Running make...
Likely error (tail of the failed operation logfile):
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/build/sox-git/build-64bit/lpc10'
Making all in src
make[1]: Entering directory '/build/sox-git/build-64bit/src'
  CCLD     sox.exe
D:/media-autobuild/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find @FLAC_STATIC_LIBS@: No such file or directory
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile:1570: sox.exe] Error 1
make[1]: Leaving directory '/build/sox-git/build-64bit/src'
make: *** [Makefile:680: all-recursive] Error 1
make failed. Check D:/media-autobuild/build/sox-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
17:54:00   Creating diagnostics file...

Attach D:\media-autobuild\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.

Try running the build again at a later time.
```

[logs.zip](https://github.com/user-attachments/files/15917389/logs.zip)

**Comment by Biswa96** [comment] 2024-06-20 18:01
Duplicate of #2718

**Comment by Barough** [comment] 2024-06-23 15:14
SoX built fine here yesterday on both 32bit and 64bit

**Closed** 2024-07-17 18:03 UTC
