### ISSUE TITLE
rav1e rights problem

### ISSUE THREAD

**Issue by Selur** [m-ab-s/media-autobuild_suite#1612] opened 2020-04-09 17:00 UTC
[logs.zip](https://0x0.st/iSjW.zip)
delete rav1e-git folder and started the script again
sadly I get the same error.
Also, since no other tools relies on rav1e would it be possible to proceed with the next tool ?

**Comment by 1480c1** [comment] 2020-04-09 17:11
Seems to be duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/1606

**Closed by 1480c1** 2020-04-09 17:11 UTC
