### ISSUE TITLE
[mingw32|mingw64] [repo] Vulkan-0001 Cross Compile Static Linkning Hacks Patch error

### ISSUE THREAD

**Issue by VulkanAuto** [m-ab-s/media-autobuild_suite#1677] opened 2020-05-27 01:30 UTC
Hello,

This is my first post. I wanted to compile a 64 bit version of ffmpeg with non-free settings. I am running into a problem with Vulkan-0001-cross-compile-static-linking-hacks.patch, where it gives me an error and stops. It mentions that it is a required for other packages and does not finish compiling. I searched if the issue has come up and found this (https://github.com/m-ab-s/media-autobuild_suite/issues/1657). I an not 100% sure if it is the same issues that I am experiencing since the lines from the code differ.  I've attached the log file as request. Appreciate any help or suggestions.

``` bash
18:09:40 python 3.8.2  ..................................... [Up-to-date]
18:09:41 vapoursynth R49  .................................. [Up-to-date]
18:09:41   Running git update for AviSynthPlus...
18:09:43 AviSynthPlus git  ................................. [Up-to-date]
18:09:53   Running git update for ffmpeg...
18:09:55 ffmpeg git  ....................................... [Up-to-date]
18:09:56   Running svn update for mplayer...
18:09:58 mplayer svn  ...................................... [Up-to-date]
18:10:03 ├ Compiling mpv with Vapoursynth R49
18:10:03 ├ mpv will need vapoursynth.dll and vsscript.dll to use vapoursynth filter!
18:10:03   Running git update for mujs...
18:10:05 mujs git  ......................................... [Up-to-date]
18:10:05   Running git update for vulkan-loader...
18:10:06 ┌ vulkan-loader git  ........................ [Recently updated]
18:10:07 ├ Running uninstall...
vulkan-0001-cross-compile-static-linking-hacks.patch
        Patch could not be applied with `git am`. Continuing without patching.
18:10:07 ├ Running dependencies...
18:10:11 ├ Installing Vulkan-Headers...
18:10:11 ├ Running uninstall...
18:10:11 ├ Running cmake...
18:10:11 ├ Running build...
18:10:11 ├ Running install...
18:10:13 ├ Building Vulkan-Loader...
18:10:13 ├ Running cmake...
18:10:15 ├ Running build...
Likely error (tail of the failed operation logfile):
../loader/vk_loader_platform.h:378:13: warning: 'loader_platform_thread_cond_wait' defined but not used [-Wunused-function]
  378 | static void loader_platform_thread_cond_wait(loader_platform_thread_cond *pCond, loader_platform_thread_mutex *pMutex) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../loader/vk_loader_platform.h:377:13: warning: 'loader_platform_thread_init_cond' defined but not used [-Wunused-function]
  377 | static void loader_platform_thread_init_cond(loader_platform_thread_cond *pCond) { InitializeConditionVariable(pCond); }
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../loader/vk_loader_platform.h:368:34: warning: 'loader_platform_get_thread_id' defined but not used [-Wunused-function]
  368 | static loader_platform_thread_id loader_platform_get_thread_id() { return GetCurrentThreadId(); }
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
build failed. Check D:/build/build/vulkan-loader-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
18:10:17   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/ipkQ.zip
Copy and paste [logs.zip](https://0x0.st/ipkQ.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

```

[logs.zip](https://0x0.st/ipkQ.zip)

**Comment by 1480c1** [comment] 2020-05-27 01:33
Duplicate of #1657

**Closed by 1480c1** 2020-05-27 01:33 UTC
