### ISSUE TITLE
librtmp error

### ISSUE THREAD

**Issue by lyglay1991** [m-ab-s/media-autobuild_suite#2362] opened 2023-01-21 16:01 UTC
23:52:44   Running git clone for librtmp...
23:52:58   Running git update for librtmp...
23:52:58 ┌ librtmp git  .............................. [Recently updated]
23:52:59 ├ Running install...
Likely error (tail of the failed operation logfile):
G:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: G:/media-autobuild_suite-master/local64/lib/libgnutls.a(provable-prime.o):provable-prime:(.text+0xbb6): undefined reference to `__imp___gmpz_set'
G:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: G:/media-autobuild_suite-master/local64/lib/libgnutls.a(provable-prime.o):provable-prime:(.text+0xc8c): undefined reference to `__imp___gmpz_add_ui'
G:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: G:/media-autobuild_suite-master/local64/lib/libgnutls.a(provable-prime.o):provable-prime:(.text+0xcca): undefined reference to `__imp___gmpz_clear'
G:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: G:/media-autobuild_suite-master/local64/lib/libgnutls.a(provable-prime.o):provable-prime:(.text+0xcda): undefined reference to `__imp___gmpz_clear'
G:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: G:/media-autobuild_suite-master/local64/lib/libgnutls.a(provable-prime.o):provable-prime:(.text+0xcea): undefined reference to `__imp___gmpz_clear'
G:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: G:/media-autobuild_suite-master/local64/lib/libgnutls.a(provable-prime.o):provable-prime:(.text+0xcfa): undefined reference to `__imp___gmpz_clear'
G:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: G:/media-autobuild_suite-master/local64/lib/libgnutls.a(provable-prime.o):provable-prime:(.text+0xd0a): undefined reference to `__imp___gmpz_clear'
G:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: G:/media-autobuild_suite-master/local64/lib/libgnutls.a(provable-prime.o):provable-prime:(.text+0xd1a): more undefined references to `__imp___gmpz_clear' follow
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:78: rtmpdump] Error 1
install failed. Check G:/media-autobuild_suite-master/build/librtmp-git/ab-suite.install.log
This is required for other packages, so this script will exit.
23:53:17   Creating diagnostics file...

[Attach G:\media-autobuild_suite-master\build\logs.zip ](url)

**Comment by Biswa96** [comment] 2023-01-21 16:02
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2352

**Comment by lyglay1991** [comment] 2023-01-22 09:08
thanks

**Closed** 2023-01-22 09:08 UTC
