### ISSUE TITLE
Error running build when running git clone for libwebp - collect2.exe: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#1999] opened 2021-06-14 12:11 UTC
``` bash
19:55:46   Running git clone for libwebp...
19:55:54 ┌ libwebp git  .............................. [Recently updated]
Failed to apply patch ''
Patch without filename, ignoring. Specify an explicit filename.
19:56:06 ├ Running cmake...
19:56:14 ├ Running build...
Likely error (tail of the failed operation logfile):
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x1e1a): undefined reference to `__imp_glVertexPointer'
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x1e2a): undefined reference to `__imp_glNormalPointer'
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x1e4d): undefined reference to `__imp_glTexCoordPointer'
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x1e69): undefined reference to `__imp_glDrawElements'
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x1e9e): undefined reference to `__imp_glDisableClientState'
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x1f93): undefined reference to `__imp_glDrawElements'
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/local64/lib/libglut.a(fg_geometry.c.obj):fg_geometry.c:(.text+0x1fac): undefined reference to `__imp_glDrawArrays'
C:/MinGW-w64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/MinGW-w64/local64/lib/libglut.a(fg_ext_mswin.c.obj):fg_ext_mswin.c:(.text+0x123): undefined reference to `__imp_wglGetProcAddress'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check C:/MinGW-w64/build/libwebp-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
19:56:17   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/-LgZ.zip
Copy and paste [logs.zip](https://0x0.st/-LgZ.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

[logs.zip](https://0x0.st/-LgZ.zip)
[ab-suite.build.log](https://github.com/m-ab-s/media-autobuild_suite/files/6648160/ab-suite.build.log)

**Comment by 1480c1** [comment] 2021-06-22 02:15
Working on this at https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6251

**Comment by 1480c1** [comment] 2021-06-22 02:22
Going to mark as duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/1998 and track the cmake issues there

**Closed by 1480c1** 2021-06-22 02:22 UTC
Labels: bug, external-dependency
