### ISSUE TITLE
32bit ninja vulkan-loader fails building

### ISSUE THREAD

**Issue by Selur** [m-ab-s/media-autobuild_suite#2022] opened 2021-08-15 10:14 UTC
[logs.zip](https://0x0.st/-ysA.zip) 
```
12:08:28   Running git clone for vulkan-loader...
12:08:39 ┌ vulkan-loader git  ........................ [Recently updated]
12:08:39 ├ Running uninstall...
0001-loader-cross-compile-static-linking-hacks.patch
        Patch could not be applied with `git am`. Continuing without patching.
12:08:40 ├ Running dependencies...
12:08:45 ├ Installing Vulkan-Headers...
12:08:45 ├ Running uninstall...
12:08:45 ├ Running cmake...
12:08:45 ├ Running build...
12:08:45 ├ Running install...
12:08:46 ├ Building Vulkan-Loader...
12:08:46 ├ Running cmake...
12:08:49 ├ Running build...
Likely error (tail of the failed operation logfile):
ml -DAPI_NAME=\"Vulkan\" -DVK_ENABLE_BETA_EXTENSIONS -DVK_USE_PLATFORM_WIN32_KHR -DWIN32_LEAN_AND_MEAN -II:/media-autobuild_suite/build/vulkan-loader-git/loader -II:/media-autobuild_suite/build/vulkan-loader-git/loader/generated -II:/media-autobuild_suite/build/vulkan-loader-git/build-32bit/loader  /c /Fo loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj I:/media-autobuild_suite/build/vulkan-loader-git/loader/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
ninja: fatal: GetOverlappedResult: Das Handle ist ung▒ltig.

[1/7] Building RC object loader/CMakeFiles/vulkan.dir/loader.rc.obj
[2/7] Building ASM_MASM object loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
FAILED: loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj
ml -DAPI_NAME=\"Vulkan\" -DVK_ENABLE_BETA_EXTENSIONS -DVK_USE_PLATFORM_WIN32_KHR -DWIN32_LEAN_AND_MEAN -II:/media-autobuild_suite/build/vulkan-loader-git/loader -II:/media-autobuild_suite/build/vulkan-loader-git/loader/generated -II:/media-autobuild_suite/build/vulkan-loader-git/build-32bit/loader  /c /Fo loader/CMakeFiles/loader-unknown-chain.dir/unknown_ext_chain_masm.asm.obj I:/media-autobuild_suite/build/vulkan-loader-git/loader/unknown_ext_chain_masm.asm
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.
build failed. Check I:/media-autobuild_suite/build/vulkan-loader-git/build-32bit/ab-suite.build.log
This is required for other packages, so this script will exit.
```
deleteing vulkan-loader-git an vulkan-header-git didn't help.

**Comment by 1480c1** [comment] 2021-08-15 17:13
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2020

**Closed by 1480c1** 2021-08-15 17:13 UTC
