### ISSUE TITLE
[mingw64] [ffmpeg] SVT-HEVC inconsistencies mess up the entire FFmpeg compile.

### ISSUE THREAD

**Issue by BedrockDotPng** [m-ab-s/media-autobuild_suite#2164] opened 2022-04-07 14:52 UTC
``` bash
18:00:26(B ┌ ffmpeg git (B ............................... [Recently updated(B]
18:00:26(B ├(B Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.(B
master-0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch(B
	Patch could not be applied with `git am`. Continuing without patching.
18:00:36(B ├(B Compiling shared(B FFmpeg...
18:00:38(B ├(B Running configure...
18:08:23(B ├(B Running make...
Likely error (tail of the failed operation logfile):
dlltool -m i386:x86-64 -d libpostproc/postproc-56.def -l libpostproc/postproc.lib -D postproc-56.dll
CC	libavcodec/libsvt_hevc.o
C:/media-autobuild_suite-master/build/ffmpeg-git/libavcodec/libsvt_hevc.c:571:6: error: 'FFCodec' has no member named 'encode2'
  571 |     .encode2        = eb_encode_frame,
      |      ^~~~~~~
C:/media-autobuild_suite-master/build/ffmpeg-git/libavcodec/libsvt_hevc.c:571:23: warning: initialization of 'int (*)(struct AVCodecContext *, struct AVFrame *, int *, struct AVPacket *)' from incompatible pointer type 'int (*)(AVCodecContext *, AVPacket *, const AVFrame *, int *)' [-Wincompatible-pointer-types]
  571 |     .encode2        = eb_encode_frame,
      |                       ^~~~~~~~~~~~~~~
C:/media-autobuild_suite-master/build/ffmpeg-git/libavcodec/libsvt_hevc.c:571:23: note: (near initialization for 'ff_libsvt_hevc_encoder.cb.decode')
make: *** [/build/ffmpeg-git/ffbuild/common.mak:78: libavcodec/libsvt_hevc.o] Error 1
make failed. Check C:/media-autobuild_suite-master/build/ffmpeg-git/build-shared-64bit/ab-suite.make.log(B
This is required for other packages, so this script will exit.(B
18:44:01(B   Creating diagnostics file...

```

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/8444018/logs.zip)

**Comment by 1480c1** [comment] 2022-04-16 01:35
For now, https://github.com/OpenVisualCloud/SVT-HEVC/issues/616

**Comment by 1480c1** [comment] 2022-04-20 17:16
duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2148

**Closed by 1480c1** 2022-04-20 17:16 UTC
