### ISSUE TITLE
cargo-c build failed

### ISSUE THREAD

**Issue by Selur** [m-ab-s/media-autobuild_suite#1822] opened 2020-09-30 17:08 UTC
``` 
19:06:44   Running git update for cargo-c...
19:06:44 ┌ cargo-c git  .............................. [Recently updated]
19:06:44 ├ Running rust.update...
19:06:46 ├ Running rust.install...
Likely error (tail of the failed operation logfile):


error: aborting due to previous error

error: aborting due to previous error

error: failed to compile `cargo-c v0.6.13 (I:\media-autobuild_suite\build\cargo-c-git)`, intermediate artifacts can be found at `I:\media-autobuild_suite\build\cargo-c-git\target`

Caused by:
  build failed
rust.install failed. Check I:/media-autobuild_suite/build/cargo-c-git/ab-suite.rust.install.log
This is required for other packages, so this script will exit.
19:06:48   Creating diagnostics file...
```

All relevant logs have been anonymously uploaded to https://0x0.st/iU0X.zip
Copy and paste [logs.zip](https://0x0.st/iU0X.zip) in the GitHub issue.
(deleting the cargo-c-git folder didn't help)

**Comment by 1480c1** [comment] 2020-09-30 17:11
duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/1819

**Closed by 1480c1** 2020-09-30 17:11 UTC
