### ISSUE TITLE
[mingw32|mingw64] [repo] Undefined reference to spvtools::Optimizer...

### ISSUE THREAD

**Issue by asitjain** [m-ab-s/media-autobuild_suite#2107] opened 2022-01-22 15:41 UTC
Hi,

I tried all the options I could think of, but this error won't go away. Please help.

``` bash
1m┌ mpv git (B[m ............................................ [[311mRecently updated(B[m]
[1m├(B[m Running bootstrap...
[1m├(B[m Running configure...
[1m├(B[m Running build...
Likely error (tail of the failed operation logfile):
C:/tempwork/myFFMPEG/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/tempwork/myFFMPEG/local64/lib/libshaderc_util.a(spirv_tools_wrapper.cc.o):spirv_tools_wrapper.cc:(.text+0x12ba): undefined reference to `spvtools::Optimizer::~Optimizer()'

C:/tempwork/myFFMPEG/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/tempwork/myFFMPEG/local64/lib/libshaderc_util.a(spirv_tools_wrapper.cc.o):spirv_tools_wrapper.cc:(.text+0x12c2): undefined reference to `spvOptimizerOptionsDestroy'

C:/tempwork/myFFMPEG/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/tempwork/myFFMPEG/local64/lib/libshaderc_util.a(spirv_tools_wrapper.cc.o):spirv_tools_wrapper.cc:(.text+0x12ca): undefined reference to `spvValidatorOptionsDestroy'

C:/tempwork/myFFMPEG/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/tempwork/myFFMPEG/local64/lib/libshaderc_util.a(spirv_tools_wrapper.cc.o):spirv_tools_wrapper.cc:(.text+0x12e2): undefined reference to `spvtools::Optimizer::PassToken::~PassToken()'

collect2.exe: error: ld returned 1 exit status

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
[31mbuild failed. Check C:/tempwork/myFFMPEG/build/mpv-git/ab-suite.build.log(B[m
[31mThis is required for other packages, so this script will exit.(B[m
```
[logs.zip](https://0x0.st/ooL6.zip)

**Comment by 1480c1** [comment] 2022-01-22 21:24
Seems to be a duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2104

**Closed by 1480c1** 2022-01-22 21:24 UTC

**Comment by asitjain** [comment] 2022-01-23 14:51
Hi,

Solved. I started with a clean slate and downloaded and ran the script in a new folder, and it worked as advertised 😊.
