### ISSUE TITLE
dssim build error

### ISSUE THREAD

**Issue by dbyoung720** [m-ab-s/media-autobuild_suite#2584] opened 2024-01-21 23:18 UTC
Likely error (tail of the failed operation logfile):
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `num-bigint` (build script) due to previous error
error: could not compile `num-integer` (build script) due to previous error
error: could not compile `crc32fast` (build script) due to previous error
error: could not compile `num-traits` (build script) due to previous error
error: could not compile `num-rational` (build script) due to previous error
error: could not compile `ahash` (build script) due to previous error
error: could not compile `crossbeam-utils` (build script) due to previous error
error: could not compile `proc-macro2` (build script) due to previous error
error: could not compile `rayon-core` (build script) due to previous error
error: could not compile `libc` (build script) due to previous error
rust.build failed. Check F:/Source/ffother/MAS/build/dssim-git/ab-suite.rust.build.log
This is required for other packages, so this script will exit.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/14003151/logs.zip)

**Comment by 1480c1** [comment] 2024-01-22 23:06
I am unable to reproduce using the same config, can you check again?

**Comment by dbyoung720** [comment] 2024-01-24 11:24
update to new


19:22:15 ┌ dssim git  ................................ [Recently updated]
19:22:15 ├ Running rust.update...
Likely error (tail of the failed operation logfile):
CXXFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1
LDFLAGS: -D_FORTIFY_SOURCE=2 -fstack-protector-strong -mtune=generic -O2 -pipe -D__USE_MINGW_ANSI_STDIO=1 -static-libgcc -static-libstdc++
/opt/cargo/bin/cargo.exe update
error: failed to load manifest for dependency `ordered-channel`

Caused by:
  failed to read `F:\Source\ffother\MAS\build\ordered-channel\Cargo.toml`

Caused by:
  The system cannot find the path specified. (os error 3)
rust.update failed. Check F:/Source/ffother/MAS/build/dssim-git/ab-suite.rust.update.log
This is required for other packages, so this script will exit.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/14037477/logs.zip)

**Comment by dbyoung720** [comment] 2024-01-24 11:28
I repeat git clone.

error same as.

**Comment by hydra3333** [comment] 2024-01-24 23:37
Hello.  I also receive this now, in a fresh VM and MABS download.  

Given it worked yesterday with the same latest MABS (with the vapoursynth change to use python 3.11.7) it would appear that something upstream has broken ?

Cheers

**Comment by 1480c1** [comment] 2024-01-25 01:08
I thought I commented, but I guess I never pressed the button

Upstream issue filled at https://github.com/kornelski/dssim/issues/153

**Comment by 1480c1** [comment] 2024-01-26 18:08
Fixed with https://github.com/kornelski/dssim/commit/f3e2191efed786081f780ddea08a1e6027f31680

**Closed by 1480c1** 2024-01-26 18:08 UTC
