### ISSUE TITLE
fault building mpv

### ISSUE THREAD

**Issue by j-mas** [m-ab-s/media-autobuild_suite#1574] opened 2020-03-04 23:00 UTC
23:55:26 ┌ mpv git  ..................................... [Files missing]
23:55:27 ├ Running bootstrap...
23:55:31 ├ Uninstalling python3-docutils... failed
23:55:35 ├ Running configure...
23:55:58 ├ Running build...
Likely error (tail of the failed operation logfile):
collect2.exe: error: ld returned 1 exit status

C:/media-autobuild_suite-master/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/media-autobuild_suite-master/local64/lib\libdvdread.a(dvd_input.o):dvd_input.c:(.text+0x21f): undefined reference to `strerror_r'
C:/media-autobuild_suite-master/local64/lib\libdvdread.a(dvd_input.o):dvd_input.c:(.text+0x21f): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `strerror_r'
collect2.exe: error: ld returned 1 exit status

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
build failed. Check C:/media-autobuild_suite-master/build/mpv-git/ab-suite.build.log
This is required for other packages, so this script will exit.
23:56:28   Creating diagnostics file...

**Comment by 1480c1** [comment] 2020-03-05 15:17
Seems near duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/1576 due to libdvdread

**Closed by 1480c1** 2020-03-05 15:17 UTC
