### ISSUE TITLE
[mingw64] [libavif] undefined reference to `warn' subcommand failed Linking avifdec.exe undefined reference to `warn'

### ISSUE THREAD

**Issue by chirrilover** [m-ab-s/media-autobuild_suite#1924] opened 2021-02-26 20:09 UTC
6d012fa

 libavif git  ........................................ [Recently updated]
├ Running cmake...
├ Running build...
Likely error (tail of the failed operation logfile):
cmd.exe /C "cd . && C:\mabs\msys64\mingw64\bin\ccache.exe  gcc -mthreads -mtune=generic -O2 -pipe -O3 -DNDEBUG -pipe -static-libgcc -static-libstdc++ CMakeFiles/avifenc.dir/apps/avifenc.c.o CMakeFiles/avifenc.dir/apps/shared/avifjpeg.c.o CMakeFiles/avifenc.dir/apps/shared/iccjpeg.c.o CMakeFiles/avifenc.dir/apps/shared/avifpng.c.o CMakeFiles/avifenc.dir/apps/shared/avifutil.c.o CMakeFiles/avifenc.dir/apps/shared/y4m.c.o -o avifenc.exe -Wl,--out-implib,libavifenc.dll.a -Wl,--major-image-version,0,--minor-image-version,0  libavif.a  -lm  -lws2_32  -luserenv  C:/mabs/msys64/mingw64/lib/libpng.a  C:/mabs/msys64/mingw64/lib/libz.a  C:/mabs/msys64/mingw64/lib/libjpeg.a  C:/mabs/local64/lib/libdav1d.a  C:/mabs/local64/lib/librav1e.a  C:/mabs/local64/lib/libaom.a  -lm  -lws2_32  -luserenv  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/libaom.a(av1_cx_iface.c.o):av1_cx_iface.c:(.text+0x4570): undefined reference to `warn'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
[1/2] Linking C executable avifdec.exe
FAILED: avifdec.exe
cmd.exe /C "cd . && C:\mabs\msys64\mingw64\bin\ccache.exe  gcc -mthreads -mtune=generic -O2 -pipe -O3 -DNDEBUG -pipe -static-libgcc -static-libstdc++ CMakeFiles/avifdec.dir/apps/avifdec.c.o CMakeFiles/avifdec.dir/apps/shared/avifjpeg.c.o CMakeFiles/avifdec.dir/apps/shared/iccjpeg.c.o CMakeFiles/avifdec.dir/apps/shared/avifpng.c.o CMakeFiles/avifdec.dir/apps/shared/avifutil.c.o CMakeFiles/avifdec.dir/apps/shared/y4m.c.o -o avifdec.exe -Wl,--out-implib,libavifdec.dll.a -Wl,--major-image-version,0,--minor-image-version,0  libavif.a  -lm  -lws2_32  -luserenv  C:/mabs/msys64/mingw64/lib/libpng.a  C:/mabs/msys64/mingw64/lib/libz.a  C:/mabs/msys64/mingw64/lib/libjpeg.a  C:/mabs/local64/lib/libdav1d.a  C:/mabs/local64/lib/librav1e.a  C:/mabs/local64/lib/libaom.a  -lm  -lws2_32  -luserenv  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
C:/mabs/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/mabs/local64/lib/libaom.a(av1_cx_iface.c.o):av1_cx_iface.c:(.text+0x4570): undefined reference to `warn'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/6052209/logs.zip)

**Comment by 1480c1** [comment] 2021-02-26 22:08
duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/1919, but fixed upstream

**Closed by 1480c1** 2021-02-26 22:08 UTC

**Comment by chirrilover** [comment] 2021-03-01 15:59
Super! Thank you
