### ISSUE TITLE
[mingw32|mingw64] [repo]- build 64 bits, fails to compile libmediainfo

### ISSUE THREAD

**Issue by WorfKlingon** [m-ab-s/media-autobuild_suite#1844] opened 2020-11-04 09:55 UTC
Launch update_suite.sh with mintty
Launch media-autobuild_suite.bat with PowerShel 7.03 (same with  5.1.19041.610)

unable to compile libmediainfo

It's my first test with your tool and my opinion it's a powerfull tool. I hope that i provide properly my issue in right location

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5486977/logs.zip)

``` bash
Paste output of the suite here
```

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite)

**Comment by Obrell86** [comment] 2020-11-04 21:24
I also got this.
[logs.zip](https://0x0.st/id3G.zip)

**Comment by 1480c1** [comment] 2020-11-04 22:00
Duplicate of #1836

**Closed by 1480c1** 2020-11-04 22:00 UTC
