### ISSUE TITLE
[mingw64] [ffmpeg] ffmpeg building stops because of libjxl error

### ISSUE THREAD

**Issue by BlackScreen** [m-ab-s/media-autobuild_suite#2193] opened 2022-05-18 08:05 UTC
```
09:58:52   Running git update for ffmpeg...
09:58:54 ┌ ffmpeg git  ............................... [Recently updated]
09:58:54 ├ Changing options to comply to nonfree...
CUDA_PATH environment variable not set or directory does not exist.
master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
        Patch could not be applied with `git am`. Continuing without patching.
09:59:02 ├ Compiling static FFmpeg...
09:59:05 ├ Running configure...
Likely error (tail of the failed operation logfile):
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config=pkgconf --pkg-config-flags=--keep-system-libs --keep-system-cflags --static --cc=ccache gcc --cxx=ccache g++ --ld=ccache g++ --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libaom --disable-debug --enable-libfdk-aac --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libopenmpt --enable-version3 --enable-librav1e --enable-libsrt --enable-libgsm --enable-libvmaf --enable-libsvtav1 --enable-chromaprint --enable-decklink --enable-frei0r --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfribidi --enable-libgme --enable-libilbc --enable-libkvazaar --enable-libmodplug --enable-librist --enable-librtmp --enable-librubberband --enable-libtesseract --enable-libxavs --enable-libzmq --enable-libzvbi --enable-openal --enable-libcodec2 --enable-ladspa --enable-libglslang --enable-vulkan --enable-libdavs2 --enable-libxavs2 --enable-libuavs3d --enable-libplacebo --enable-libjxl --enable-opencl --enable-opengl --enable-libopenh264 --enable-openssl --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --enable-nonfree --extra-cflags=-DAL_LIBTYPE_STATIC --extra-cflags=-IC:/Development/MABS_All/local64/include --extra-cflags=-IC:/Development/MABS_All/local64/include/AL --extra-version=ge3580f6077+1
ERROR: libjxl >= 0.7.0 not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
configure failed. Check C:/Development/MABS_All/build/ffmpeg-git/build-static-64bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
10:03:50   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oa8F.zip
Copy and paste [logs.zip](https://0x0.st/oa8F.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

**Comment by crhepner** [comment] 2022-05-19 06:37
I am having the same problem.

```
  Running git update for ffmpeg...
┌ ffmpeg git  ............................................ [Updates found]
├ Changing options to comply to nonfree...
FFmpeg and related apps will depend on CUDA SDK to run!
master-0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
        Patch could not be applied with `git am`. Continuing without patching.
├ Compiling static FFmpeg...
├ Running configure...
Likely error (tail of the failed operation logfile):
CXXFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config=pkgconf --pkg-config-flags=--keep-system-libs --keep-system-cflags --static --cc=ccache gcc --cxx=ccache g++ --ld=ccache g++ --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libaom --disable-debug --enable-libfdk-aac --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libopenmpt --enable-version3 --enable-librav1e --enable-libsrt --enable-libgsm --enable-libvmaf --enable-libsvtav1 --enable-chromaprint --enable-decklink --enable-frei0r --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfribidi --enable-libgme --enable-libilbc --enable-libkvazaar --enable-libmodplug --enable-librist --enable-librtmp --enable-librubberband --enable-libtesseract --enable-libxavs --enable-libzmq --enable-libzvbi --enable-openal --enable-libcodec2 --enable-ladspa --enable-libglslang --enable-vulkan --enable-libdavs2 --enable-libxavs2 --enable-libuavs3d --enable-libplacebo --enable-libjxl --enable-opencl --enable-opengl --enable-libnpp --enable-libopenh264 --enable-openssl --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --enable-nonfree --extra-cflags=-IC:/PROGRA~1/NVIDIA~2/CUDA/v11.3/include --extra-ldflags=-LC:/PROGRA~1/NVIDIA~2/CUDA/v11.3/lib/x64 --extra-cflags=-DAL_LIBTYPE_STATIC --extra-cflags=-IC:/ab-suite-20210823/local64/include --extra-cflags=-IC:/ab-suite-20210823/local64/include/AL --extra-version=gb8ede4d637+1
ERROR: libjxl >= 0.7.0 not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
configure failed. Check C:/ab-suite-20210823/build/ffmpeg-git/build-static-64bit/ab-suite.configure.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oaq9.zip
Copy and paste [logs.zip](https://0x0.st/oaq9.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

Here are my logs: [logs.zip](https://0x0.st/oaq9.zip)

**Comment by 1480c1** [comment] 2022-05-19 17:46
tried running the suite last night, but wasn't able to reproduce the issue

Did libjxl not install the required header?

**Comment by 1480c1** [comment] 2022-05-19 19:12
Ah, I found the issue, since we manually install the libraries and stuff, we didn't actually install the headers,

@woot000 do you know how the build managed to pass before?

**Comment by 1480c1** [comment] 2022-05-19 19:18
I also don't know why my builds worked as well, too. Probably due to a previous build that had ninja install

**Comment by crhepner** [comment] 2022-05-19 22:16
It looks like copying the contents of both /build/libjxl-git/lib/include/jxl and /build/libjxl-git/build-64bit/lib/include/jxl to /local64/include/jxl allows ffmpeg to compile without any errors.  I initially tried copying just the first one (/build/libjxl-git/lib/include/jxl), but I got an error saying that jxl_export.h was missing, so I needed to copy the contents of the second folder as well.

**Comment by BlackScreen** [comment] 2022-05-20 09:03
I can confirm, that the copy process described by @crhepner works. With that the build was successful.
Maybe we can get it working without the copy process. :)

**Comment by woot000** [comment] 2022-05-22 20:42
> Ah, I found the issue, since we manually install the libraries and stuff, we didn't actually install the headers,
> 
> @woot000 do you know how the build managed to pass before?

I think my previous attempts at doing the install process all at once left those include directories installed in my local64 folder, I guess I hadn't noticed

I tried adding ```do_install {,../}lib/include/jxl/*.h include/jxl/``` to the build script, but that doesn't seem to be even creating the directory for the files to install into

Any thoughts? @1480c1

**Comment by 1480c1** [comment] 2022-05-22 20:43
Right now working on a branch in my fork to fix this, I got the clang and gcc builds to pass last night, so I will be pushing them to master soon

**Comment by 1480c1** [comment] 2022-05-31 21:15
Should have been fixed in https://github.com/m-ab-s/media-autobuild_suite/commit/f90b381e152fd3af28cf6c115c46246a71a7063c

**Closed by 1480c1** 2022-05-31 21:15 UTC
