### ISSUE TITLE
Mediainfo make bug

### ISSUE THREAD

**Issue by mecurry0232** [m-ab-s/media-autobuild_suite#1848] opened 2020-11-09 16:40 UTC
During making Mediainfo, Cmake shows error in other package needed. The error log has been attached in here.

[in1b.zip](https://github.com/m-ab-s/media-autobuild_suite/files/5511931/in1b.zip)

**Comment by wiiaboo** [comment] 2020-11-09 16:46
Duplicate of #1836

**Closed by wiiaboo** 2020-11-09 16:46 UTC
