### ISSUE TITLE
Error running meson when running git update for libplacebo

### ISSUE THREAD

**Issue by ycwan** [m-ab-s/media-autobuild_suite#2291] opened 2022-09-25 07:52 UTC
15:32:02   Running git update for libplacebo...
15:32:07 ┌ libplacebo git  .............................. [Updates found]
0001-meson-use-shaderc_combined.patch
        Patch could not be applied with `git am`. Continuing without patching.
0002-spirv-cross-use-spirv-cross-instead-of-c-shared.patch
        Patch could not be applied with `git am`. Continuing without patching.
15:32:11 ├ Running uninstall...
15:32:14 ├ Running meson...
Likely error (tail of the failed operation logfile):
Run-time dependency libunwind found: NO (tried pkgconfig and cmake)
Library execinfo found: NO
Checking for function "backtrace_symbols" with dependency -lexecinfo: NO
Run-time dependency shaderc found: YES 2022.2.0
Message: Skipping `glslang` because `shaderc` is available
Run-time dependency spirv-cross-c-shared found: NO (tried pkgconfig and cmake)

../src/d3d11/meson.build:3:0: ERROR: Dependency "spirv-cross-c-shared" not found, tried pkgconfig and cmake

A full log can be found at C:/MinGW-w64/build/libplacebo-git/build-64bit/meson-logs/meson-log.txt
meson failed. Check C:/MinGW-w64/build/libplacebo-git/build-64bit/ab-suite.meson.log
This is required for other packages, so this script will exit.
15:32:22   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/oWWi.zip
Copy and paste [logs.zip](https://0x0.st/oWWi.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

[logs.zip](https://0x0.st/oWWi.zip)
[meson-log.txt](https://github.com/m-ab-s/media-autobuild_suite/files/9640242/meson-log.txt)
[ab-suite.meson.log](https://github.com/m-ab-s/media-autobuild_suite/files/9640246/ab-suite.meson.log)

**Comment by Barough** [comment] 2022-09-25 08:18
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2287

**Comment by 1480c1** [comment] 2022-09-25 15:10
Duplicate of https://github.com/m-ab-s/media-autobuild_suite/issues/2287

**Closed by 1480c1** 2022-09-25 15:10 UTC
